# Wikipedia State and City Article Quality Analysis

## Data Acquisition: Article, Population, and Region Data

This analysis involves collecting data that lists Wikipedia articles about US cities and data for US state populations. Data regarding lists of cities in the United States by state was obtained by the teaching staff (University of Washington Master of Science in Data Science: DATA 512) by crawling this [Wikipedia page](https://en.wikipedia.org/wiki/Category:Lists_of_cities_in_the_United_States_by_state). I downloaded this data to my local device in the form of a csv file (*us_cities_by_state_SEPT.2023.csv*), accessed at this [link](https://drive.google.com/file/d/1khouDmMaZyKo0y5WkFj4lu7g8o35x_98/view?usp=drive_link) on 10/11/2023.

In [200]:
import pandas as pd

# Import list of cities by state
us_cities_by_state_df = pd.read_csv("us_cities_by_state_SEPT.2023.csv")

# View data
us_cities_by_state_df.head()

state           page_title  \
0  Alabama   Abbeville, Alabama   
1  Alabama  Adamsville, Alabama   
2  Alabama     Addison, Alabama   
3  Alabama       Akron, Alabama   
4  Alabama   Alabaster, Alabama   

                                                 url  
0   https://en.wikipedia.org/wiki/Abbeville,_Alabama  
1  https://en.wikipedia.org/wiki/Adamsville,_Alabama  
2     https://en.wikipedia.org/wiki/Addison,_Alabama  
3       https://en.wikipedia.org/wiki/Akron,_Alabama  
4   https://en.wikipedia.org/wiki/Alabaster,_Alabama

The next step involves getting data related to population estimates for every US state as of 2022. This data was obtained from the US Census Bureau at this [link](https://www.census.gov/data/tables/time-series/demo/popest/2020s-state-total.html) on 10/11/2023. I downloaded the data to my local device in the form of an csv file (*NST-EST2022-ALLDATA.csv*).

In [3]:
# Import population estimates
pop_estimates_df = pd.read_csv("NST-EST2022-ALLDATA.csv")

# View data
pop_estimates_df.head()

SUMLEV REGION DIVISION  STATE              NAME  ESTIMATESBASE2020  \
0      10      0        0      0     United States          331449520   
1      20      1        0      0  Northeast Region           57609156   
2      30      1        1      0       New England           15116206   
3      30      1        2      0   Middle Atlantic           42492950   
4      20      2        0      0    Midwest Region           68985537   

   POPESTIMATE2020  POPESTIMATE2021  POPESTIMATE2022  NPOPCHG_2020  ...  \
0        331511512        332031554        333287557         61992  ...   
1         57448898         57259257         57040406       -160258  ...   
2         15074473         15121745         15129548        -41733  ...   
3         42374425         42137512         41910858       -118525  ...   
4         68961043         68836505         68787595        -24494  ...   

   RDEATH2021  RDEATH2022  RNATURALCHG2021  RNATURALCHG2022  \
0   10.363828   10.350218         0.434073         0.736729   
1    9.780142    9.868918         0.206629         0.511200   
2    9.530598    9.887115        -0.310502        -0.206669   
3    9.869304    9.862369         0.391400         0.769581   
4   11.059195   11.169148        -0.207043        -0.125530   

   RINTERNATIONALMIG2021  RINTERNATIONALMIG2022  RDOMESTICMIG2021  \
0               1.133397               3.038912          0.000000   
1               1.402708               3.752662         -4.855348   
2               1.770752               4.655140          1.546021   
3               1.271205               3.427836         -7.142565   
4               0.802714               2.111084         -2.645374   

   RDOMESTICMIG2022  RNETMIG2021  RNETMIG2022  
0          0.000000     1.133397     3.038912  
1         -8.061896    -3.452640    -4.309234  
2         -3.767839     3.316773     0.887301  
3         -9.607444    -5.871360    -6.179608  
4         -2.529339    -1.842660    -0.418255  

[5 rows x 45 columns]

As this dataset contains many columns, I clean the dataframe to only include the columns we are interested in (the name of the state, and the 2022 population estimate).

In [4]:
# Keep only the columns we are interested in
pop_estimates_df = pop_estimates_df[['NAME','POPESTIMATE2022']]

# View data
pop_estimates_df.head()

NAME  POPESTIMATE2022
0     United States        333287557
1  Northeast Region         57040406
2       New England         15129548
3   Middle Atlantic         41910858
4    Midwest Region         68787595

For this analysis, I use the regional and divisional agglomerations as defined by the US Census Bureau. I obtained a spreadsheet listing the states in each regional division at this [link](https://docs.google.com/spreadsheets/d/14Sjfd_u_7N9SSyQ7bmxfebF_2XpR8QamvmNntKDIQB0/edit?usp=drive_link), and downloaded it to my local device on 10/11/2023 titled *US States by Region - US Census Bureau.xlsx*. As this is in an hierarchical table format, I reformat it into a flat format and remove NA values.

In [5]:
# Import states by regional division
states_regions_df = pd.read_excel("US States by Region - US Census Bureau.xlsx")

# Format is hierarchical
states_regions_df.head()

REGION     DIVISION          STATE
0  Northeast          NaN            NaN
1        NaN  New England            NaN
2        NaN          NaN    Connecticut
3        NaN          NaN          Maine
4        NaN          NaN  Massachusetts

In [6]:
# Forward fill blank cells with value above
states_regions_df['REGION'] = states_regions_df['REGION'].fillna(method='ffill')
states_regions_df['DIVISION'] = states_regions_df['DIVISION'].fillna(method='ffill')

# Drop NAs
states_regions_df = states_regions_df.dropna().reset_index(drop=True)

# View dataframe
states_regions_df.head()

REGION     DIVISION          STATE
0  Northeast  New England    Connecticut
1  Northeast  New England          Maine
2  Northeast  New England  Massachusetts
3  Northeast  New England  New Hampshire
4  Northeast  New England   Rhode Island

### Inconsistencies

In [7]:
len(us_cities_by_state_df) # Number of rows in dataframe

22157

In [8]:
us_cities_by_state_df.nunique() # Number of unique city names

state            48
page_title    21519
url           21519
dtype: int64

As shown above, an inconsistency that I found is that the *us_cities_by_state* file contains over 600 duplicates. This is because crawling Wikipedia categories can result is misleading and duplicate category labels due to limited consistency in naming conventions. In order to fix this inconsistency, I have removed all the duplicate values below.

In [232]:
us_cities_by_state_df = us_cities_by_state_df.drop_duplicates().reset_index(drop=True) # Drop duplicates

In [233]:
us_cities_by_state_df['state'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

Another inconsistency I found is that the above table only contains 48 out of the 50 states. This data set does not include Connecticut or Nebraska.

## Article Quality Predictions

This step involves getting the predicted quality scores for each article in the Wikipedia dataset.

First, I obtain a list of article names using the last column of the *us_cities_by_state* dataframe. Specifically, I use string methods to return the name of the article by extracting the string after the last slash in the url column.

In [11]:
article_titles_states = us_cities_by_state_df['url'].apply(lambda x: x.rsplit('/', 1)[-1]) # Extract string after last slash

Code in an example notebook, provided by Dr. David W McDonald and accessed at this [link](https://drive.google.com/file/d/15UoE16s-IccCTOXREjU3xDIz07tlpyrl/view?usp=drive_link) has been modified and used below. This code has been provided under the [Creative Commons](https://creativecommons.org) [CC-BY license](https://creativecommons.org/licenses/by/4.0/). Revision 1.1 - August 14, 2023

The code below accesses page info data using the [MediaWiki REST API for the EN Wikipedia](https://www.mediawiki.org/wiki/API:Main_page). Summary 'page_info' is requested for an article page. API documentation for the MediaWiki REST API can be accessed at this [link](https://www.mediawiki.org/wiki/API:Info).

In [12]:
# Code from Dr. McDonald
# These are standard python modules
import json, time, urllib.parse
#
# The 'requests' module is not a standard Python module. You will need to install this with pip/pip3 if you do not already have it
import requests

The code below creates constants that specify features such as the API endpoint and article titles of interest.

In [13]:
# Code from Dr. McDonald
#########
#
#    CONSTANTS
#

# The basic English Wikipedia API endpoint
API_ENWIKIPEDIA_ENDPOINT = "https://en.wikipedia.org/w/api.php"

# We'll assume that there needs to be some throttling for these requests - we should always be nice to a free data resource
API_LATENCY_ASSUMED = 0.002       # Assuming roughly 2ms latency on the API and network
API_THROTTLE_WAIT = (1.0/100.0)-API_LATENCY_ASSUMED

# When making automated requests we should include something that is unique to the person making the request
# This should include an email - your UW email would be good to put in there
REQUEST_HEADERS = {
    'User-Agent': '<tejalk@uw.edu>, University of Washington, MSDS DATA 512 - AUTUMN 2023',
}

# List of article titles
ARTICLE_TITLES = article_titles_states
# ARTICLE_TITLES = article_titles_states[0:10]

# This is a string of additional page properties that can be returned see the Info documentation for
# what can be included. If you don't want any this can simply be the empty string
PAGEINFO_EXTENDED_PROPERTIES = ""

# This template lists the basic parameters for making this
PAGEINFO_PARAMS_TEMPLATE = {
    "action": "query",
    "format": "json",
    "titles": "",           # to simplify this should be a single page title at a time
    "prop": "info",
    "inprop": PAGEINFO_EXTENDED_PROPERTIES
}

The function below has also been modified from code provided by Dr. McDonald in the example notebook attributed above. This function makes the API request using the constants specified above.

In [14]:
# Code from Dr. McDonald
#########
#
#    PROCEDURES/FUNCTIONS
#

def request_pageinfo_per_article(article_title = None, 
                                 endpoint_url = API_ENWIKIPEDIA_ENDPOINT, 
                                 request_template = PAGEINFO_PARAMS_TEMPLATE,
                                 headers = REQUEST_HEADERS):
    
    # article title can be as a parameter to the call or in the request_template
    if article_title:
        request_template['titles'] = article_title

    if not request_template['titles']:
        raise Exception("Must supply an article title to make a pageinfo request.")

    # make the request
    try:
        # we'll wait first, to make sure we don't exceed the limit in the situation where an exception
        # occurs during the request processing - throttling is always a good practice with a free
        # data source like Wikipedia - or any other community sources
        if API_THROTTLE_WAIT > 0.0:
            time.sleep(API_THROTTLE_WAIT)
        response = requests.get(endpoint_url, headers=headers, params=request_template)
        json_response = response.json()
    except Exception as e:
        print(e)
        json_response = None
    return json_response

The function is called below and the list of article titles are iterated through in order to get information for each article title, which is then saved in a list.

In [16]:
all_pages = []
for i in range(0,len(ARTICLE_TITLES)):
    current_view = request_pageinfo_per_article(ARTICLE_TITLES[i])
    print(ARTICLE_TITLES[i]) # make sure all pages are getting printed
    all_pages.append(current_view)

Abbeville,_Alabama
Adamsville,_Alabama
Addison,_Alabama
Akron,_Alabama
Alabaster,_Alabama
Albertville,_Alabama
Alexander_City,_Alabama
Aliceville,_Alabama
Allgood,_Alabama
Altoona,_Alabama
Andalusia,_Alabama
Anderson,_Lauderdale_County,_Alabama
Anniston,_Alabama
Arab,_Alabama
Ardmore,_Alabama
Argo,_Alabama
Ariton,_Alabama
Arley,_Alabama
Ashford,_Alabama
Ashland,_Alabama
Ashville,_Alabama
Athens,_Alabama
Atmore,_Alabama
Attalla,_Alabama
Auburn,_Alabama
Autaugaville,_Alabama
Avon,_Alabama
Babbie,_Alabama
Baileyton,_Alabama
Bakerhill,_Alabama
Banks,_Alabama
Bay_Minette,_Alabama
Bayou_La_Batre,_Alabama
Bear_Creek,_Alabama
Beatrice,_Alabama
Beaverton,_Alabama
Belk,_Alabama
Benton,_Alabama
Berlin,_Alabama
Berry,_Alabama
Bessemer,_Alabama
Billingsley,_Alabama
Birmingham,_Alabama
Black,_Alabama
Blountsville,_Alabama
Blue_Springs,_Alabama
Boaz,_Alabama
Boligee,_Alabama
Bon_Air,_Alabama
Brantley,_Alabama
Brent,_Alabama
Brewton,_Alabama
Bridgeport,_Alabama
Brighton,_Alabama
Brilliant,_Alabama
Bro

Waverly,_Alabama
Weaver,_Alabama
Webb,_Alabama
Wedowee,_Alabama
West_Blocton,_Alabama
West_Jefferson,_Alabama
West_Point,_Alabama
Westover,_Alabama
Wetumpka,_Alabama
White_Hall,_Alabama
Wilsonville,_Alabama
Wilton,_Alabama
Winfield,_Alabama
Woodland,_Alabama
Woodstock,_Alabama
Woodville,_Alabama
Yellow_Bluff,_Alabama
York,_Alabama
Adak,_Alaska
Akhiok,_Alaska
Akiak,_Alaska
Akutan,_Alaska
Alakanuk,_Alaska
Aleknagik,_Alaska
Allakaket,_Alaska
Ambler,_Alaska
Anaktuvuk_Pass,_Alaska
Anchorage,_Alaska
Anderson,_Alaska
Angoon,_Alaska
Aniak,_Alaska
Anvik,_Alaska
Atka,_Alaska
Atqasuk,_Alaska
Bethel,_Alaska
Bettles,_Alaska
Brevig_Mission,_Alaska
Buckland,_Alaska
Chefornak,_Alaska
Chevak,_Alaska
Chignik,_Alaska
Chuathbaluk,_Alaska
Clark's_Point,_Alaska
Coffman_Cove,_Alaska
Cold_Bay,_Alaska
Cordova,_Alaska
Craig,_Alaska
Deering,_Alaska
Delta_Junction,_Alaska
Dillingham,_Alaska
Diomede,_Alaska
Eagle,_Alaska
Edna_Bay,_Alaska
Eek,_Alaska
Egegik,_Alaska
Ekwok,_Alaska
Elim,_Alaska
Emmonak,_Alaska
Fairban

Greenland,_Arkansas
Greenway,_Arkansas
Greenwood,_Arkansas
Greers_Ferry,_Arkansas
Griffithville,_Arkansas
Grubbs,_Arkansas
Guion,_Arkansas
Gum_Springs,_Arkansas
Gurdon,_Arkansas
Guy,_Arkansas
Hackett,_Arkansas
Hamburg,_Arkansas
Hampton,_Arkansas
Hardy,_Arkansas
Harrell,_Arkansas
Harrisburg,_Arkansas
Harrison,_Arkansas
Hartford,_Arkansas
Hartman,_Arkansas
Haskell,_Arkansas
Hatfield,_Arkansas
Havana,_Arkansas
Haynes,_Arkansas
Hazen,_Arkansas
Heber_Springs,_Arkansas
Hector,_Arkansas
Helena-West_Helena,_Arkansas
Hermitage,_Arkansas
Hickory_Ridge,_Arkansas
Higden,_Arkansas
Higginson,_Arkansas
Highfill,_Arkansas
Highland,_Arkansas
Hindsville,_Arkansas
Holland,_Arkansas
Holly_Grove,_Arkansas
Hope,_Arkansas
Horatio,_Arkansas
Horseshoe_Bend,_Arkansas
Horseshoe_Lake,_Arkansas
Hot_Springs,_Arkansas
Houston,_Arkansas
Hoxie,_Arkansas
Hughes,_Arkansas
Humnoke,_Arkansas
Humphrey,_Arkansas
Hunter,_Arkansas
Huntington,_Arkansas
Huntsville,_Arkansas
Huttig,_Arkansas
Imboden,_Arkansas
Jacksonport,_Arkans

Cupertino,_California
Cypress,_California
Daly_City,_California
Dana_Point,_California
Danville,_California
Davis,_California
Del_Mar,_California
Del_Rey_Oaks,_California
Delano,_California
Desert_Hot_Springs,_California
Diamond_Bar,_California
Dinuba,_California
Dixon,_California
Dorris,_California
Dos_Palos,_California
Downey,_California
Duarte,_California
Dublin,_California
Dunsmuir,_California
East_Palo_Alto,_California
Eastvale,_California
El_Cajon,_California
El_Centro,_California
El_Cerrito,_California
El_Monte,_California
El_Segundo,_California
Elk_Grove,_California
Emeryville,_California
Encinitas,_California
Escalon,_California
Escondido,_California
Etna,_California
Eureka,_California
Exeter,_California
Fairfax,_California
Fairfield,_California
Farmersville,_California
Ferndale,_California
Fillmore,_California
Firebaugh,_California
Folsom,_California
Fontana,_California
Fort_Bragg,_California
Fort_Jones,_California
Fortuna,_California
Foster_City,_California
Fountain_Valley,_

Willows,_California
Windsor,_California
Winters,_California
Woodlake,_California
Woodland,_California
Woodside,_California
Yorba_Linda,_California
Yountville,_California
Yreka,_California
Yuba_City,_California
Yucaipa,_California
Yucca_Valley,_California
2020_United_States_census
2010_United_States_census
Aguilar,_Colorado
Akron,_Colorado
Alamosa,_Colorado
Alma,_Colorado
Antonito,_Colorado
Arriba,_Colorado
Arvada,_Colorado
Aspen,_Colorado
Ault,_Colorado
Aurora,_Colorado
Avon,_Colorado
Basalt,_Colorado
Bayfield,_Colorado
Bennett,_Colorado
Berthoud,_Colorado
Bethune,_Colorado
Black_Hawk,_Colorado
Blanca,_Colorado
Blue_River,_Colorado
Bonanza,_Colorado
Boone,_Colorado
Boulder,_Colorado
Bow_Mar,_Colorado
Branson,_Colorado
Breckenridge,_Colorado
Brighton,_Colorado
Brookside,_Colorado
Broomfield,_Colorado
Brush,_Colorado
Buena_Vista,_Colorado
Burlington,_Colorado
Calhan,_Colorado
Campo,_Colorado
Cañon_City,_Colorado
Carbonate,_Colorado
Carbondale,_Colorado
Castle_Pines,_Colorado
Castle_Rock,

Century,_Florida
Chattahoochee,_Florida
Chiefland,_Florida
Chipley,_Florida
Cinco_Bayou,_Florida
Clearwater,_Florida
Clermont,_Florida
Clewiston,_Florida
Cloud_Lake,_Florida
Cocoa,_Florida
Cocoa_Beach,_Florida
Coconut_Creek,_Florida
Coleman,_Florida
Cooper_City,_Florida
Coral_Gables,_Florida
Coral_Springs,_Florida
Cottondale,_Florida
Crescent_City,_Florida
Crestview,_Florida
Cross_City,_Florida
Crystal_River,_Florida
Cutler_Bay,_Florida
Dade_City,_Florida
Dania_Beach,_Florida
Davenport,_Florida
Davie,_Florida
Daytona_Beach,_Florida
Daytona_Beach_Shores,_Florida
DeBary,_Florida
Deerfield_Beach,_Florida
DeFuniak_Springs,_Florida
DeLand,_Florida
Delray_Beach,_Florida
Deltona,_Florida
Destin,_Florida
Doral,_Florida
Dundee,_Florida
Dunedin,_Florida
Dunnellon,_Florida
Eagle_Lake,_Florida
Eatonville,_Florida
Ebro,_Florida
Edgewater,_Volusia_County,_Florida
Edgewood,_Florida
El_Portal,_Florida
Estero,_Florida
Esto,_Florida
Eustis,_Florida
Everglades_City,_Florida
Fanning_Springs,_Florida
Fells

Blairsville,_Georgia
Blakely,_Georgia
Bloomingdale,_Georgia
Blue_Ridge,_Georgia
Bluffton,_Georgia
Blythe,_Georgia
Bogart,_Georgia
Boston,_Georgia
Bostwick,_Georgia
Bowdon,_Georgia
Bowersville,_Georgia
Bowman,_Georgia
Braselton,_Georgia
Braswell,_Georgia
Bremen,_Georgia
Brinson,_Georgia
Bronwood,_Georgia
Brookhaven,_Georgia
Brooklet,_Georgia
Brooks,_Georgia
Broxton,_Georgia
Brunswick,_Georgia
Buchanan,_Georgia
Buckhead,_Morgan_County,_Georgia
Buena_Vista,_Georgia
Buford,_Georgia
Butler,_Georgia
Byromville,_Georgia
Byron,_Georgia
Cadwell,_Georgia
Cairo,_Georgia
Calhoun,_Georgia
Camak,_Georgia
Camilla,_Georgia
Canon,_Georgia
Canton,_Georgia
Carl,_Georgia
Carlton,_Georgia
Carnesville,_Georgia
Carrollton,_Georgia
Cartersville,_Georgia
Cave_Spring,_Georgia
Cecil,_Georgia
Cedartown,_Georgia
Centerville,_Georgia
Centralhatchee,_Georgia
Chamblee,_Georgia
Chatsworth,_Georgia
Chattahoochee_Hills,_Georgia
Chauncey,_Georgia
Chester,_Georgia
Chickamauga,_Georgia
Clarkesville,_Georgia
Clarkston,_Geor

Varnell,_Georgia
Vernonburg,_Georgia
Vidette,_Georgia
Vienna,_Georgia
Vidalia,_Georgia
Villa_Rica,_Georgia
Waco,_Georgia
Wadley,_Georgia
Waleska,_Georgia
Walnut_Grove,_Georgia
Walthourville,_Georgia
Warm_Springs,_Georgia
Warner_Robins,_Georgia
Warrenton,_Georgia
Warwick,_Georgia
Washington,_Georgia
Watkinsville,_Georgia
Waverly_Hall,_Georgia
Waycross,_Georgia
Waynesboro,_Georgia
Webster_County,_Georgia
West_Point,_Georgia
Whigham,_Georgia
White,_Georgia
White_Plains,_Georgia
Whitesburg,_Georgia
Willacoochee,_Georgia
Williamson,_Georgia
Winder,_Georgia
Winterville,_Georgia
Woodbine,_Georgia
Woodbury,_Georgia
Woodland,_Georgia
Woodstock,_Georgia
Woodville,_Georgia
Woolsey,_Georgia
Wrens,_Georgia
Wrightsville,_Georgia
Yatesville,_Georgia
Young_Harris,_Georgia
Zebulon,_Georgia
Honolulu,_Hawaii
East_Honolulu,_Hawaii
Pearl_City,_Hawaii
Hilo,_Hawaii
Waipahu,_Hawaii
Kailua,_Honolulu_County,_Hawaii
Kaneohe,_Hawaii
Kahului,_Hawaii
Mililani,_Hawaii
'Ewa_Gentry,_Hawaii
Kihei,_Hawaii
Kapolei,_Hawai

Beecher_City,_Illinois
Belgium,_Illinois
Belknap,_Illinois
Belle_Prairie_City,_Illinois
Belle_Rive,_Illinois
Belleville,_Illinois
Bellevue,_Illinois
Bellflower,_Illinois
Bellmont,_Illinois
Bellwood,_Illinois
Belvidere,_Illinois
Bement,_Illinois
Benld,_Illinois
Bensenville,_Illinois
Benson,_Illinois
Bentley,_Illinois
Benton,_Illinois
Berkeley,_Illinois
Berlin,_Illinois
Berwyn,_Illinois
Bethalto,_Illinois
Bethany,_Illinois
Biggsville,_Illinois
Big_Rock,_Illinois
Bingham,_Illinois
Bishop_Hill,_Illinois
Bismarck,_Illinois
Blandinsville,_Illinois
Bloomingdale,_Illinois
Bloomington,_Illinois
Blue_Island,_Illinois
Blue_Mound,_Illinois
Bluffs,_Illinois
Bluford,_Illinois
Bolingbrook,_Illinois
Bondville,_Illinois
Bone_Gap,_Illinois
Bonfield,_Illinois
Bonnie,_Illinois
Bourbonnais,_Illinois
Bowen,_Illinois
Braceville,_Illinois
Bradford,_Illinois
Bradley,_Illinois
Braidwood,_Illinois
Breese,_Illinois
Bridgeport,_Illinois
Bridgeview,_Illinois
Brighton,_Illinois
Brimfield,_Illinois
Broadlands,_Illino

Hartford,_Illinois
Hartsburg,_Illinois
Harvard,_Illinois
Harvel,_Illinois
Harvey,_Illinois
Harwood_Heights,_Illinois
Havana,_Illinois
Hawthorn_Woods,_Illinois
Hazel_Crest,_Illinois
Hebron,_Illinois
Hecker,_Illinois
Henderson,_Illinois
Hennepin,_Illinois
Henning,_Illinois
Henry,_Illinois
Herrick,_Illinois
Herrin,_Illinois
Herscher,_Illinois
Hettick,_Illinois
Heyworth,_Illinois
Hickory_Hills,_Illinois
Hidalgo,_Illinois
Highland,_Illinois
Highland_Park,_Illinois
Highwood,_Illinois
Hillcrest,_Illinois
Hillsboro,_Illinois
Hillsdale,_Illinois
Hillside,_Illinois
Hillview,_Illinois
Hinckley,_Illinois
Hindsboro,_Illinois
Hinsdale,_Illinois
Hodgkins,_Illinois
Hoffman,_Illinois
Hoffman_Estates,_Illinois
Holiday_Hills,_Illinois
Hollowayville,_Illinois
Homer,_Illinois
Homer_Glen,_Illinois
Hometown,_Illinois
Homewood,_Illinois
Hoopeston,_Illinois
Hooppole,_Illinois
Hopedale,_Illinois
Hopewell,_Illinois
Hopkins_Park,_Illinois
Hoyleton,_Illinois
Hudson,_Illinois
Huey,_Illinois
Hull,_Illinois
Humboldt,

Pecatonica,_Illinois
Pekin,_Illinois
Peoria,_Illinois
Peoria_Heights,_Illinois
Peotone,_Illinois
Percy,_Illinois
Perry,_Illinois
Peru,_Illinois
Pesotum,_Illinois
Petersburg,_Illinois
Phillipstown,_Illinois
Philo,_Illinois
Phoenix,_Illinois
Pierron,_Illinois
Pinckneyville,_Illinois
Pingree_Grove,_Illinois
Piper_City,_Illinois
Pittsburg,_Illinois
Pittsfield,_Illinois
Plainfield,_Illinois
Plainville,_Illinois
Plano,_Illinois
Plattville,_Illinois
Pleasant_Hill,_Illinois
Pleasant_Plains,_Illinois
Plymouth,_Illinois
Pocahontas,_Illinois
Polo,_Illinois
Pontiac,_Illinois
Pontoon_Beach,_Illinois
Pontoosuc,_Illinois
Poplar_Grove,_Illinois
Port_Barrington,_Illinois
Port_Byron,_Illinois
Posen,_Illinois
Potomac,_Illinois
Prairie_City,_Illinois
Prairie_du_Rocher,_Illinois
Prairie_Grove,_Illinois
Princeton,_Illinois
Princeville,_Illinois
Prophetstown,_Illinois
Prospect_Heights,_Illinois
Pulaski,_Illinois
Quincy,_Illinois
Radom,_Illinois
Raleigh,_Illinois
Ramsey,_Illinois
Rankin,_Illinois
Ransom,_Illi

Schererville,_Indiana
Brownsburg,_Indiana
Hobart,_Indiana
East_Chicago,_Indiana
Marion,_Indiana
Franklin,_Indiana
Highland,_Lake_County,_Indiana
Munster,_Indiana
Greenfield,_Indiana
Clarksville,_Indiana
Avon,_Indiana
La_Porte,_Indiana
St._John,_Indiana
Seymour,_Indiana
Shelbyville,_Indiana
Logansport,_Indiana
New_Castle,_Indiana
Huntington,_Indiana
Vincennes,_Indiana
Griffith,_Indiana
Dyer,_Indiana
Crawfordsville,_Indiana
Lebanon,_Indiana
New_Haven,_Indiana
Frankfort,_Indiana
Jasper,_Indiana
Warsaw,_Indiana
Beech_Grove,_Indiana
Chesterton,_Indiana
Cedar_Lake,_Indiana
Speedway,_Indiana
Auburn,_Indiana
Bedford,_Indiana
Connersville,_Indiana
Washington,_Indiana
Greensburg,_Indiana
Lake_Station,_Indiana
Martinsville,_Indiana
Madison,_Indiana
Yorktown,_Indiana
Peru,_Indiana
Lowell,_Indiana
Danville,_Indiana
Wabash,_Indiana
Bluffton,_Indiana
Kendallville,_Indiana
Plymouth,_Indiana
Whitestown,_Indiana
Decatur,_Indiana
Columbia_City,_Indiana
Greencastle,_Indiana
Bargersville,_Indiana
Mooresvil

Richland_City,_Indiana
Ridgeville,_Indiana
Riley,_Indiana
River_Forest,_Indiana
Roachdale,_Indiana
Roann,_Indiana
Roanoke,_Indiana
Rocky_Ripple,_Indiana
Rome_City,_Indiana
Rosedale,_Indiana
Roseland,_Indiana
Rossville,_Indiana
Royal_Center,_Indiana
Russellville,_Indiana
Russiaville,_Indiana
St._Joe,_Indiana
St._Leon,_Indiana
St._Paul,_Indiana
Salamonia,_Indiana
Saltillo,_Indiana
Sandborn,_Indiana
Saratoga,_Indiana
Schneider,_Indiana
Seelyville,_Indiana
Selma,_Indiana
Shadeland,_Indiana
Shamrock_Lakes,_Indiana
Sharpsville,_Indiana
Shelburn,_Indiana
Shipshewana,_Indiana
Shirley,_Indiana
Shoals,_Indiana
Sidney,_Indiana
Silver_Lake,_Indiana
Somerville,_Indiana
South_Whitley,_Indiana
Spiceland,_Indiana
Spring_Grove,_Indiana
Spring_Hill,_Indiana
Spring_Lake,_Indiana
Springport,_Indiana
Spurgeon,_Indiana
State_Line_City,_Indiana
Staunton,_Indiana
Stilesville,_Indiana
Stinesville,_Indiana
Straughn,_Indiana
Sulphur_Springs,_Indiana
Summitville,_Indiana
Sunman,_Indiana
Swayzee,_Indiana
Sweetser,

Floyd,_Iowa
Fonda,_Iowa
Pocahontas_County,_Iowa
Fontanelle,_Iowa
Forest_City,_Iowa
Fort_Atkinson,_Iowa
Fort_Dodge,_Iowa
Fort_Madison,_Iowa
Fostoria,_Iowa
Franklin,_Iowa
Fraser,_Iowa
Fredericksburg,_Iowa
Frederika,_Iowa
Fredonia,_Iowa
Fremont,_Iowa
Fruitland,_Iowa
Galt,_Iowa
Galva,_Iowa
Garber,_Iowa
Garden_Grove,_Iowa
Garnavillo,_Iowa
Garner,_Iowa
Garrison,_Iowa
Garwin,_Iowa
Geneva,_Iowa
George,_Iowa
Gibson,_Iowa
Gilbert,_Iowa
Gilbertville,_Iowa
Gillett_Grove,_Iowa
Gilman,_Iowa
Gilmore_City,_Iowa
Gladbrook,_Iowa
Glenwood,_Iowa
Glidden,_Iowa
Goldfield,_Iowa
Goodell,_Iowa
Goose_Lake,_Iowa
Gowrie,_Iowa
Graettinger,_Iowa
Graf,_Iowa
Grafton,_Iowa
Grand_Junction,_Iowa
Grand_Mound,_Iowa
Grand_River,_Iowa
Grandview,_Iowa
Granger,_Iowa
Grant,_Iowa
Granville,_Iowa
Gravity,_Iowa
Gray,_Iowa
Greeley,_Iowa
Greene,_Iowa
Greenfield,_Iowa
Greenville,_Iowa
Grimes,_Iowa
Grinnell,_Iowa
Griswold,_Iowa
Grundy_Center,_Iowa
Gruver,_Iowa
Guernsey,_Iowa
Guthrie_Center,_Iowa
Guttenberg,_Iowa
Halbur,_Iowa
Hamburg,

Tama,_Iowa
Templeton,_Iowa
Tennant,_Iowa
Terril,_Iowa
Thayer,_Iowa
Thompson,_Iowa
Thor,_Iowa
Thornburg,_Iowa
Thornton,_Iowa
Thurman,_Iowa
Tiffin,_Iowa
Tingley,_Iowa
Tipton,_Iowa
Titonka,_Iowa
Toledo,_Iowa
Toronto,_Iowa
Traer,_Iowa
Treynor,_Iowa
Tripoli,_Iowa
Truesdale,_Iowa
Truro,_Iowa
Turin,_Iowa
Udell,_Iowa
Underwood,_Iowa
Union,_Iowa
Unionville,_Iowa
University_Heights,_Iowa
University_Park,_Iowa
Urbana,_Iowa
Urbandale,_Iowa
Ute,_Iowa
Vail,_Iowa
Valeria,_Iowa
Van_Horne,_Iowa
Van_Meter,_Iowa
Van_Wert,_Iowa
Varina,_Iowa
Ventura,_Iowa
Victor,_Iowa
Villisca,_Iowa
Vincent,_Iowa
Vining,_Iowa
Vinton,_Iowa
Volga,_Iowa
Wadena,_Iowa
Wahpeton,_Iowa
Walcott,_Iowa
Walford,_Iowa
Walker,_Iowa
Wall_Lake,_Iowa
Wallingford,_Iowa
Walnut,_Iowa
Wapello,_Iowa
Washington,_Iowa
Washta,_Iowa
Waterloo,_Iowa
Waterville,_Iowa
Waucoma,_Iowa
Waukee,_Iowa
Waukon,_Iowa
Waverly,_Iowa
Wayland,_Iowa
Webb,_Iowa
Webster,_Iowa
Webster_City,_Iowa
Weldon,_Iowa
Wellman,_Iowa
Wellsburg,_Iowa
Welton,_Iowa
Wesley,_Iowa
West_B

Muldraugh,_Kentucky
Munfordville,_Kentucky
Murray,_Kentucky
Murray_Hill,_Kentucky
Nebo,_Kentucky
New_Castle,_Kentucky
New_Haven,_Kentucky
Newport,_Kentucky
Nicholasville,_Kentucky
Norbourne_Estates,_Kentucky
North_Middletown,_Kentucky
Northfield,_Kentucky
Nortonville,_Kentucky
Norwood,_Kentucky
Oak_Grove,_Kentucky
Oakland,_Kentucky
Old_Brownsboro_Place,_Kentucky
Olive_Hill,_Kentucky
Orchard_Grass_Hills,_Kentucky
Owensboro,_Kentucky
Owenton,_Kentucky
Owingsville,_Kentucky
Paducah,_Kentucky
Paintsville,_Kentucky
Paris,_Kentucky
Park_City,_Kentucky
Park_Hills,_Kentucky
Parkway_Village,_Kentucky
Pembroke,_Kentucky
Perryville,_Kentucky
Pewee_Valley,_Kentucky
Pikeville,_Kentucky
Pineville,_Kentucky
Pioneer_Village,_Kentucky
Pippa_Passes,_Kentucky
Plantation,_Kentucky
Pleasureville,_Kentucky
Plum_Springs,_Kentucky
Poplar_Hills,_Kentucky
Powderly,_Kentucky
Prestonsburg,_Kentucky
Prestonville,_Kentucky
Princeton,_Kentucky
Prospect,_Kentucky
Providence,_Kentucky
Raceland,_Kentucky
Radcliff,_Kent

Robeline,_Louisiana
Rodessa,_Louisiana
Rosedale,_Louisiana
Roseland,_Louisiana
Rosepine,_Louisiana
Ruston,_Louisiana
St._Francisville,_Louisiana
St._Gabriel,_Louisiana
St._Joseph,_Louisiana
St._Martinville,_Louisiana
Saline,_Louisiana
Sarepta,_Louisiana
Scott,_Louisiana
Shongaloo,_Louisiana
Shreveport,_Louisiana
Sibley,_Louisiana
Sicily_Island,_Louisiana
Sikes,_Louisiana
Simmesport,_Louisiana
Simpson,_Louisiana
Simsboro,_Louisiana
Slaughter,_Louisiana
Slidell,_Louisiana
Sorrento,_Louisiana
South_Mansfield,_Louisiana
Spearsville,_Louisiana
Springfield,_Louisiana
Springhill,_Louisiana
Stanley,_Louisiana
Sterlington,_Louisiana
Stonewall,_Louisiana
Sulphur,_Louisiana
Sun,_Louisiana
Sunset,_Louisiana
Tallulah,_Louisiana
Tangipahoa,_Louisiana
Thibodaux,_Louisiana
Tickfaw,_Louisiana
Tullos,_Louisiana
Turkey_Creek,_Louisiana
Urania,_Louisiana
Varnado,_Louisiana
Vidalia,_Louisiana
Vienna,_Louisiana
Ville_Platte,_Louisiana
Vinton,_Louisiana
Vivian,_Louisiana
Walker,_Louisiana
Washington,_Louisia

Swanville,_Maine
Sweden,_Maine
Talmadge,_Maine
Temple,_Maine
The_Forks,_Maine
Thomaston,_Maine
Thorndike,_Maine
Topsfield,_Maine
Topsham,_Maine
Tremont,_Maine
Trenton,_Maine
Troy,_Maine
Turner,_Maine
Union,_Maine
Unity,_Maine
Upton,_Maine
Van_Buren,_Maine
Vanceboro,_Maine
Vassalboro,_Maine
Veazie,_Maine
Verona_Island,_Maine
Vienna,_Maine
Vinalhaven,_Maine
Wade,_Maine
Waite,_Maine
Waldo,_Maine
Waldoboro,_Maine
Wales,_Maine
Wallagrass,_Maine
Waltham,_Maine
Warren,_Maine
Washburn,_Maine
Washington,_Maine
Waterboro,_Maine
Waterville,_Maine
Waterford,_Maine
Wayne,_Maine
Webster_Plantation,_Maine
Weld,_Maine
Wellington,_Maine
Wells,_Maine
Wesley,_Maine
West_Bath,_Maine
Westbrook,_Maine
West_Forks,_Maine
West_Gardiner,_Maine
West_Paris,_Maine
Westfield,_Maine
Westmanland,_Maine
Weston,_Maine
Westport_Island,_Maine
Whitefield,_Maine
Whiting,_Maine
Whitneyville,_Maine
Willimantic,_Maine
Wilton,_Maine
Windham,_Maine
Windsor,_Maine
Winn,_Maine
Winslow,_Maine
Winter_Harbor,_Maine
Winterport,_Maine

Leverett,_Massachusetts
Lexington,_Massachusetts
Leyden,_Massachusetts
Lincoln,_Massachusetts
Littleton,_Massachusetts
Longmeadow,_Massachusetts
Lowell,_Massachusetts
Ludlow,_Massachusetts
Lunenburg,_Massachusetts
Lynn,_Massachusetts
Lynnfield,_Massachusetts
Malden,_Massachusetts
Manchester-by-the-Sea,_Massachusetts
Mansfield,_Massachusetts
Marblehead,_Massachusetts
Marion,_Massachusetts
Marlborough,_Massachusetts
Marshfield,_Massachusetts
Mashpee,_Massachusetts
Mattapoisett,_Massachusetts
Maynard,_Massachusetts
Medfield,_Massachusetts
Medford,_Massachusetts
Medway,_Massachusetts
Melrose,_Massachusetts
Mendon,_Massachusetts
Merrimac,_Massachusetts
Methuen,_Massachusetts
Middleborough,_Massachusetts
Middlefield,_Massachusetts
Middleton,_Massachusetts
Milford,_Massachusetts
Millbury,_Massachusetts
Millis,_Massachusetts
Millville,_Massachusetts
Milton,_Massachusetts
Monroe,_Massachusetts
Monson,_Massachusetts
Montague,_Massachusetts
Monterey,_Massachusetts
Montgomery,_Massachusetts
Mount_

Beaver_Creek_Township,_Michigan
Beaverton,_Michigan
Beaverton_Township,_Michigan
Bedford_Charter_Township,_Michigan
Bedford_Township,_Monroe_County,_Michigan
Belding,_Michigan
Belknap_Township,_Michigan
Bellaire,_Michigan
Belleville,_Michigan
Bellevue,_Michigan
Bellevue_Township,_Michigan
Belvidere_Township,_Michigan
Bengal_Township,_Michigan
Bennington_Township,_Michigan
Benona_Township,_Michigan
Bentley_Township,_Michigan
Benton_Charter_Township,_Michigan
Benton_Township,_Cheboygan_County,_Michigan
Benton_Township,_Eaton_County,_Michigan
Benton_Harbor,_Michigan
Benzonia,_Michigan
Benzonia_Township,_Michigan
Bergland_Township,_Michigan
Berkley,_Michigan
Berlin_Township,_Ionia_County,_Michigan
Berlin_Charter_Township,_Michigan
Berlin_Township,_St._Clair_County,_Michigan
Berrien_Township,_Michigan
Berrien_Springs,_Michigan
Bertrand_Township,_Michigan
Bessemer,_Michigan
Bessemer_Township,_Michigan
Bethany_Township,_Michigan
Bethel_Township,_Michigan
Beulah,_Michigan
Beverly_Hills,_Michig

Copper_City,_Michigan
Cornell_Township,_Michigan
Corunna,_Michigan
Corwith_Township,_Michigan
Cottrellville_Township,_Michigan
Courtland_Township,_Michigan
Covert_Township,_Michigan
Covington_Township,_Michigan
Crockery_Township,_Michigan
Cross_Village_Township,_Michigan
Croswell,_Michigan
Croton_Township,_Michigan
Crystal_Township,_Montcalm_County,_Michigan
Crystal_Township,_Oceana_County,_Michigan
Crystal_Falls,_Michigan
Crystal_Falls_Township,_Michigan
Crystal_Lake_Township,_Michigan
Cumming_Township,_Michigan
Curtis_Township,_Michigan
Custer_Township,_Antrim_County,_Michigan
Custer,_Michigan
Custer_Township,_Mason_County,_Michigan
Custer_Township,_Sanilac_County,_Michigan
Dafter_Township,_Michigan
Daggett,_Michigan
Daggett_Township,_Michigan
Dallas_Township,_Michigan
Dalton_Township,_Michigan
Danby_Township,_Michigan
Dansville,_Michigan
Davison,_Michigan
Davison_Township,_Michigan
Day_Township,_Michigan
Dayton_Township,_Newaygo_County,_Michigan
Dayton_Township,_Tuscola_County,_Mich

Grant_Township,_Huron_County,_Michigan
Grant_Township,_Iosco_County,_Michigan
Grant_Township,_Keweenaw_County,_Michigan
Grant_Township,_Mason_County,_Michigan
Grant_Township,_Mecosta_County,_Michigan
Grant,_Michigan
Grant_Township,_Newaygo_County,_Michigan
Grant_Township,_Oceana_County,_Michigan
Grant_Township,_St._Clair_County,_Michigan
Grass_Lake,_Michigan
Grass_Lake_Charter_Township,_Michigan
Grattan_Township,_Michigan
Grayling,_Michigan
Grayling_Charter_Township,_Michigan
Green_Township,_Michigan
Green_Charter_Township,_Michigan
Greenbush_Township,_Alcona_County,_Michigan
Greenbush_Township,_Clinton_County,_Michigan
Greendale_Township,_Michigan
Green_Lake_Township,_Michigan
Greenland_Township,_Michigan
Greenleaf_Township,_Michigan
Green_Oak_Township,_Michigan
Greenville,_Michigan
Greenwood_Township,_Clare_County,_Michigan
Greenwood_Township,_Oceana_County,_Michigan
Greenwood_Township,_Oscoda_County,_Michigan
Greenwood_Township,_St._Clair_County,_Michigan
Greenwood_Township,_Wexford

Little_Traverse_Township,_Michigan
Livingston_Township,_Michigan
Livonia,_Michigan
Locke_Township,_Michigan
Lockport_Township,_Michigan
Lodi_Township,_Michigan
Logan_Township,_Mason_County,_Michigan
Logan_Township,_Ogemaw_County,_Michigan
London_Township,_Michigan
Long_Lake_Township,_Michigan
Long_Rapids_Township,_Michigan
Loud_Township,_Michigan
Lovells_Township,_Michigan
Lowell,_Michigan
Lowell_Charter_Township,_Michigan
Ludington,_Michigan
Luna_Pier,_Michigan
Luther,_Michigan
Lyndon_Township,_Michigan
Lynn_Township,_Michigan
Lyon_Township,_Oakland_County,_Michigan
Lyon_Township,_Roscommon_County,_Michigan
Lyons,_Michigan
Lyons_Township,_Michigan
McBain,_Michigan
McBride,_Michigan
Mackinac_Island,_Michigan
Mackinaw_Township,_Michigan
Mackinaw_City,_Michigan
McKinley_Township,_Emmet_County,_Michigan
McKinley_Township,_Huron_County,_Michigan
McMillan_Township,_Luce_County,_Michigan
McMillan_Township,_Ontonagon_County,_Michigan
Macomb_Township,_Michigan
Macon_Township,_Michigan
Madison_

Oxford,_Michigan
Oxford_Charter_Township,_Michigan
Palmyra_Township,_Michigan
Paradise_Township,_Michigan
Parchment,_Michigan
Paris_Township,_Michigan
Park_Township,_Ottawa_County,_Michigan
Park_Township,_St._Joseph_County,_Michigan
Parma,_Michigan
Parma_Township,_Michigan
Pavilion_Township,_Michigan
Paw_Paw,_Michigan
Paw_Paw_Township,_Michigan
Peacock_Township,_Michigan
Peaine_Township,_Michigan
Peck,_Michigan
Pellston,_Michigan
Peninsula_Township,_Michigan
Penn_Township,_Michigan
Pennfield_Charter_Township,_Michigan
Pentland_Township,_Michigan
Pentwater,_Michigan
Pentwater_Township,_Michigan
Pere_Marquette_Charter_Township,_Michigan
Perrinton,_Michigan
Perry,_Michigan
Perry_Township,_Michigan
Petersburg,_Michigan
Petoskey,_Michigan
Pewamo,_Michigan
Pickford_Township,_Michigan
Pierson,_Michigan
Pierson_Township,_Michigan
Pigeon,_Michigan
Pinckney,_Michigan
Pinconning,_Michigan
Pinconning_Township,_Michigan
Pine_Township,_Michigan
Pine_Grove_Township,_Michigan
Pine_River_Township,_Mich

Sterling,_Michigan
Sterling_Heights,_Michigan
Stevensville,_Michigan
Stockbridge,_Michigan
Stockbridge_Township,_Michigan
Stronach_Township,_Michigan
Sturgis,_Michigan
Sturgis_Township,_Michigan
Sugar_Island_Township,_Michigan
Sullivan_Township,_Michigan
Summerfield_Township,_Clare_County,_Michigan
Summerfield_Township,_Monroe_County,_Michigan
Summit_Township,_Jackson_County,_Michigan
Summit_Township,_Mason_County,_Michigan
Sumner_Township,_Michigan
Sumpter_Township,_Michigan
Sunfield,_Michigan
Sunfield_Township,_Michigan
Superior_Township,_Chippewa_County,_Michigan
Superior_Township,_Washtenaw_County,_Michigan
Surrey_Township,_Michigan
Suttons_Bay,_Michigan
Suttons_Bay_Township,_Michigan
Swan_Creek_Township,_Michigan
Swartz_Creek,_Michigan
Sweetwater_Township,_Michigan
Sylvan_Township,_Osceola_County,_Michigan
Sylvan_Township,_Washtenaw_County,_Michigan
Sylvan_Lake,_Michigan
Tallmadge_Township,_Michigan
Tawas_Township,_Michigan
Tawas_City,_Michigan
Taylor,_Michigan
Taymouth_Township,_

Fairmont,_Minnesota
Hermantown,_Minnesota
St._Anthony,_Minnesota
Detroit_Lakes,_Minnesota
Arden_Hills,_Minnesota
Dayton,_Minnesota
Waseca,_Minnesota
Oak_Grove,_Minnesota
Little_Falls,_Minnesota
East_Grand_Forks,_Minnesota
Mound,_Minnesota
Baxter,_Minnesota
Thief_River_Falls,_Minnesota
Minnetrista,_Minnesota
St._Francis,_Minnesota
Waite_Park,_Minnesota
Virginia,_Minnesota
New_Prague,_Minnesota
Orono,_Minnesota
Albertville,_Minnesota
Wyoming,_Minnesota
Mahtomedi,_Minnesota
Shorewood,_Minnesota
Belle_Plaine,_Minnesota
Corcoran,_Minnesota
Crookston,_Minnesota
Isanti,_Minnesota
St._Joseph,_Minnesota
Spring_Lake_Park,_Minnesota
Kasson,_Minnesota
Delano,_Minnesota
Medina,_Minnesota
Stewartville,_Minnesota
Jordan,_Minnesota
Byron,_Minnesota
Litchfield,_Minnesota
Zimmerman,_Minnesota
Carver,_Minnesota
Glencoe,_Minnesota
Chisago_City,_Minnesota
International_Falls,_Minnesota
Credit_River,_Minnesota
St._Paul_Park,_Minnesota
La_Crescent,_Minnesota
Princeton,_Minnesota
Lake_City,_Minnesota
Montevid

Brewster,_Minnesota
Sacred_Heart,_Minnesota
Brandon,_Minnesota
Rothsay,_Minnesota
Jenkins,_Minnesota
Carlos,_Minnesota
Kiester,_Minnesota
Ellsworth,_Minnesota
Pennock,_Minnesota
Upsala,_Minnesota
Lafayette,_Minnesota
Ulen,_Minnesota
Ashby,_Minnesota
Stewart,_Minnesota
Bethel,_Minnesota
Clearbrook,_Minnesota
Altura,_Minnesota
Randolph,_Minnesota
New_Germany,_Minnesota
Sturgeon_Lake,_Minnesota
Danube,_Minnesota
Fifty_Lakes,_Minnesota
Wrenshall,_Minnesota
Miltona,_Minnesota
Wykoff,_Minnesota
Vermillion,_Minnesota
Lynd,_Minnesota
Badger,_Minnesota
Kellogg,_Minnesota
Tower,_Minnesota
Akeley,_Minnesota
Milan,_Minnesota
Fisher,_Minnesota
New_Auburn,_Minnesota
Fountain,_Minnesota
Oklee,_Minnesota
Chokio,_Minnesota
Bigfork,_Minnesota
Waubun,_Minnesota
Morton,_Minnesota
Remer,_Minnesota
Willow_River,_Minnesota
Rose_Creek,_Minnesota
Ogilvie,_Minnesota
Erskine,_Minnesota
Nevis,_Minnesota
Herman,_Minnesota
Hanska,_Minnesota
McGregor,_Minnesota
Woodland,_Minnesota
Alvarado,_Minnesota
Clinton,_Minnes

Coldwater,_Mississippi
Collins,_Mississippi
Columbia,_Mississippi
Columbus,_Mississippi
Como,_Mississippi
Corinth,_Mississippi
Courtland,_Mississippi
Crawford,_Mississippi
Crenshaw,_Mississippi
Crosby,_Mississippi
Crowder,_Mississippi
Cruger,_Mississippi
Crystal_Springs,_Mississippi
Decatur,_Mississippi
De_Kalb,_Mississippi
Derma,_Mississippi
D'Iberville,_Mississippi
D'Lo,_Mississippi
Diamondhead,_Mississippi
Doddsville,_Mississippi
Drew,_Mississippi
Duck_Hill,_Mississippi
Dumas,_Mississippi
Duncan,_Mississippi
Durant,_Mississippi
Ecru,_Mississippi
Eden,_Mississippi
Edwards,_Mississippi
Ellisville,_Mississippi
Enterprise,_Clarke_County,_Mississippi
Ethel,_Mississippi
Eupora,_Mississippi
Falcon,_Mississippi
Falkner,_Mississippi
Farmington,_Mississippi
Fayette,_Mississippi
Flora,_Mississippi
Florence,_Mississippi
Flowood,_Mississippi
Forest,_Mississippi
French_Camp,_Mississippi
Friars_Point,_Mississippi
Fulton,_Mississippi
Gattman,_Mississippi
Gautier,_Mississippi
Georgetown,_Mississippi

Canalou,_Missouri
Canton,_Missouri
Cape_Girardeau,_Missouri
Cardwell,_Missouri
Carl_Junction,_Missouri
Carrollton,_Missouri
Carterville,_Missouri
Carthage,_Missouri
Caruthersville,_Missouri
Carytown,_Missouri
Cassville,_Missouri
Catron,_Missouri
Cave,_Missouri
Cedar_Hill_Lakes,_Missouri
Center,_Missouri
Centertown,_Missouri
Centerview,_Missouri
Centerville,_Missouri
Centralia,_Missouri
Chaffee,_Missouri
Chain_of_Rocks,_Missouri
Chain-O-Lakes,_Missouri
Chamois,_Missouri
Champ,_Missouri
Charlack,_Missouri
Charleston,_Missouri
Chesterfield,_Missouri
Chilhowee,_Missouri
Chillicothe,_Missouri
Chula,_Missouri
Clarence,_Missouri
Clark,_Missouri
Clarksburg,_Missouri
Clarksdale,_Missouri
Clarkson_Valley,_Missouri
Clarksville,_Missouri
Clarkton,_Missouri
Claycomo,_Missouri
Clayton,_Missouri
Clearmont,_Missouri
Cleveland,_Missouri
Clever,_Missouri
Cliff_Village,_Missouri
Clifton_Hill,_Missouri
Climax_Springs,_Missouri
Clinton,_Missouri
Clyde,_Missouri
Cobalt,_Missouri
Coffey,_Missouri
Cole_Camp,_

McBaine,_Missouri
McCord_Bend,_Missouri
McFall,_Missouri
McKittrick,_Missouri
Meadville,_Missouri
Memphis,_Missouri
Mendon,_Missouri
Mercer,_Missouri
Merriam_Woods,_Missouri
Merwin,_Missouri
Meta,_Missouri
Mexico,_Missouri
Miami,_Missouri
Middletown,_Missouri
Milan,_Missouri
Milford,_Missouri
Mill_Spring,_Missouri
Millard,_Missouri
Miller,_Missouri
Milo,_Missouri
Mindenmines,_Missouri
Miner,_Missouri
Mineral_Point,_Missouri
Miramiguoa_Park,_Missouri
Missouri_City,_Missouri
Moberly,_Missouri
Mokane,_Missouri
Moline_Acres,_Missouri
Monett,_Missouri
Monroe_City,_Missouri
Montgomery_City,_Missouri
Monticello,_Missouri
Montrose,_Missouri
Mooresville,_Missouri
Morehouse,_Missouri
Morley,_Missouri
Morrison,_Missouri
Morrisville,_Missouri
Mosby,_Missouri
Moscow_Mills,_Missouri
Mound_City,_Missouri
Moundville,_Missouri
Mount_Leonard,_Missouri
Mount_Moriah,_Missouri
Mount_Vernon,_Missouri
Mountain_Grove,_Missouri
Mountain_View,_Missouri
Napoleon,_Missouri
Naylor,_Missouri
Neck_City,_Missouri
Nee

Broadview,_Montana
Browning,_Montana
Butte,_Montana
Cascade,_Montana
Chester,_Montana
Chinook,_Montana
Choteau,_Montana
Circle,_Montana
Clyde_Park,_Montana
Colstrip,_Montana
Columbia_Falls,_Montana
Columbus,_Montana
Conrad,_Montana
Culbertson,_Montana
Cut_Bank,_Montana
Darby,_Montana
Deer_Lodge,_Montana
Denton,_Montana
Dillon,_Montana
Dodson,_Montana
Drummond,_Montana
Dutton,_Montana
East_Helena,_Montana
Ekalaka,_Montana
Ennis,_Montana
Eureka,_Montana
Fairfield,_Montana
Fairview,_Montana
Flaxville,_Montana
Forsyth,_Montana
Fort_Benton,_Montana
Fort_Peck,_Montana
Froid,_Montana
Fromberg,_Montana
Geraldine,_Montana
Glasgow,_Montana
Glendive,_Montana
Grass_Range,_Montana
Great_Falls,_Montana
Hamilton,_Montana
Hardin,_Montana
Harlem,_Montana
Harlowton,_Montana
Havre,_Montana
Helena,_Montana
Hingham,_Montana
Hobson,_Montana
Hot_Springs,_Montana
Hysham,_Montana
Ismay,_Montana
Joliet,_Montana
Jordan,_Montana
Judith_Gap,_Montana
Kalispell,_Montana
Kevin,_Montana
Laurel,_Montana
Lavina,_Montana

Trenton,_New_Jersey
Clifton,_New_Jersey
Cherry_Hill,_New_Jersey
Brick_Township,_New_Jersey
Camden,_New_Jersey
Bayonne,_New_Jersey
Passaic,_New_Jersey
East_Orange,_New_Jersey
Union_City,_New_Jersey
Franklin_Township,_Somerset_County,_New_Jersey
Middletown_Township,_New_Jersey
Old_Bridge_Township,_New_Jersey
Gloucester_Township,_New_Jersey
North_Bergen,_New_Jersey
Irvington,_New_Jersey
Piscataway,_New_Jersey
Vineland,_New_Jersey
Hoboken,_New_Jersey
Union_Township,_Union_County,_New_Jersey
Jackson_Township,_New_Jersey
Parsippany–Troy_Hills,_New_Jersey
Perth_Amboy,_New_Jersey
New_Brunswick,_New_Jersey
Wayne,_New_Jersey
Plainfield,_New_Jersey
Howell_Township,_New_Jersey
Bloomfield,_New_Jersey
West_New_York,_New_Jersey
East_Brunswick,_New_Jersey
West_Orange,_New_Jersey
Washington_Township,_Gloucester_County,_New_Jersey
Monroe_Township,_Middlesex_County,_New_Jersey
Egg_Harbor_Township,_New_Jersey
South_Brunswick,_New_Jersey
Evesham_Township,_New_Jersey
Hackensack,_New_Jersey
Bridgewater_Towns

Allendale,_New_Jersey
Tabernacle_Township,_New_Jersey
North_Caldwell,_New_Jersey
Rockaway,_New_Jersey
Union_Township,_Hunterdon_County,_New_Jersey
Washington_Township,_Warren_County,_New_Jersey
Shamong_Township,_New_Jersey
Watchung,_New_Jersey
Carlstadt,_New_Jersey
Prospect_Park,_New_Jersey
New_Hanover_Township,_New_Jersey
Roseland,_New_Jersey
Dennis_Township,_New_Jersey
Fair_Haven,_New_Jersey
Maurice_River_Township,_New_Jersey
Paulsboro,_New_Jersey
Lebanon_Township,_New_Jersey
Eastampton_Township,_New_Jersey
Morris_Plains,_New_Jersey
Oceanport,_New_Jersey
Little_Silver,_New_Jersey
Woodcliff_Lake,_New_Jersey
Hainesport_Township,_New_Jersey
Mendham_Township,_New_Jersey
Logan_Township,_New_Jersey
Andover_Township,_New_Jersey
Manasquan,_New_Jersey
Mount_Arlington,_New_Jersey
Belmar,_New_Jersey
Hightstown,_New_Jersey
Old_Tappan,_New_Jersey
Tewksbury_Township,_New_Jersey
Berlin_Township,_New_Jersey
Mullica_Township,_New_Jersey
Rochelle_Park,_New_Jersey
Jamesburg,_New_Jersey
Union_Beach,_New

San_Jon,_New_Mexico
San_Ysidro,_New_Mexico
Santa_Clara,_New_Mexico
Santa_Fe,_New_Mexico
Santa_Rosa,_New_Mexico
Silver_City,_New_Mexico
Socorro,_New_Mexico
Springer,_New_Mexico
Sunland_Park,_New_Mexico
Taos,_New_Mexico
Taos_Ski_Valley,_New_Mexico
Tatum,_New_Mexico
Texico,_New_Mexico
Tijeras,_New_Mexico
Truth_or_Consequences,_New_Mexico
Tucumcari,_New_Mexico
Tularosa,_New_Mexico
Vaughn,_New_Mexico
Virden,_New_Mexico
Wagon_Mound,_New_Mexico
Willard,_New_Mexico
Williamsburg,_New_Mexico
Population
Square_mile
Adams_(village),_New_York
Addison_(village),_New_York
Afton_(village),_New_York
Airmont,_New_York
Akron,_New_York
Albany,_New_York
Albion_(village),_New_York
Alden_(village),_New_York
Alexander_(village),_New_York
Alexandria_Bay,_New_York
Alfred_(village),_New_York
Allegany_(village),_New_York
Almond_(village),_New_York
Altamont,_New_York
Ames,_New_York
Amityville,_New_York
Amsterdam_(city),_New_York
Andover_(village),_New_York
Angelica_(village),_New_York
Angola,_New_York
Antwerp_(vil

McGraw,_New_York
Mechanicville,_New_York
Medina,_New_York
Menands,_New_York
Meridian,_New_York
Mexico_(village),_New_York
Middleburgh_(village),_New_York
Middleport,_New_York
Middletown,_Orange_County,_New_York
Middleville,_New_York
Milford_(village),_New_York
Mill_Neck,_New_York
Millbrook,_New_York
Millerton,_New_York
Millport,_New_York
Mineola,_New_York
Minoa,_New_York
Mohawk,_Herkimer_County,_New_York
Monroe_(village),_New_York
Montebello,_New_York
Montgomery_(village),_New_York
Monticello,_New_York
Montour_Falls,_New_York
Moravia_(village),_New_York
Morris_(village),_New_York
Morrisville,_New_York
Mount_Kisco,_New_York
Mount_Morris_(village),_New_York
Mount_Vernon,_New_York
Munnsville,_New_York
Munsey_Park,_New_York
Muttontown,_New_York
Naples_(village),_New_York
Nassau_(village),_New_York
Nelliston,_New_York
Nelsonville,_New_York
New_Berlin_(village),_New_York
New_Hartford_(village),_New_York
New_Hempstead,_New_York
New_Hyde_Park,_New_York
New_Paltz_(village),_New_York
New_Rochell

Smithtown_(CDP),_New_York
Westport,_New_York
Woodhull,_New_York
Charlotte,_North_Carolina
Raleigh,_North_Carolina
Greensboro,_North_Carolina
Durham,_North_Carolina
Winston-Salem,_North_Carolina
Fayetteville,_North_Carolina
Cary,_North_Carolina
Wilmington,_North_Carolina
High_Point,_North_Carolina
Concord,_North_Carolina
Asheville,_North_Carolina
Greenville,_North_Carolina
Gastonia,_North_Carolina
Jacksonville,_North_Carolina
Apex,_North_Carolina
Huntersville,_North_Carolina
Chapel_Hill,_North_Carolina
Burlington,_North_Carolina
Kannapolis,_North_Carolina
Rocky_Mount,_North_Carolina
Mooresville,_North_Carolina
Wake_Forest,_North_Carolina
Wilson,_North_Carolina
Hickory,_North_Carolina
Holly_Springs,_North_Carolina
Indian_Trail,_North_Carolina
Fuquay-Varina,_North_Carolina
Salisbury,_North_Carolina
Monroe,_North_Carolina
Goldsboro,_North_Carolina
Garner,_North_Carolina
Cornelius,_North_Carolina
New_Bern,_North_Carolina
Morrisville,_North_Carolina
Sanford,_North_Carolina
Matthews,_North_Ca

Clifford,_North_Dakota
Egeland,_North_Dakota
Fortuna,_North_Dakota
Alsen,_North_Dakota
Monango,_North_Dakota
Nekoma,_North_Dakota
Springbrook,_North_Dakota
Hampden,_North_Dakota
Brinsmade,_North_Dakota
Fairdale,_North_Dakota
Luverne,_North_Dakota
Leith,_North_Dakota
Kramer,_North_Dakota
Amidon,_North_Dakota
Leal,_North_Dakota
Gardena,_North_Dakota
Antler,_North_Dakota
Cathay,_North_Dakota
Elliott,_North_Dakota
Gascoyne,_North_Dakota
Knox,_North_Dakota
Mylo,_North_Dakota
Sibley,_North_Dakota
Venturia,_North_Dakota
Ambrose,_North_Dakota
Braddock,_North_Dakota
Ludden,_North_Dakota
Lawton,_North_Dakota
Balfour,_North_Dakota
Bucyrus,_North_Dakota
Hansboro,_North_Dakota
Haynes,_North_Dakota
Sarles,_North_Dakota
York,_North_Dakota
Conway,_North_Dakota
Calvin,_North_Dakota
Ayr,_North_Dakota
Bergen,_North_Dakota
Hamberg,_North_Dakota
Pillsbury,_North_Dakota
Churchs_Ferry,_North_Dakota
Overly,_North_Dakota
Grano,_North_Dakota
Loma,_North_Dakota
Wales,_North_Dakota
Loraine,_North_Dakota
Hannah,_N

Fayetteville,_Ohio
Felicity,_Ohio
Fletcher,_Ohio
Florida,_Ohio
Flushing,_Ohio
Forest,_Ohio
Fort_Jennings,_Ohio
Fort_Loramie,_Ohio
Fort_Recovery,_Ohio
Frankfort,_Ohio
Frazeysburg,_Ohio
Fredericksburg,_Ohio
Fredericktown,_Ohio
Freeport,_Ohio
Fulton,_Ohio
Fultonham,_Ohio
Galena,_Ohio
Gallipolis,_Ohio
Gambier,_Ohio
Gann,_Ohio
Garrettsville,_Ohio
Gates_Mills,_Ohio
Geneva-on-the-Lake,_Ohio
Genoa,_Ohio
Georgetown,_Ohio
Gettysburg,_Ohio
Gibsonburg,_Ohio
Gilboa,_Ohio
Glandorf,_Ohio
Glendale,_Ohio
Glenford,_Ohio
Glenmont,_Ohio
Glenwillow,_Ohio
Gloria_Glens_Park,_Ohio
Glouster,_Ohio
Gnadenhutten,_Ohio
Golf_Manor,_Ohio
Gordon,_Ohio
Grafton,_Ohio
Grand_Rapids,_Ohio
Grand_River,_Ohio
Granville,_Ohio
Gratiot,_Ohio
Gratis,_Ohio
Graysville,_Ohio
Green_Camp,_Ohio
Green_Springs,_Ohio
Greenfield,_Ohio
Greenhills,_Ohio
Greenwich,_Ohio
Grover_Hill,_Ohio
Hamden,_Ohio
Hamersville,_Ohio
Hamler,_Ohio
Hanging_Rock,_Ohio
Hanover,_Ohio
Hanoverton,_Ohio
Harbor_View,_Ohio
Harpster,_Ohio
Harrisburg,_Ohio
Harrisville,

Oklahoma_City
Tulsa,_Oklahoma
Norman,_Oklahoma
Broken_Arrow,_Oklahoma
Edmond,_Oklahoma
Lawton,_Oklahoma
Moore,_Oklahoma
Midwest_City,_Oklahoma
Enid,_Oklahoma
Stillwater,_Oklahoma
Owasso,_Oklahoma
Bartlesville,_Oklahoma
Muskogee,_Oklahoma
Shawnee,_Oklahoma
Bixby,_Oklahoma
Jenks,_Oklahoma
Ardmore,_Oklahoma
Ponca_City,_Oklahoma
Yukon,_Oklahoma
Duncan,_Oklahoma
Sapulpa,_Oklahoma
Del_City,_Oklahoma
Bethany,_Oklahoma
Mustang,_Oklahoma
Sand_Springs,_Oklahoma
Claremore,_Oklahoma
Altus,_Oklahoma
Durant,_Oklahoma
McAlester,_Oklahoma
El_Reno,_Oklahoma
Ada,_Oklahoma
Tahlequah,_Oklahoma
Chickasha,_Oklahoma
Glenpool,_Oklahoma
Miami,_Oklahoma
Guymon,_Oklahoma
Choctaw,_Oklahoma
Woodward,_Oklahoma
Weatherford,_Oklahoma
Elk_City,_Oklahoma
Okmulgee,_Oklahoma
Newcastle,_Oklahoma
Guthrie,_Oklahoma
Warr_Acres,_Oklahoma
Coweta,_Oklahoma
The_Village,_Oklahoma
Pryor_Creek,_Oklahoma
Blanchard,_Oklahoma
Poteau,_Oklahoma
Clinton,_Oklahoma
Sallisaw,_Oklahoma
Skiatook,_Oklahoma
Cushing,_Oklahoma
Collinsville,_Oklah

Swatara_Township,_Dauphin_County,_Pennsylvania
Warrington_Township,_Bucks_County,_Pennsylvania
Marple_Township,_Delaware_County,_Pennsylvania
New_Castle,_Pennsylvania
West_Goshen_Township,_Chester_County,_Pennsylvania
Unity_Township,_Westmoreland_County,_Pennsylvania
Pottstown,_Pennsylvania
Peters_Township,_Washington_County,_Pennsylvania
Upper_Providence_Township,_Montgomery_County,_Pennsylvania
Upper_Macungie_Township,_Lehigh_County,_Pennsylvania
Dover_Township,_York_County,_Pennsylvania
East_Pennsboro_Township,_Cumberland_County,_Pennsylvania
Palmer_Township,_Northampton_County,_Pennsylvania
Johnstown,_Pennsylvania
Coolbaugh_Township,_Monroe_County,_Pennsylvania
Chambersburg,_Pennsylvania
Buckingham_Township,_Bucks_County,_Pennsylvania
West_Mifflin,_Pennsylvania
Murrysville,_Pennsylvania
Manor_Township,_Lancaster_County,_Pennsylvania
Penn_Township,_Westmoreland_County,_Pennsylvania
Muhlenberg_Township,_Berks_County,_Pennsylvania
Baldwin,_Pennsylvania
McKeesport,_Pennsylvania
South_W

Ephrata_Township,_Lancaster_County,_Pennsylvania
Plains_Township,_Luzerne_County,_Pennsylvania
Northampton,_Pennsylvania
Milford_Township,_Bucks_County,_Pennsylvania
East_Stroudsburg,_Pennsylvania
Sunbury,_Pennsylvania
Lock_Haven,_Pennsylvania
Penn_Forest_Township,_Carbon_County,_Pennsylvania
Bristol,_Pennsylvania
Brentwood,_Pennsylvania
Hazle_Township,_Luzerne_County,_Pennsylvania
South_Lebanon_Township,_Lebanon_County,_Pennsylvania
West_Hanover_Township,_Dauphin_County,_Pennsylvania
Jeannette,_Pennsylvania
Warren,_Pennsylvania
College_Township,_Centre_County,_Pennsylvania
South_Strabane_Township,_Washington_County,_Pennsylvania
Neshannock_Township,_Lawrence_County,_Pennsylvania
Lititz,_Pennsylvania
Butler_Township,_Luzerne_County,_Pennsylvania
Aliquippa,_Pennsylvania
Darby_Township,_Delaware_County,_Pennsylvania
Maidencreek_Township,_Berks_County,_Pennsylvania
Moore_Township,_Northampton_County,_Pennsylvania
Perkiomen_Township,_Montgomery_County,_Pennsylvania
South_Abington_Township,

Dickson_City,_Pennsylvania
Carroll_Township,_York_County,_Pennsylvania
Cambria_Township,_Cambria_County,_Pennsylvania
Hellam_Township,_York_County,_Pennsylvania
New_Brighton,_Pennsylvania
Luzerne_Township,_Fayette_County,_Pennsylvania
Steelton,_Pennsylvania
Crafton,_Pennsylvania
Sewickley_Township,_Westmoreland_County,_Pennsylvania
St._Thomas_Township,_Pennsylvania
Plymouth,_Pennsylvania
Williams_Township,_Northampton_County,_Pennsylvania
Punxsutawney,_Pennsylvania
Greenville,_Pennsylvania
Monroe_Township,_Cumberland_County,_Pennsylvania
Norwood,_Pennsylvania
Adams_Township,_Cambria_County,_Pennsylvania
Ross_Township,_Monroe_County,_Pennsylvania
Hellertown,_Pennsylvania
Mount_Carmel,_Pennsylvania
East_Hanover_Township,_Dauphin_County,_Pennsylvania
Hollidaysburg,_Pennsylvania
Reading_Township,_Adams_County,_Pennsylvania
New_London_Township,_Chester_County,_Pennsylvania
Lewisburg,_Pennsylvania
Union_Township,_Washington_County,_Pennsylvania
Monaca,_Pennsylvania
Moosic,_Pennsylvania
South

Sellersville,_Pennsylvania
Franklin_Township,_Carbon_County,_Pennsylvania
Manor_Township,_Armstrong_County,_Pennsylvania
Sugarloaf_Township,_Luzerne_County,_Pennsylvania
Birmingham_Township,_Chester_County,_Pennsylvania
Strasburg_Township,_Lancaster_County,_Pennsylvania
Mahoning_Township,_Montour_County,_Pennsylvania
West_Reading,_Pennsylvania
Forty_Fort,_Pennsylvania
Menallen_Township,_Fayette_County,_Pennsylvania
Salem_Township,_Wayne_County,_Pennsylvania
Cornwall,_Pennsylvania
Barrett_Township,_Pennsylvania
Greenfield_Township,_Blair_County,_Pennsylvania
Upper_Paxton_Township,_Dauphin_County,_Pennsylvania
Little_Britain_Township,_Lancaster_County,_Pennsylvania
Aldan,_Pennsylvania
Connoquenessing_Township,_Butler_County,_Pennsylvania
Pine_Grove_Township,_Schuylkill_County,_Pennsylvania
Ruscombmanor_Township,_Berks_County,_Pennsylvania
Heidelberg_Township,_Lebanon_County,_Pennsylvania
Bethel_Township,_Berks_County,_Pennsylvania
Waynesburg,_Pennsylvania
Mahanoy_City,_Pennsylvania
Baden

Fulton_Township,_Lancaster_County,_Pennsylvania
Fawn_Township,_York_County,_Pennsylvania
Edgewood,_Allegheny_County,_Pennsylvania
Macungie,_Pennsylvania
Myerstown,_Pennsylvania
Lower_Mount_Bethel_Township,_Northampton_County,_Pennsylvania
Thornbury_Township,_Chester_County,_Pennsylvania
Girard,_Pennsylvania
Heidelberg_Township,_York_County,_Pennsylvania
Orwigsburg,_Pennsylvania
Wormleysburg,_Pennsylvania
Wrightstown_Township,_Bucks_County,_Pennsylvania
Wyoming,_Pennsylvania
Lower_Chanceford_Township,_York_County,_Pennsylvania
Raccoon_Township,_Beaver_County,_Pennsylvania
Nottingham_Township,_Washington_County,_Pennsylvania
Mohnton,_Pennsylvania
McSherrystown,_Pennsylvania
Malvern,_Pennsylvania
Mahoning_Township,_Lawrence_County,_Pennsylvania
Bradford_Township,_Clearfield_County,_Pennsylvania
Wolf_Township,_Lycoming_County,_Pennsylvania
Lake_City,_Pennsylvania
Briar_Creek_Township,_Pennsylvania
Springfield_Township,_Fayette_County,_Pennsylvania
Youngwood,_Pennsylvania
Washington_Townshi

Eddystone,_Pennsylvania
Gregg_Township,_Centre_County,_Pennsylvania
Coopersburg,_Pennsylvania
Marcus_Hook,_Pennsylvania
Woodward_Township,_Clinton_County,_Pennsylvania
Donegal_Township,_Westmoreland_County,_Pennsylvania
Red_Hill,_Pennsylvania
Greene_Township,_Beaver_County,_Pennsylvania
Highspire,_Pennsylvania
Clifford_Township,_Susquehanna_County,_Pennsylvania
Berwick_Township,_Pennsylvania
Cornplanter_Township,_Venango_County,_Pennsylvania
Alburtis,_Pennsylvania
Brothersvalley_Township,_Somerset_County,_Pennsylvania
Exeter_Township,_Luzerne_County,_Pennsylvania
Fawn_Township,_Allegheny_County,_Pennsylvania
Hamiltonban_Township,_Adams_County,_Pennsylvania
Huntington_Township,_Adams_County,_Pennsylvania
Connellsville_Township,_Fayette_County,_Pennsylvania
Hopewell_Township,_Cumberland_County,_Pennsylvania
Watsontown,_Pennsylvania
Loyalhanna_Township,_Westmoreland_County,_Pennsylvania
Dunkard_Township,_Greene_County,_Pennsylvania
Plumcreek_Township,_Armstrong_County,_Pennsylvania
Rye_To

Rayburn_Township,_Armstrong_County,_Pennsylvania
Braddock_Hills,_Pennsylvania
Washington_Township,_Clarion_County,_Pennsylvania
Cherry_Ridge_Township,_Wayne_County,_Pennsylvania
Donegal_Township,_Butler_County,_Pennsylvania
Forest_City,_Pennsylvania
Tullytown,_Pennsylvania
Metal_Township,_Pennsylvania
Jefferson_Township,_Mercer_County,_Pennsylvania
Port_Carbon,_Pennsylvania
Zerbe_Township,_Northumberland_County,_Pennsylvania
Brokenstraw_Township,_Warren_County,_Pennsylvania
East_Providence_Township,_Bedford_County,_Pennsylvania
Limestone_Township,_Clarion_County,_Pennsylvania
Oil_Creek_Township,_Crawford_County,_Pennsylvania
Brush_Valley_Township,_Indiana_County,_Pennsylvania
Trainer,_Pennsylvania
Londonderry_Township,_Bedford_County,_Pennsylvania
West_Franklin_Township,_Armstrong_County,_Pennsylvania
Upper_Fairfield_Township,_Lycoming_County,_Pennsylvania
Jacobus,_Pennsylvania
Elkland,_Pennsylvania
East_Nantmeal_Township,_Chester_County,_Pennsylvania
Lehigh_Township,_Wayne_County,_Pen

New_Beaver,_Pennsylvania
East_Mead_Township,_Crawford_County,_Pennsylvania
Perry_Township,_Greene_County,_Pennsylvania
Windsor,_Pennsylvania
Elk_Township,_Clarion_County,_Pennsylvania
Lewis_Township,_Union_County,_Pennsylvania
Clarks_Green,_Pennsylvania
Sullivan_Township,_Tioga_County,_Pennsylvania
North_Union_Township,_Schuylkill_County,_Pennsylvania
West_Bethlehem_Township,_Washington_County,_Pennsylvania
Oakdale,_Pennsylvania
Richmond_Township,_Crawford_County,_Pennsylvania
Conyngham_Township,_Luzerne_County,_Pennsylvania
Conneaut_Township,_Crawford_County,_Pennsylvania
Belfast_Township,_Fulton_County,_Pennsylvania
Horton_Township,_Elk_County,_Pennsylvania
Langhorne_Manor,_Pennsylvania
Rockland_Township,_Venango_County,_Pennsylvania
Blawnox,_Pennsylvania
Greenwood_Township,_Crawford_County,_Pennsylvania
Wilmington_Township,_Mercer_County,_Pennsylvania
Perry_Township,_Mercer_County,_Pennsylvania
Kline_Township,_Schuylkill_County,_Pennsylvania
Sterling_Township,_Wayne_County,_Pennsylv

Sykesville,_Pennsylvania
Knox,_Pennsylvania
Tatamy,_Pennsylvania
Durham_Township,_Bucks_County,_Pennsylvania
Tuscarora_Township,_Bradford_County,_Pennsylvania
Derry_Township,_Montour_County,_Pennsylvania
North_Towanda_Township,_Bradford_County,_Pennsylvania
Dennison_Township,_Luzerne_County,_Pennsylvania
Shinglehouse,_Pennsylvania
Carbondale_Township,_Lackawanna_County,_Pennsylvania
Osceola_Mills,_Pennsylvania
Rush_Township,_Northumberland_County,_Pennsylvania
South_Creek_Township,_Bradford_County,_Pennsylvania
Springfield_Township,_Bradford_County,_Pennsylvania
Cochranton,_Pennsylvania
Schuylkill_Township,_Schuylkill_County,_Pennsylvania
White_Haven,_Pennsylvania
Limestone_Township,_Montour_County,_Pennsylvania
Ashland_Township,_Pennsylvania
Lower_Tyrone_Township,_Fayette_County,_Pennsylvania
Milesburg,_Pennsylvania
Williams_Township,_Dauphin_County,_Pennsylvania
Slocum_Township,_Luzerne_County,_Pennsylvania
Juniata_Township,_Blair_County,_Pennsylvania
Cass_Township,_Huntingdon_County

West_Middlesex,_Pennsylvania
Spruce_Hill_Township,_Juniata_County,_Pennsylvania
East_Norwegian_Township,_Schuylkill_County,_Pennsylvania
Hubley_Township,_Schuylkill_County,_Pennsylvania
Union_Township,_Jefferson_County,_Pennsylvania
New_Milford,_Pennsylvania
Clinton_Township,_Venango_County,_Pennsylvania
Oil_Creek_Township,_Venango_County,_Pennsylvania
Carrolltown,_Pennsylvania
Beale_Township,_Pennsylvania
Halifax,_Pennsylvania
Parker,_Pennsylvania
Jackson_Township,_Susquehanna_County,_Pennsylvania
North_Irwin,_Pennsylvania
Spring_Creek_Township,_Warren_County,_Pennsylvania
Shickshinny,_Pennsylvania
Wolf_Creek_Township,_Mercer_County,_Pennsylvania
Windham_Township,_Wyoming_County,_Pennsylvania
Lathrop_Township,_Susquehanna_County,_Pennsylvania
York_Springs,_Pennsylvania
Freedom_Township,_Adams_County,_Pennsylvania
Wells_Township,_Bradford_County,_Pennsylvania
Worth_Township,_Centre_County,_Pennsylvania
White_Township,_Cambria_County,_Pennsylvania
Eldred,_Pennsylvania
Claysville,_Pennsy

Connoquenessing,_Pennsylvania
Scott_Township,_Wayne_County,_Pennsylvania
Wall,_Pennsylvania
Elkland_Township,_Sullivan_County,_Pennsylvania
Norwich_Township,_McKean_County,_Pennsylvania
Davidson_Township,_Sullivan_County,_Pennsylvania
Meshoppen,_Pennsylvania
West_Township,_Huntingdon_County,_Pennsylvania
Valencia,_Pennsylvania
Freeburg,_Pennsylvania
Austin,_Pennsylvania
East_Rochester,_Pennsylvania
Bastress_Township,_Lycoming_County,_Pennsylvania
Potter_Township,_Beaver_County,_Pennsylvania
New_Alexandria,_Pennsylvania
Ararat_Township,_Susquehanna_County,_Pennsylvania
Gaines_Township,_Tioga_County,_Pennsylvania
Oakland_Township,_Susquehanna_County,_Pennsylvania
Juniata_Township,_Huntingdon_County,_Pennsylvania
Monroe,_Pennsylvania
Watson_Township,_Lycoming_County,_Pennsylvania
West_Cameron_Township,_Northumberland_County,_Pennsylvania
Hickory_Township,_Forest_County,_Pennsylvania
Juniata_Terrace,_Pennsylvania
Dayton,_Pennsylvania
Strattanville,_Pennsylvania
Glen_Osborne,_Pennsylvania
L

Shrewsbury_Township,_Sullivan_County,_Pennsylvania
Youngstown,_Pennsylvania
Daisytown,_Pennsylvania
Kistler,_Pennsylvania
Herndon,_Pennsylvania
Elco,_Pennsylvania
Townville,_Pennsylvania
Franklin,_Cambria_County,_Pennsylvania
Laporte,_Pennsylvania
Keating_Township,_Potter_County,_Pennsylvania
East_Side,_Pennsylvania
Wallaceton,_Pennsylvania
Eau_Claire,_Pennsylvania
Triumph_Township,_Warren_County,_Pennsylvania
Penn_Lake_Park,_Pennsylvania
Creekside,_Pennsylvania
Freeport_Township,_Greene_County,_Pennsylvania
Applewold,_Pennsylvania
Plumville,_Pennsylvania
Porter_Township,_Jefferson_County,_Pennsylvania
Pillow,_Pennsylvania
Enon_Valley,_Pennsylvania
Spartansburg,_Pennsylvania
Manns_Choice,_Pennsylvania
Pine_Township,_Lycoming_County,_Pennsylvania
Thompson,_Pennsylvania
Hillsgrove_Township,_Sullivan_County,_Pennsylvania
Le_Raysville,_Pennsylvania
Unionville,_Centre_County,_Pennsylvania
Hunker,_Pennsylvania
Pavia_Township,_Bedford_County,_Pennsylvania
Hartleton,_Pennsylvania
Markleysburg,

Bishopville,_South_Carolina
Blacksburg,_South_Carolina
Blackville,_South_Carolina
Blenheim,_South_Carolina
Bluffton,_South_Carolina
Blythewood,_South_Carolina
Bonneau,_South_Carolina
Bowman,_South_Carolina
Branchville,_South_Carolina
Briarcliffe_Acres,_South_Carolina
Brunson,_South_Carolina
Burnettown,_South_Carolina
Calhoun_Falls,_South_Carolina
Camden,_South_Carolina
Cameron,_South_Carolina
Campobello,_South_Carolina
Carlisle,_South_Carolina
Cayce,_South_Carolina
Central,_South_Carolina
Central_Pacolet,_South_Carolina
Chapin,_South_Carolina
Charleston,_South_Carolina
Cheraw,_South_Carolina
Chesnee,_South_Carolina
Chester,_South_Carolina
Chesterfield,_South_Carolina
Clemson,_South_Carolina
Clinton,_South_Carolina
Clio,_South_Carolina
Clover,_South_Carolina
Columbia,_South_Carolina
Conway,_South_Carolina
Cope,_South_Carolina
Cordova,_South_Carolina
Cottageville,_South_Carolina
Coward,_South_Carolina
Cowpens,_South_Carolina
Cross_Hill,_South_Carolina
Darlington,_South_Carolina
Denmark,_

Marion,_South_Dakota
Howard,_South_Dakota
Faulkton,_South_Dakota
Viborg,_South_Dakota
Eureka,_South_Dakota
Scotland,_South_Dakota
Alcester,_South_Dakota
Plankinton,_South_Dakota
Elkton,_South_Dakota
Edgemont,_South_Dakota
Wessington_Springs,_South_Dakota
Estelline,_South_Dakota
Philip,_South_Dakota
Colton,_South_Dakota
Castlewood,_South_Dakota
Wall,_South_Dakota
Armour,_South_Dakota
Lake_Andes,_South_Dakota
Woonsocket,_South_Dakota
Onida,_South_Dakota
Alexandria,_South_Dakota
Colman,_South_Dakota
Canistota,_South_Dakota
Highmore,_South_Dakota
Menno,_South_Dakota
New_Underwood,_South_Dakota
Selby,_South_Dakota
Lake_Preston,_South_Dakota
Newell,_South_Dakota
Humboldt,_South_Dakota
Lake_Norden,_South_Dakota
Avon,_South_Dakota
Burke,_South_Dakota
Kimball,_South_Dakota
Tripp,_South_Dakota
McLaughlin,_South_Dakota
Corsica,_South_Dakota
Kadoka,_South_Dakota
White,_South_Dakota
White_River,_South_Dakota
Bridgewater,_South_Dakota
Timber_Lake,_South_Dakota
Dupree,_South_Dakota
Emery,_South_Dakot

Hartsville,_Tennessee
Henderson,_Tennessee
Hendersonville,_Tennessee
Henning,_Tennessee
Henry,_Tennessee
Hickory_Valley,_Tennessee
Hohenwald,_Tennessee
Hollow_Rock,_Tennessee
Hornbeak,_Tennessee
Hornsby,_Tennessee
Humboldt,_Tennessee
Huntingdon,_Tennessee
Huntland,_Tennessee
Huntsville,_Tennessee
Jacksboro,_Tennessee
Jackson,_Tennessee
Jamestown,_Tennessee
Jasper,_Tennessee
Jefferson_City,_Tennessee
Jellico,_Tennessee
Johnson_City,_Tennessee
Jonesborough,_Tennessee
Kenton,_Tennessee
Kimball,_Tennessee
Kingsport,_Tennessee
Kingston,_Tennessee
Kingston_Springs,_Tennessee
Knoxville,_Tennessee
Lafayette,_Tennessee
LaFollette,_Tennessee
La_Grange,_Tennessee
Lakeland,_Tennessee
Lakesite,_Tennessee
La_Vergne,_Tennessee
Lawrenceburg,_Tennessee
Lebanon,_Tennessee
Lenoir_City,_Tennessee
Lewisburg,_Tennessee
Lexington,_Tennessee
Liberty,_Tennessee
Linden,_Tennessee
Livingston,_Tennessee
Lobelville,_Tennessee
Lookout_Mountain,_Tennessee
Loretto,_Tennessee
Loudon,_Tennessee
Louisville,_Tennessee
Lu

Pecos,_Texas
Fair_Oaks_Ranch,_Texas
Burkburnett,_Texas
Pleasanton,_Texas
Fairview,_Texas
Bonham,_Texas
Heath,_Texas
Rockport,_Texas
Clute,_Texas
Bellmead,_Texas
Freeport,_Texas
Sweetwater,_Texas
Galena_Park,_Texas
Robstown,_Texas
Raymondville,_Texas
San_Elizario,_Texas
Ingleside,_Texas
Roanoke,_Texas
Vernon,_Texas
Sanger,_Texas
Lago_Vista,_Texas
Vidor,_Texas
Helotes,_Texas
Woodway,_Texas
Bridge_City,_Texas
Dayton,_Texas
Kennedale,_Texas
Jacinto_City,_Texas
Commerce,_Texas
Whitehouse,_Texas
Liberty_Hill,_Texas
Mont_Belvieu,_Texas
Pearsall,_Texas
Bee_Cave,_Texas
Northlake,_Texas
Aransas_Pass,_Texas
Graham,_Texas
Wharton,_Texas
Highland_Park,_Texas
Brownfield,_Texas
Joshua,_Texas
Hondo,_Texas
Liberty,_Texas
Hillsboro,_Texas
Cleveland,_Texas
Lucas,_Texas
Providence_Village,_Texas
Lamesa,_Texas
Prairie_View,_Texas
Navasota,_Texas
Richland_Hills,_Texas
Dalhart,_Texas
Sunnyvale,_Texas
Kaufman,_Texas
Los_Fresnos,_Texas
Fort_Stockton,_Texas
Perryton,_Texas
Cuero,_Texas
Kirby,_Texas
Floresville,

Menard,_Texas
Emory,_Texas
Thorndale,_Texas
Wallis,_Texas
Booker,_Texas
Brackettville,_Texas
Nevada,_Texas
Rosebud,_Texas
Plains,_Texas
Rotan,_Texas
Old_River-Winfree,_Texas
Natalia,_Texas
Big_Sandy,_Texas
Valley_Mills,_Texas
Sundown,_Texas
Lexington,_Texas
China,_Texas
Woodsboro,_Texas
Brownsboro,_Texas
Clear_Lake_Shores,_Texas
Kemp,_Texas
Elkhart,_Texas
Point_Venture,_Texas
Gholson,_Texas
Roscoe,_Texas
Rice,_Texas
Tioga,_Texas
Kempner,_Texas
La_Vernia,_Texas
Martindale,_Texas
Lakeside_City,_Texas
Munday,_Texas
La_Grulla,_Texas
Blue_Ridge,_Texas
Oyster_Creek,_Texas
Claude,_Texas
Tye,_Texas
Florence,_Texas
Newark,_Texas
Von_Ormy,_Texas
Cut_and_Shoot,_Texas
Granger,_Texas
Orange_Grove,_Texas
LaCoste,_Texas
Rio_Vista,_Texas
Ransom_Canyon,_Texas
Pine_Island,_Texas
Benavides,_Texas
Ore_City,_Texas
Sterling_City,_Texas
Eustace,_Texas
China_Grove,_Texas
Oak_Ridge,_Kaufman_County,_Texas
Rogers,_Texas
Holland,_Texas
Frankston,_Texas
Gruver,_Texas
Tiki_Island,_Texas
Lindsay,_Cooke_County,_Texas

Sun_Valley,_Texas
Seven_Oaks,_Texas
Pyote,_Texas
Valentine,_Texas
Neylandville,_Texas
Putnam,_Texas
Dorchester,_Texas
Lakeview,_Texas
Toyah,_Texas
Dayton_Lakes,_Texas
Spofford,_Texas
Draper,_Texas
Quintana,_Texas
Impact,_Texas
Los_Ybanez,_Texas
Mustang,_Texas
Alpine,_Utah
Alta,_Utah
Altamont,_Utah
Alton,_Utah
Amalga,_Utah
American_Fork,_Utah
Annabella,_Utah
Antimony,_Utah
Apple_Valley,_Utah
Aurora,_Utah
Ballard,_Utah
Bear_River_City,_Utah
Beaver,_Utah
Bicknell,_Utah
Big_Water,_Utah
Blanding,_Utah
Bluff,_Utah
Bluffdale,_Utah
Boulder,_Utah
Bountiful,_Utah
Brian_Head,_Utah
Brigham_City,_Utah
Brighton,_Utah
Bryce_Canyon_City,_Utah
Cannonville,_Utah
Castle_Dale,_Utah
Castle_Valley,_Utah
Cedar_City,_Utah
Cedar_Fort,_Utah
Cedar_Hills,_Utah
Centerfield,_Utah
Centerville,_Utah
Central_Valley,_Utah
Charleston,_Utah
Circleville,_Utah
Clarkston,_Utah
Clawson,_Utah
Clearfield,_Utah
Cleveland,_Utah
Clinton,_Utah
Coalville,_Utah
Copperton,_Utah
Corinne,_Utah
Cornish,_Utah
Cottonwood_Heights,_Utah
Dan

Washington,_Vermont
Waterbury,_Vermont
Waterford,_Vermont
Waterville,_Vermont
Weathersfield,_Vermont
Wells,_Vermont
West_Fairlee,_Vermont
West_Haven,_Vermont
West_Rutland,_Vermont
West_Windsor,_Vermont
Westfield,_Vermont
Westford,_Vermont
Westminster,_Vermont
Westmore,_Vermont
Weston,_Vermont
Weybridge,_Vermont
Wheelock,_Vermont
Whiting,_Vermont
Whitingham,_Vermont
Williamstown,_Vermont
Williston,_Vermont
Wilmington,_Vermont
Windham,_Vermont
Windsor,_Vermont
Winhall,_Vermont
Wolcott,_Vermont
Woodbury,_Vermont
Woodford,_Vermont
Woodstock,_Vermont
Worcester,_Vermont
Middlebury_(village),_Vermont
Montpelier,_Vermont
Brattleboro_(village),_Vermont
Windsor_(village),_Vermont
Bellows_Falls_(village),_Vermont
Woodstock_(village),_Vermont
Rutland_(city),_Vermont
Castleton_(village),_Vermont
Bennington_(village),_Vermont
St._Johnsbury_(village),_Vermont
Northfield_(village),_Vermont
Wilmington_(village),_Vermont
St._Albans_(city),_Vermont
Newport_(city),_Vermont
Fair_Haven_(village),_Vermont
Ca

Long_Beach,_Washington
Longview,_Washington
Lynden,_Washington
Lynnwood,_Washington
Mabton,_Washington
Maple_Valley,_Washington
Marysville,_Washington
Mattawa,_Washington
McCleary,_Washington
Medical_Lake,_Washington
Medina,_Washington
Mercer_Island,_Washington
Mesa,_Washington
Mill_Creek,_Washington
Millwood,_Washington
Milton,_Washington
Monroe,_Washington
Montesano,_Washington
Morton,_Washington
Moses_Lake,_Washington
Mossyrock,_Washington
Mount_Vernon,_Washington
Mountlake_Terrace,_Washington
Moxee,_Washington
Mukilteo,_Washington
Napavine,_Washington
Newcastle,_Washington
Newport,_Washington
Nooksack,_Washington
Normandy_Park,_Washington
North_Bend,_Washington
North_Bonneville,_Washington
Oak_Harbor,_Washington
Oakville,_Washington
Ocean_Shores,_Washington
Okanogan,_Washington
Olympia,_Washington
Omak,_Washington
Oroville,_Washington
Orting,_Washington
Othello,_Washington
Pacific,_Washington
Palouse,_Washington
Pasco,_Washington
Pateros,_Washington
Pomeroy,_Washington
Port_Angeles

Fairview,_West_Virginia
Lost_Creek,_West_Virginia
Windsor_Heights,_West_Virginia
Pine_Grove,_West_Virginia
Whitesville,_West_Virginia
Lester,_West_Virginia
Gilbert,_West_Virginia
Meadow_Bridge,_West_Virginia
Mitchell_Heights,_West_Virginia
Tunnelton,_West_Virginia
Flemington,_West_Virginia
Kermit,_West_Virginia
Hedgesville,_West_Virginia
Bramwell,_West_Virginia
Newburg,_West_Virginia
Iaeger,_West_Virginia
Valley_Grove,_West_Virginia
Harpers_Ferry,_West_Virginia
Wardensville,_West_Virginia
Albright,_West_Virginia
Flatwoods,_West_Virginia
Hundred,_West_Virginia
Durbin,_West_Virginia
Northfork,_West_Virginia
Ellenboro,_West_Virginia
Hillsboro,_West_Virginia
Henderson,_West_Virginia
Davy,_West_Virginia
Hendricks,_West_Virginia
Handley,_West_Virginia
Bradshaw,_West_Virginia
Quinwood,_West_Virginia
Hambleton,_West_Virginia
Elk_Garden,_West_Virginia
Bayard,_West_Virginia
Womelsdorf_(Coalton),_West_Virginia
Keystone,_West_Virginia
Worthington,_West_Virginia
Sand_Fork,_West_Virginia
Anawalt,_We

I iterate through the list, *all_pages*, to extract the *title* and *lastrevid* for each page. I then save these values in a dataframe called *titles_revids_df*.

In [17]:
titles = []
rev_ids = []

# Extract title and lastrevid
for i in range(0, len(all_pages)):
    page_id = list(all_pages[i]['query']['pages'])[0]
    title = all_pages[i]['query']['pages'][page_id]['title']
    revid = all_pages[i]['query']['pages'][page_id]['lastrevid']
    titles.append(title)
    rev_ids.append(revid)

In [18]:
# save title and lastrevid in df
titles_revids_df = pd.DataFrame({'title':titles,'revid':rev_ids})

# View df
titles_revids_df.head()

title       revid
0   Abbeville, Alabama  1171163550
1  Adamsville, Alabama  1177621427
2     Addison, Alabama  1168359898
3       Akron, Alabama  1165909508
4   Alabaster, Alabama  1179139816

For the next part of this analysis, I utilize the ORES machine learning system. More information on this system is available [here](https://www.mediawiki.org/wiki/ORES). This system makes labeled predictions about the quality of Wikipedia articles, using [these](https://en.wikipedia.org/wiki/Wikipedia:Content_assessment) content assessment procedures. For my analysis, I will be using the Liftwing version of ORES, and documentation is available at this [link](https://wikitech.wikimedia.org/wiki/Machine_Learning/LiftWing/Usage). General ORES documentation can also be accessed [here](https://ores.wikimedia.org/docs).

The code below has been adapted from a code example developed by Dr. David W. McDonald for use in DATA 512, a course in the UW MS Data Science degree program. This code is provided under the under the [Creative Commons](https://creativecommons.org) [CC-BY license](https://creativecommons.org/licenses/by/4.0/) (Revision 1.0 - August 15, 2023). The code was accessed at this [link](https://drive.google.com/file/d/17C9xsmR9U3lJeD52UTbAedlHDetwYsxs/view?usp=drive_link) on 10/11/2023.

In order to use this API, I created an account for the Wikimedia API portal at this [link](https://api.wikimedia.org/w/index.php?title=Special:UserLogin&centralAuthAutologinTried=1&centralAuthError=Not+centrally+logged+in) and created a personal API [token](https://api.wikimedia.org/wiki/Authentication). This allowed me to access my Client ID, Client secret, and Access token, which I use in my code below.

The code below creates constants that specify features such as the API endpoint and article titles and revision IDs of interest.

In [22]:
# Code from Dr. McDonald
#########
#
#    CONSTANTS
#

#    The current LiftWing ORES API endpoint and prediction model
#
API_ORES_LIFTWING_ENDPOINT = "https://api.wikimedia.org/service/lw/inference/v1/models/{model_name}:predict"
API_ORES_EN_QUALITY_MODEL = "enwiki-articlequality"

#
#    The throttling rate is a function of the Access token that you are granted when you request the token. The constants
#    come from dissecting the token and getting the rate limits from the granted token. An example of that is below.
#
API_LATENCY_ASSUMED = 0.002       # Assuming roughly 2ms latency on the API and network
API_THROTTLE_WAIT = (60.0/5000.0)-API_LATENCY_ASSUMED

#    When making automated requests we should include something that is unique to the person making the request
#    This should include an email - your UW email would be good to put in there
#    
#    Because all LiftWing API requests require some form of authentication, you need to provide your access token
#    as part of the header too
#
REQUEST_HEADER_TEMPLATE = {
    'User-Agent': "<tejalk@uw.edu>, University of Washington, MSDS DATA 512 - AUTUMN 2023",
    'Content-Type': 'application/json',
    'Authorization': "Bearer {access_token}"
}
#
#    This is a template for the parameters that we need to supply in the headers of an API request
#
REQUEST_HEADER_PARAMS_TEMPLATE = {
    'email_address' : "tejalk@uw.edu",         # your email address should go here
    'access_token'  : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2ZGY2NjVhYWUyZTg2N2RmMDdiMWZhMWYyMGUwNDMyZiIsImp0aSI6ImM4MzA3NWMzNTZlMmRiZTEzMjZlZWY5MzIyOThiZTY1ZmZkZWM0NzUxYjRkNWExNjE0ZTg5ZDZjNTUyNmJkYTQ1NWJhMTdlMWM3OTNkNWZhIiwiaWF0IjoxNjk3MDgzNDgxLjg2NzQ1MywibmJmIjoxNjk3MDgzNDgxLjg2NzQ1NiwiZXhwIjozMzI1Mzk5MjI4MS44NjUxOSwic3ViIjoiNzM5ODQ0OTgiLCJpc3MiOiJodHRwczovL21ldGEud2lraW1lZGlhLm9yZyIsInJhdGVsaW1pdCI6eyJyZXF1ZXN0c19wZXJfdW5pdCI6NTAwMCwidW5pdCI6IkhPVVIifSwic2NvcGVzIjpbImJhc2ljIl19.NczOVNkMNmCKa3Q-PD_qCXsC-npicQDfsSuSLoF-vdTkrvZReQe3fsp2-8THHyZy5BtNvZxIn6l-qds6mri_LGQzpxbI8VudARduN4mVvLvUfeblI-sX3nK_0xSirV6d9tKCeOWWgm_rCzXyCbwwHR7w7b2TSPTm-RPl8o5QLhmsxuOxzHqTlQVxO17aFFh05q2LX-iM3hOzgswwmihW3-9IpNeO6sI-7Co1hLCmNp3WIpExwNHmFgAKynxQJ7EyOcQYOWspayDWERx_-NzMUIbjU3e0tcwqKtrCrvNdvz5albjmbUqniiTyJRtYfhGOuxkY6dEUZwig8CJ0QY16DBENGKVr6nnPkAEazVxz31eElA-5hxcGJ472EGyGL_e0CTGZ0ltC3qxgZxZbIJ3IZJaCmrNAm2km_Vx3iMuz9B_ln2TGo7MNdSEiP99fRBCPDAOfLFtSoipUmY2kzMP-kwVXJV1z4JyESpf4M35PwAjGXGVCrfPaxKTTkUtCSp4ligW7j6knoR5cBHNwE4fTBV7LFM4K3iAz5dUmor0m85s5jclQ61iTqgBCLR2_kZ-WdKxaTiq8pyeqt7U-1EamjR-vgfKTOeCXkDu5kDFZ29pS8YAfOsTN0pahJLqn3TnkfNwB5oIqDDn1xIz251swPJvcZmmewQH7Ysz-weKGCTA"          # the access token you create will need to go here
}

#
#    A dictionary of English Wikipedia article titles (keys) and sample revision IDs that can be used for this ORES scoring example
#
# ARTICLE_REVISIONS = { 'Bison':1085687913 , 'Northern flicker':1086582504 , 'Red squirrel':1083787665 , 'Chinook salmon':1085406228 , 'Horseshoe bat':1060601936 }

#
#    This is a template of the data required as a payload when making a scoring request of the ORES model
#
ORES_REQUEST_DATA_TEMPLATE = {
    "lang":        "en",     # required that its english - we're scoring English Wikipedia revisions
    "rev_id":      "",       # this request requires a revision id
    "features":    True
}

#
#    These are used later - defined here so they, at least, have empty values
#
USERNAME = "Tejaluw"
ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI2ZGY2NjVhYWUyZTg2N2RmMDdiMWZhMWYyMGUwNDMyZiIsImp0aSI6ImM4MzA3NWMzNTZlMmRiZTEzMjZlZWY5MzIyOThiZTY1ZmZkZWM0NzUxYjRkNWExNjE0ZTg5ZDZjNTUyNmJkYTQ1NWJhMTdlMWM3OTNkNWZhIiwiaWF0IjoxNjk3MDgzNDgxLjg2NzQ1MywibmJmIjoxNjk3MDgzNDgxLjg2NzQ1NiwiZXhwIjozMzI1Mzk5MjI4MS44NjUxOSwic3ViIjoiNzM5ODQ0OTgiLCJpc3MiOiJodHRwczovL21ldGEud2lraW1lZGlhLm9yZyIsInJhdGVsaW1pdCI6eyJyZXF1ZXN0c19wZXJfdW5pdCI6NTAwMCwidW5pdCI6IkhPVVIifSwic2NvcGVzIjpbImJhc2ljIl19.NczOVNkMNmCKa3Q-PD_qCXsC-npicQDfsSuSLoF-vdTkrvZReQe3fsp2-8THHyZy5BtNvZxIn6l-qds6mri_LGQzpxbI8VudARduN4mVvLvUfeblI-sX3nK_0xSirV6d9tKCeOWWgm_rCzXyCbwwHR7w7b2TSPTm-RPl8o5QLhmsxuOxzHqTlQVxO17aFFh05q2LX-iM3hOzgswwmihW3-9IpNeO6sI-7Co1hLCmNp3WIpExwNHmFgAKynxQJ7EyOcQYOWspayDWERx_-NzMUIbjU3e0tcwqKtrCrvNdvz5albjmbUqniiTyJRtYfhGOuxkY6dEUZwig8CJ0QY16DBENGKVr6nnPkAEazVxz31eElA-5hxcGJ472EGyGL_e0CTGZ0ltC3qxgZxZbIJ3IZJaCmrNAm2km_Vx3iMuz9B_ln2TGo7MNdSEiP99fRBCPDAOfLFtSoipUmY2kzMP-kwVXJV1z4JyESpf4M35PwAjGXGVCrfPaxKTTkUtCSp4ligW7j6knoR5cBHNwE4fTBV7LFM4K3iAz5dUmor0m85s5jclQ61iTqgBCLR2_kZ-WdKxaTiq8pyeqt7U-1EamjR-vgfKTOeCXkDu5kDFZ29pS8YAfOsTN0pahJLqn3TnkfNwB5oIqDDn1xIz251swPJvcZmmewQH7Ysz-weKGCTA"
#

The next step is to define a function to make the ORES API request. The code below has also been modified from code provided by Dr. McDonald. According to Dr. McDonald:

*The API request will be made using a function to encapsulate call and make access reusable in other notebooks. The procedure is parameterized, relying on the constants above for some important default parameters. The primary assumption is that this function will be used to request data for a set of article revisions. The main parameter is 'article_revid'. One should be able to simply pass in a new article revision id on each call and get back a python dictionary as the result. A valid result will be a dictionary that contains the probabilities that the specific revision is one of six different article quality levels. Generally, quality level with the highest probability score is considered the quality level for the article. This can be tricky when you have two (or more) highly probable quality levels.*

In [23]:
# Code from Dr. McDonald
#########
#
#    PROCEDURES/FUNCTIONS
#

def request_ores_score_per_article(article_revid = None, email_address=None, access_token=None,
                                   endpoint_url = API_ORES_LIFTWING_ENDPOINT, 
                                   model_name = API_ORES_EN_QUALITY_MODEL, 
                                   request_data = ORES_REQUEST_DATA_TEMPLATE, 
                                   header_format = REQUEST_HEADER_TEMPLATE, 
                                   header_params = REQUEST_HEADER_PARAMS_TEMPLATE):
    
    #    Make sure we have an article revision id, email and token
    #    This approach prioritizes the parameters passed in when making the call
    if article_revid:
        request_data['rev_id'] = article_revid
    if email_address:
        header_params['email_address'] = email_address
    if access_token:
        header_params['access_token'] = access_token
    
    #   Making a request requires a revision id - an email address - and the access token
    if not request_data['rev_id']:
        raise Exception("Must provide an article revision id (rev_id) to score articles")
    if not header_params['email_address']:
        raise Exception("Must provide an 'email_address' value")
    if not header_params['access_token']:
        raise Exception("Must provide an 'access_token' value")
    
    # Create the request URL with the specified model parameter - default is a article quality score request
    request_url = endpoint_url.format(model_name=model_name)
    
    # Create a compliant request header from the template and the supplied parameters
    headers = dict()
    for key in header_format.keys():
        headers[str(key)] = header_format[key].format(**header_params)
    
    # make the request
    try:
        # we'll wait first, to make sure we don't exceed the limit in the situation where an exception
        # occurs during the request processing - throttling is always a good practice with a free data
        # source like ORES - or other community sources
        if API_THROTTLE_WAIT > 0.0:
            time.sleep(API_THROTTLE_WAIT)
        #response = requests.get(request_url, headers=headers)
        response = requests.post(request_url, headers=headers, data=json.dumps(request_data))
        json_response = response.json()
    except Exception as e:
        print(e)
        json_response = None
    return json_response

We call the function by passing in three items, revision id, email, and access token. We iterate through each of the revision IDs in the *titles_revids_df* dataframe created above. We also extract the revision IDs and predictions from the function results and store this in a new dataframe, *revids_preds_df*.

If unable to get a score for a particular article, the corresponding prediction column in the *revids_preds_df* will be blank.

In [76]:
city_titles = []
score_list = []
for i in range(0, len(titles_revids_df)): # len(titles_revids_df)
    id = int(titles_revids_df['revid'][i]) # convert to int
    title = titles_revids_df['title'][i]
    score = request_ores_score_per_article(article_revid=id,
                                       email_address="tejalk@uw.edu",
                                       access_token=ACCESS_TOKEN)
    print(title) # make sure API is running through all the cities
    score_list.append(score)
    city_titles.append(title)

Abbeville, Alabama
Adamsville, Alabama
Addison, Alabama
Akron, Alabama
Alabaster, Alabama
Albertville, Alabama
Alexander City, Alabama
Aliceville, Alabama
Allgood, Alabama
Altoona, Alabama
Andalusia, Alabama
Anderson, Lauderdale County, Alabama
Anniston, Alabama
Arab, Alabama
Ardmore, Alabama
Argo, Alabama
Ariton, Alabama
Arley, Alabama
Ashford, Alabama
Ashland, Alabama
Ashville, Alabama
Athens, Alabama
Atmore, Alabama
Attalla, Alabama
Auburn, Alabama
Autaugaville, Alabama
Avon, Alabama
Babbie, Alabama
Baileyton, Alabama
Bakerhill, Alabama
Banks, Alabama
Bay Minette, Alabama
Bayou La Batre, Alabama
Bear Creek, Alabama
Beatrice, Alabama
Beaverton, Alabama
Belk, Alabama
Benton, Alabama
Berlin, Alabama
Berry, Alabama
Bessemer, Alabama
Billingsley, Alabama
Birmingham, Alabama
Black, Alabama
Blountsville, Alabama
Blue Springs, Alabama
Boaz, Alabama
Boligee, Alabama
Bon Air, Alabama
Brantley, Alabama
Brent, Alabama
Brewton, Alabama
Bridgeport, Alabama
Brighton, Alabama
Brilliant, Alabama
Bro

Waverly, Alabama
Weaver, Alabama
Webb, Alabama
Wedowee, Alabama
West Blocton, Alabama
West Jefferson, Alabama
West Point, Alabama
Westover, Alabama
Wetumpka, Alabama
White Hall, Alabama
Wilsonville, Alabama
Wilton, Alabama
Winfield, Alabama
Woodland, Alabama
Woodstock, Alabama
Woodville, Alabama
Yellow Bluff, Alabama
York, Alabama
Adak, Alaska
Akhiok, Alaska
Akiak, Alaska
Akutan, Alaska
Alakanuk, Alaska
Aleknagik, Alaska
Allakaket, Alaska
Ambler, Alaska
Anaktuvuk Pass, Alaska
Anchorage, Alaska
Anderson, Alaska
Angoon, Alaska
Aniak, Alaska
Anvik, Alaska
Atka, Alaska
Atqasuk, Alaska
Bethel, Alaska
Bettles, Alaska
Brevig Mission, Alaska
Buckland, Alaska
Chefornak, Alaska
Chevak, Alaska
Chignik, Alaska
Chuathbaluk, Alaska
Clark's Point, Alaska
Coffman Cove, Alaska
Cold Bay, Alaska
Cordova, Alaska
Craig, Alaska
Deering, Alaska
Delta Junction, Alaska
Dillingham, Alaska
Diomede, Alaska
Eagle, Alaska
Edna Bay, Alaska
Eek, Alaska
Egegik, Alaska
Ekwok, Alaska
Elim, Alaska
Emmonak, Alaska
Fairban

Greenland, Arkansas
Greenway, Arkansas
Greenwood, Arkansas
Greers Ferry, Arkansas
Griffithville, Arkansas
Grubbs, Arkansas
Guion, Arkansas
Gum Springs, Arkansas
Gurdon, Arkansas
Guy, Arkansas
Hackett, Arkansas
Hamburg, Arkansas
Hampton, Arkansas
Hardy, Arkansas
Harrell, Arkansas
Harrisburg, Arkansas
Harrison, Arkansas
Hartford, Arkansas
Hartman, Arkansas
Haskell, Arkansas
Hatfield, Arkansas
Havana, Arkansas
Haynes, Arkansas
Hazen, Arkansas
Heber Springs, Arkansas
Hector, Arkansas
Helena-West Helena, Arkansas
Hermitage, Arkansas
Hickory Ridge, Arkansas
Higden, Arkansas
Higginson, Arkansas
Highfill, Arkansas
Highland, Arkansas
Hindsville, Arkansas
Holland, Arkansas
Holly Grove, Arkansas
Hope, Arkansas
Horatio, Arkansas
Horseshoe Bend, Arkansas
Horseshoe Lake, Arkansas
Hot Springs, Arkansas
Houston, Arkansas
Hoxie, Arkansas
Hughes, Arkansas
Humnoke, Arkansas
Humphrey, Arkansas
Hunter, Arkansas
Huntington, Arkansas
Huntsville, Arkansas
Huttig, Arkansas
Imboden, Arkansas
Jacksonport, Arkans

Cupertino, California
Cypress, California
Daly City, California
Dana Point, California
Danville, California
Davis, California
Del Mar, California
Del Rey Oaks, California
Delano, California
Desert Hot Springs, California
Diamond Bar, California
Dinuba, California
Dixon, California
Dorris, California
Dos Palos, California
Downey, California
Duarte, California
Dublin, California
Dunsmuir, California
East Palo Alto, California
Eastvale, California
El Cajon, California
El Centro, California
El Cerrito, California
El Monte, California
El Segundo, California
Elk Grove, California
Emeryville, California
Encinitas, California
Escalon, California
Escondido, California
Etna, California
Eureka, California
Exeter, California
Fairfax, California
Fairfield, California
Farmersville, California
Ferndale, California
Fillmore, California
Firebaugh, California
Folsom, California
Fontana, California
Fort Bragg, California
Fort Jones, California
Fortuna, California
Foster City, California
Fountain Valley, 

Willows, California
Windsor, California
Winters, California
Woodlake, California
Woodland, California
Woodside, California
Yorba Linda, California
Yountville, California
Yreka, California
Yuba City, California
Yucaipa, California
Yucca Valley, California
2020 United States census
2010 United States census
Aguilar, Colorado
Akron, Colorado
Alamosa, Colorado
Alma, Colorado
Antonito, Colorado
Arriba, Colorado
Arvada, Colorado
Aspen, Colorado
Ault, Colorado
Aurora, Colorado
Avon, Colorado
Basalt, Colorado
Bayfield, Colorado
Bennett, Colorado
Berthoud, Colorado
Bethune, Colorado
Black Hawk, Colorado
Blanca, Colorado
Blue River, Colorado
Bonanza, Colorado
Boone, Colorado
Boulder, Colorado
Bow Mar, Colorado
Branson, Colorado
Breckenridge, Colorado
Brighton, Colorado
Brookside, Colorado
Broomfield, Colorado
Brush, Colorado
Buena Vista, Colorado
Burlington, Colorado
Calhan, Colorado
Campo, Colorado
Cañon City, Colorado
Carbonate, Colorado
Carbondale, Colorado
Castle Pines, Colorado
Castle Rock,

Century, Florida
Chattahoochee, Florida
Chiefland, Florida
Chipley, Florida
Cinco Bayou, Florida
Clearwater, Florida
Clermont, Florida
Clewiston, Florida
Cloud Lake, Florida
Cocoa, Florida
Cocoa Beach, Florida
Coconut Creek, Florida
Coleman, Florida
Cooper City, Florida
Coral Gables, Florida
Coral Springs, Florida
Cottondale, Florida
Crescent City, Florida
Crestview, Florida
Cross City, Florida
Crystal River, Florida
Cutler Bay, Florida
Dade City, Florida
Dania Beach, Florida
Davenport, Florida
Davie, Florida
Daytona Beach, Florida
Daytona Beach Shores, Florida
DeBary, Florida
Deerfield Beach, Florida
DeFuniak Springs, Florida
DeLand, Florida
Delray Beach, Florida
Deltona, Florida
Destin, Florida
Doral, Florida
Dundee, Florida
Dunedin, Florida
Dunnellon, Florida
Eagle Lake, Florida
Eatonville, Florida
Ebro, Florida
Edgewater, Volusia County, Florida
Edgewood, Florida
El Portal, Florida
Estero, Florida
Esto, Florida
Eustis, Florida
Everglades City, Florida
Fanning Springs, Florida
Fells

Blairsville, Georgia
Blakely, Georgia
Bloomingdale, Georgia
Blue Ridge, Georgia
Bluffton, Georgia
Blythe, Georgia
Bogart, Georgia
Boston, Georgia
Bostwick, Georgia
Bowdon, Georgia
Bowersville, Georgia
Bowman, Georgia
Braselton, Georgia
Braswell, Georgia
Bremen, Georgia
Brinson, Georgia
Bronwood, Georgia
Brookhaven, Georgia
Brooklet, Georgia
Brooks, Georgia
Broxton, Georgia
Brunswick, Georgia
Buchanan, Georgia
Buckhead, Morgan County, Georgia
Buena Vista, Georgia
Buford, Georgia
Butler, Georgia
Byromville, Georgia
Byron, Georgia
Cadwell, Georgia
Cairo, Georgia
Calhoun, Georgia
Camak, Georgia
Camilla, Georgia
Canon, Georgia
Canton, Georgia
Carl, Georgia
Carlton, Georgia
Carnesville, Georgia
Carrollton, Georgia
Cartersville, Georgia
Cave Spring, Georgia
Cecil, Georgia
Cedartown, Georgia
Centerville, Georgia
Centralhatchee, Georgia
Chamblee, Georgia
Chatsworth, Georgia
Chattahoochee Hills, Georgia
Chauncey, Georgia
Chester, Georgia
Chickamauga, Georgia
Clarkesville, Georgia
Clarkston, Geor

Varnell, Georgia
Vernonburg, Georgia
Vidette, Georgia
Vienna, Georgia
Vidalia, Georgia
Villa Rica, Georgia
Waco, Georgia
Wadley, Georgia
Waleska, Georgia
Walnut Grove, Georgia
Walthourville, Georgia
Warm Springs, Georgia
Warner Robins, Georgia
Warrenton, Georgia
Warwick, Georgia
Washington, Georgia
Watkinsville, Georgia
Waverly Hall, Georgia
Waycross, Georgia
Waynesboro, Georgia
Webster County, Georgia
West Point, Georgia
Whigham, Georgia
White, Georgia
White Plains, Georgia
Whitesburg, Georgia
Willacoochee, Georgia
Williamson, Georgia
Winder, Georgia
Winterville, Georgia
Woodbine, Georgia
Woodbury, Georgia
Woodland, Georgia
Woodstock, Georgia
Woodville, Georgia
Woolsey, Georgia
Wrens, Georgia
Wrightsville, Georgia
Yatesville, Georgia
Young Harris, Georgia
Zebulon, Georgia
Honolulu, Hawaii
East Honolulu, Hawaii
Pearl City, Hawaii
Hilo, Hawaii
Waipahu, Hawaii
Kailua, Honolulu County, Hawaii
Kaneohe, Hawaii
Kahului, Hawaii
Mililani, Hawaii
'Ewa Gentry, Hawaii
Kihei, Hawaii
Kapolei, Hawai

Beecher City, Illinois
Belgium, Illinois
Belknap, Illinois
Belle Prairie City, Illinois
Belle Rive, Illinois
Belleville, Illinois
Bellevue, Illinois
Bellflower, Illinois
Bellmont, Illinois
Bellwood, Illinois
Belvidere, Illinois
Bement, Illinois
Benld, Illinois
Bensenville, Illinois
Benson, Illinois
Bentley, Illinois
Benton, Illinois
Berkeley, Illinois
Berlin, Illinois
Berwyn, Illinois
Bethalto, Illinois
Bethany, Illinois
Biggsville, Illinois
Big Rock, Illinois
Bingham, Illinois
Bishop Hill, Illinois
Bismarck, Illinois
Blandinsville, Illinois
Bloomingdale, Illinois
Bloomington, Illinois
Blue Island, Illinois
Blue Mound, Illinois
Bluffs, Illinois
Bluford, Illinois
Bolingbrook, Illinois
Bondville, Illinois
Bone Gap, Illinois
Bonfield, Illinois
Bonnie, Illinois
Bourbonnais, Illinois
Bowen, Illinois
Braceville, Illinois
Bradford, Illinois
Bradley, Illinois
Braidwood, Illinois
Breese, Illinois
Bridgeport, Illinois
Bridgeview, Illinois
Brighton, Illinois
Brimfield, Illinois
Broadlands, Illino

Hartford, Illinois
Hartsburg, Illinois
Harvard, Illinois
Harvel, Illinois
Harvey, Illinois
Harwood Heights, Illinois
Havana, Illinois
Hawthorn Woods, Illinois
Hazel Crest, Illinois
Hebron, Illinois
Hecker, Illinois
Henderson, Illinois
Hennepin, Illinois
Henning, Illinois
Henry, Illinois
Herrick, Illinois
Herrin, Illinois
Herscher, Illinois
Hettick, Illinois
Heyworth, Illinois
Hickory Hills, Illinois
Hidalgo, Illinois
Highland, Illinois
Highland Park, Illinois
Highwood, Illinois
Hillcrest, Illinois
Hillsboro, Illinois
Hillsdale, Illinois
Hillside, Illinois
Hillview, Illinois
Hinckley, Illinois
Hindsboro, Illinois
Hinsdale, Illinois
Hodgkins, Illinois
Hoffman, Illinois
Hoffman Estates, Illinois
Holiday Hills, Illinois
Hollowayville, Illinois
Homer, Illinois
Homer Glen, Illinois
Hometown, Illinois
Homewood, Illinois
Hoopeston, Illinois
Hooppole, Illinois
Hopedale, Illinois
Hopewell, Illinois
Hopkins Park, Illinois
Hoyleton, Illinois
Hudson, Illinois
Huey, Illinois
Hull, Illinois
Humboldt,

Pecatonica, Illinois
Pekin, Illinois
Peoria, Illinois
Peoria Heights, Illinois
Peotone, Illinois
Percy, Illinois
Perry, Illinois
Peru, Illinois
Pesotum, Illinois
Petersburg, Illinois
Phillipstown, Illinois
Philo, Illinois
Phoenix, Illinois
Pierron, Illinois
Pinckneyville, Illinois
Pingree Grove, Illinois
Piper City, Illinois
Pittsburg, Illinois
Pittsfield, Illinois
Plainfield, Illinois
Plainville, Illinois
Plano, Illinois
Plattville, Illinois
Pleasant Hill, Illinois
Pleasant Plains, Illinois
Plymouth, Illinois
Pocahontas, Illinois
Polo, Illinois
Pontiac, Illinois
Pontoon Beach, Illinois
Pontoosuc, Illinois
Poplar Grove, Illinois
Port Barrington, Illinois
Port Byron, Illinois
Posen, Illinois
Potomac, Illinois
Prairie City, Illinois
Prairie du Rocher, Illinois
Prairie Grove, Illinois
Princeton, Illinois
Princeville, Illinois
Prophetstown, Illinois
Prospect Heights, Illinois
Pulaski, Illinois
Quincy, Illinois
Radom, Illinois
Raleigh, Illinois
Ramsey, Illinois
Rankin, Illinois
Ransom, Illi

Schererville, Indiana
Brownsburg, Indiana
Hobart, Indiana
East Chicago, Indiana
Marion, Indiana
Franklin, Indiana
Highland, Lake County, Indiana
Munster, Indiana
Greenfield, Indiana
Clarksville, Indiana
Avon, Indiana
La Porte, Indiana
St. John, Indiana
Seymour, Indiana
Shelbyville, Indiana
Logansport, Indiana
New Castle, Indiana
Huntington, Indiana
Vincennes, Indiana
Griffith, Indiana
Dyer, Indiana
Crawfordsville, Indiana
Lebanon, Indiana
New Haven, Indiana
Frankfort, Indiana
Jasper, Indiana
Warsaw, Indiana
Beech Grove, Indiana
Chesterton, Indiana
Cedar Lake, Indiana
Speedway, Indiana
Auburn, Indiana
Bedford, Indiana
Connersville, Indiana
Washington, Indiana
Greensburg, Indiana
Lake Station, Indiana
Martinsville, Indiana
Madison, Indiana
Yorktown, Indiana
Peru, Indiana
Lowell, Indiana
Danville, Indiana
Wabash, Indiana
Bluffton, Indiana
Kendallville, Indiana
Plymouth, Indiana
Whitestown, Indiana
Decatur, Indiana
Columbia City, Indiana
Greencastle, Indiana
Bargersville, Indiana
Mooresvil

Richland City, Indiana
Ridgeville, Indiana
Riley, Indiana
River Forest, Indiana
Roachdale, Indiana
Roann, Indiana
Roanoke, Indiana
Rocky Ripple, Indiana
Rome City, Indiana
Rosedale, Indiana
Roseland, Indiana
Rossville, Indiana
Royal Center, Indiana
Russellville, Indiana
Russiaville, Indiana
St. Joe, Indiana
St. Leon, Indiana
St. Paul, Indiana
Salamonia, Indiana
Saltillo, Indiana
Sandborn, Indiana
Saratoga, Indiana
Schneider, Indiana
Seelyville, Indiana
Selma, Indiana
Shadeland, Indiana
Shamrock Lakes, Indiana
Sharpsville, Indiana
Shelburn, Indiana
Shipshewana, Indiana
Shirley, Indiana
Shoals, Indiana
Sidney, Indiana
Silver Lake, Indiana
Somerville, Indiana
South Whitley, Indiana
Spiceland, Indiana
Spring Grove, Indiana
Spring Hill, Indiana
Spring Lake, Indiana
Springport, Indiana
Spurgeon, Indiana
State Line City, Indiana
Staunton, Indiana
Stilesville, Indiana
Stinesville, Indiana
Straughn, Indiana
Sulphur Springs, Indiana
Summitville, Indiana
Sunman, Indiana
Swayzee, Indiana
Sweetser,

Floyd, Iowa
Fonda, Iowa
Pocahontas County, Iowa
Fontanelle, Iowa
Forest City, Iowa
Fort Atkinson, Iowa
Fort Dodge, Iowa
Fort Madison, Iowa
Fostoria, Iowa
Franklin, Iowa
Fraser, Iowa
Fredericksburg, Iowa
Frederika, Iowa
Fredonia, Iowa
Fremont, Iowa
Fruitland, Iowa
Galt, Iowa
Galva, Iowa
Garber, Iowa
Garden Grove, Iowa
Garnavillo, Iowa
Garner, Iowa
Garrison, Iowa
Garwin, Iowa
Geneva, Iowa
George, Iowa
Gibson, Iowa
Gilbert, Iowa
Gilbertville, Iowa
Gillett Grove, Iowa
Gilman, Iowa
Gilmore City, Iowa
Gladbrook, Iowa
Glenwood, Iowa
Glidden, Iowa
Goldfield, Iowa
Goodell, Iowa
Goose Lake, Iowa
Gowrie, Iowa
Graettinger, Iowa
Graf, Iowa
Grafton, Iowa
Grand Junction, Iowa
Grand Mound, Iowa
Grand River, Iowa
Grandview, Iowa
Granger, Iowa
Grant, Iowa
Granville, Iowa
Gravity, Iowa
Gray, Iowa
Greeley, Iowa
Greene, Iowa
Greenfield, Iowa
Greenville, Iowa
Grimes, Iowa
Grinnell, Iowa
Griswold, Iowa
Grundy Center, Iowa
Gruver, Iowa
Guernsey, Iowa
Guthrie Center, Iowa
Guttenberg, Iowa
Halbur, Iowa
Hamburg,

Tama, Iowa
Templeton, Iowa
Tennant, Iowa
Terril, Iowa
Thayer, Iowa
Thompson, Iowa
Thor, Iowa
Thornburg, Iowa
Thornton, Iowa
Thurman, Iowa
Tiffin, Iowa
Tingley, Iowa
Tipton, Iowa
Titonka, Iowa
Toledo, Iowa
Toronto, Iowa
Traer, Iowa
Treynor, Iowa
Tripoli, Iowa
Truesdale, Iowa
Truro, Iowa
Turin, Iowa
Udell, Iowa
Underwood, Iowa
Union, Iowa
Unionville, Iowa
University Heights, Iowa
University Park, Iowa
Urbana, Iowa
Urbandale, Iowa
Ute, Iowa
Vail, Iowa
Valeria, Iowa
Van Horne, Iowa
Van Meter, Iowa
Van Wert, Iowa
Varina, Iowa
Ventura, Iowa
Victor, Iowa
Villisca, Iowa
Vincent, Iowa
Vining, Iowa
Vinton, Iowa
Volga, Iowa
Wadena, Iowa
Wahpeton, Iowa
Walcott, Iowa
Walford, Iowa
Walker, Iowa
Wall Lake, Iowa
Wallingford, Iowa
Walnut, Iowa
Wapello, Iowa
Washington, Iowa
Washta, Iowa
Waterloo, Iowa
Waterville, Iowa
Waucoma, Iowa
Waukee, Iowa
Waukon, Iowa
Waverly, Iowa
Wayland, Iowa
Webb, Iowa
Webster, Iowa
Webster City, Iowa
Weldon, Iowa
Wellman, Iowa
Wellsburg, Iowa
Welton, Iowa
Wesley, Iowa
West B

Muldraugh, Kentucky
Munfordville, Kentucky
Murray, Kentucky
Murray Hill, Kentucky
Nebo, Kentucky
New Castle, Kentucky
New Haven, Kentucky
Newport, Kentucky
Nicholasville, Kentucky
Norbourne Estates, Kentucky
North Middletown, Kentucky
Northfield, Kentucky
Nortonville, Kentucky
Norwood, Kentucky
Oak Grove, Kentucky
Oakland, Kentucky
Old Brownsboro Place, Kentucky
Olive Hill, Kentucky
Orchard Grass Hills, Kentucky
Owensboro, Kentucky
Owenton, Kentucky
Owingsville, Kentucky
Paducah, Kentucky
Paintsville, Kentucky
Paris, Kentucky
Park City, Kentucky
Park Hills, Kentucky
Parkway Village, Kentucky
Pembroke, Kentucky
Perryville, Kentucky
Pewee Valley, Kentucky
Pikeville, Kentucky
Pineville, Kentucky
Pioneer Village, Kentucky
Pippa Passes, Kentucky
Plantation, Kentucky
Pleasureville, Kentucky
Plum Springs, Kentucky
Poplar Hills, Kentucky
Powderly, Kentucky
Prestonsburg, Kentucky
Prestonville, Kentucky
Princeton, Kentucky
Prospect, Kentucky
Providence, Kentucky
Raceland, Kentucky
Radcliff, Kent

Robeline, Louisiana
Rodessa, Louisiana
Rosedale, Louisiana
Roseland, Louisiana
Rosepine, Louisiana
Ruston, Louisiana
St. Francisville, Louisiana
St. Gabriel, Louisiana
St. Joseph, Louisiana
St. Martinville, Louisiana
Saline, Louisiana
Sarepta, Louisiana
Scott, Louisiana
Shongaloo, Louisiana
Shreveport, Louisiana
Sibley, Louisiana
Sicily Island, Louisiana
Sikes, Louisiana
Simmesport, Louisiana
Simpson, Louisiana
Simsboro, Louisiana
Slaughter, Louisiana
Slidell, Louisiana
Sorrento, Louisiana
South Mansfield, Louisiana
Spearsville, Louisiana
Springfield, Louisiana
Springhill, Louisiana
Stanley, Louisiana
Sterlington, Louisiana
Stonewall, Louisiana
Sulphur, Louisiana
Sun, Louisiana
Sunset, Louisiana
Tallulah, Louisiana
Tangipahoa, Louisiana
Thibodaux, Louisiana
Tickfaw, Louisiana
Tullos, Louisiana
Turkey Creek, Louisiana
Urania, Louisiana
Varnado, Louisiana
Vidalia, Louisiana
Vienna, Louisiana
Ville Platte, Louisiana
Vinton, Louisiana
Vivian, Louisiana
Walker, Louisiana
Washington, Louisia

Swanville, Maine
Sweden, Maine
Talmadge, Maine
Temple, Maine
The Forks, Maine
Thomaston, Maine
Thorndike, Maine
Topsfield, Maine
Topsham, Maine
Tremont, Maine
Trenton, Maine
Troy, Maine
Turner, Maine
Union, Maine
Unity, Maine
Upton, Maine
Van Buren, Maine
Vanceboro, Maine
Vassalboro, Maine
Veazie, Maine
Verona Island, Maine
Vienna, Maine
Vinalhaven, Maine
Wade, Maine
Waite, Maine
Waldo, Maine
Waldoboro, Maine
Wales, Maine
Wallagrass, Maine
Waltham, Maine
Warren, Maine
Washburn, Maine
Washington, Maine
Waterboro, Maine
Waterville, Maine
Waterford, Maine
Wayne, Maine
Webster Plantation, Maine
Weld, Maine
Wellington, Maine
Wells, Maine
Wesley, Maine
West Bath, Maine
Westbrook, Maine
West Forks, Maine
West Gardiner, Maine
West Paris, Maine
Westfield, Maine
Westmanland, Maine
Weston, Maine
Westport Island, Maine
Whitefield, Maine
Whiting, Maine
Whitneyville, Maine
Willimantic, Maine
Wilton, Maine
Windham, Maine
Windsor, Maine
Winn, Maine
Winslow, Maine
Winter Harbor, Maine
Winterport, Maine

Leverett, Massachusetts
Lexington, Massachusetts
Leyden, Massachusetts
Lincoln, Massachusetts
Littleton, Massachusetts
Longmeadow, Massachusetts
Lowell, Massachusetts
Ludlow, Massachusetts
Lunenburg, Massachusetts
Lynn, Massachusetts
Lynnfield, Massachusetts
Malden, Massachusetts
Manchester-by-the-Sea, Massachusetts
Mansfield, Massachusetts
Marblehead, Massachusetts
Marion, Massachusetts
Marlborough, Massachusetts
Marshfield, Massachusetts
Mashpee, Massachusetts
Mattapoisett, Massachusetts
Maynard, Massachusetts
Medfield, Massachusetts
Medford, Massachusetts
Medway, Massachusetts
Melrose, Massachusetts
Mendon, Massachusetts
Merrimac, Massachusetts
Methuen, Massachusetts
Middleborough, Massachusetts
Middlefield, Massachusetts
Middleton, Massachusetts
Milford, Massachusetts
Millbury, Massachusetts
Millis, Massachusetts
Millville, Massachusetts
Milton, Massachusetts
Monroe, Massachusetts
Monson, Massachusetts
Montague, Massachusetts
Monterey, Massachusetts
Montgomery, Massachusetts
Mount 

Beaver Creek Township, Michigan
Beaverton, Michigan
Beaverton Township, Michigan
Bedford Charter Township, Michigan
Bedford Township, Monroe County, Michigan
Belding, Michigan
Belknap Township, Michigan
Bellaire, Michigan
Belleville, Michigan
Bellevue, Michigan
Bellevue Township, Michigan
Belvidere Township, Michigan
Bengal Township, Michigan
Bennington Township, Michigan
Benona Township, Michigan
Bentley Township, Michigan
Benton Charter Township, Michigan
Benton Township, Cheboygan County, Michigan
Benton Township, Eaton County, Michigan
Benton Harbor, Michigan
Benzonia, Michigan
Benzonia Township, Michigan
Bergland Township, Michigan
Berkley, Michigan
Berlin Township, Ionia County, Michigan
Berlin Charter Township, Michigan
Berlin Township, St. Clair County, Michigan
Berrien Township, Michigan
Berrien Springs, Michigan
Bertrand Township, Michigan
Bessemer, Michigan
Bessemer Township, Michigan
Bethany Township, Michigan
Bethel Township, Michigan
Beulah, Michigan
Beverly Hills, Michig

Copper City, Michigan
Cornell Township, Michigan
Corunna, Michigan
Corwith Township, Michigan
Cottrellville Township, Michigan
Courtland Township, Michigan
Covert Township, Michigan
Covington Township, Michigan
Crockery Township, Michigan
Cross Village Township, Michigan
Croswell, Michigan
Croton Township, Michigan
Crystal Township, Montcalm County, Michigan
Crystal Township, Oceana County, Michigan
Crystal Falls, Michigan
Crystal Falls Township, Michigan
Crystal Lake Township, Michigan
Cumming Township, Michigan
Curtis Township, Michigan
Custer Township, Antrim County, Michigan
Custer, Michigan
Custer Township, Mason County, Michigan
Custer Township, Sanilac County, Michigan
Dafter Township, Michigan
Daggett, Michigan
Daggett Township, Michigan
Dallas Township, Michigan
Dalton Township, Michigan
Danby Township, Michigan
Dansville, Michigan
Davison, Michigan
Davison Township, Michigan
Day Township, Michigan
Dayton Township, Newaygo County, Michigan
Dayton Township, Tuscola County, Mich

Grant Township, Huron County, Michigan
Grant Township, Iosco County, Michigan
Grant Township, Keweenaw County, Michigan
Grant Township, Mason County, Michigan
Grant Township, Mecosta County, Michigan
Grant, Michigan
Grant Township, Newaygo County, Michigan
Grant Township, Oceana County, Michigan
Grant Township, St. Clair County, Michigan
Grass Lake, Michigan
Grass Lake Charter Township, Michigan
Grattan Township, Michigan
Grayling, Michigan
Grayling Charter Township, Michigan
Green Township, Michigan
Green Charter Township, Michigan
Greenbush Township, Alcona County, Michigan
Greenbush Township, Clinton County, Michigan
Greendale Township, Michigan
Green Lake Township, Michigan
Greenland Township, Michigan
Greenleaf Township, Michigan
Green Oak Township, Michigan
Greenville, Michigan
Greenwood Township, Clare County, Michigan
Greenwood Township, Oceana County, Michigan
Greenwood Township, Oscoda County, Michigan
Greenwood Township, St. Clair County, Michigan
Greenwood Township, Wexford

Little Traverse Township, Michigan
Livingston Township, Michigan
Livonia, Michigan
Locke Township, Michigan
Lockport Township, Michigan
Lodi Township, Michigan
Logan Township, Mason County, Michigan
Logan Township, Ogemaw County, Michigan
London Township, Michigan
Long Lake Township, Michigan
Long Rapids Township, Michigan
Loud Township, Michigan
Lovells Township, Michigan
Lowell, Michigan
Lowell Charter Township, Michigan
Ludington, Michigan
Luna Pier, Michigan
Luther, Michigan
Lyndon Township, Michigan
Lynn Township, Michigan
Lyon Township, Oakland County, Michigan
Lyon Township, Roscommon County, Michigan
Lyons, Michigan
Lyons Township, Michigan
McBain, Michigan
McBride, Michigan
Mackinac Island, Michigan
Mackinaw Township, Michigan
Mackinaw City, Michigan
McKinley Township, Emmet County, Michigan
McKinley Township, Huron County, Michigan
McMillan Township, Luce County, Michigan
McMillan Township, Ontonagon County, Michigan
Macomb Township, Michigan
Macon Township, Michigan
Madison 

Oxford, Michigan
Oxford Charter Township, Michigan
Palmyra Township, Michigan
Paradise Township, Michigan
Parchment, Michigan
Paris Township, Michigan
Park Township, Ottawa County, Michigan
Park Township, St. Joseph County, Michigan
Parma, Michigan
Parma Township, Michigan
Pavilion Township, Michigan
Paw Paw, Michigan
Paw Paw Township, Michigan
Peacock Township, Michigan
Peaine Township, Michigan
Peck, Michigan
Pellston, Michigan
Peninsula Township, Michigan
Penn Township, Michigan
Pennfield Charter Township, Michigan
Pentland Township, Michigan
Pentwater, Michigan
Pentwater Township, Michigan
Pere Marquette Charter Township, Michigan
Perrinton, Michigan
Perry, Michigan
Perry Township, Michigan
Petersburg, Michigan
Petoskey, Michigan
Pewamo, Michigan
Pickford Township, Michigan
Pierson, Michigan
Pierson Township, Michigan
Pigeon, Michigan
Pinckney, Michigan
Pinconning, Michigan
Pinconning Township, Michigan
Pine Township, Michigan
Pine Grove Township, Michigan
Pine River Township, Mich

Sterling, Michigan
Sterling Heights, Michigan
Stevensville, Michigan
Stockbridge, Michigan
Stockbridge Township, Michigan
Stronach Township, Michigan
Sturgis, Michigan
Sturgis Township, Michigan
Sugar Island Township, Michigan
Sullivan Township, Michigan
Summerfield Township, Clare County, Michigan
Summerfield Township, Monroe County, Michigan
Summit Township, Jackson County, Michigan
Summit Township, Mason County, Michigan
Sumner Township, Michigan
Sumpter Township, Michigan
Sunfield, Michigan
Sunfield Township, Michigan
Superior Township, Chippewa County, Michigan
Superior Township, Washtenaw County, Michigan
Surrey Township, Michigan
Suttons Bay, Michigan
Suttons Bay Township, Michigan
Swan Creek Township, Michigan
Swartz Creek, Michigan
Sweetwater Township, Michigan
Sylvan Township, Osceola County, Michigan
Sylvan Township, Washtenaw County, Michigan
Sylvan Lake, Michigan
Tallmadge Township, Michigan
Tawas Township, Michigan
Tawas City, Michigan
Taylor, Michigan
Taymouth Township, 

Fairmont, Minnesota
Hermantown, Minnesota
St. Anthony, Minnesota
Detroit Lakes, Minnesota
Arden Hills, Minnesota
Dayton, Minnesota
Waseca, Minnesota
Oak Grove, Minnesota
Little Falls, Minnesota
East Grand Forks, Minnesota
Mound, Minnesota
Baxter, Minnesota
Thief River Falls, Minnesota
Minnetrista, Minnesota
St. Francis, Minnesota
Waite Park, Minnesota
Virginia, Minnesota
New Prague, Minnesota
Orono, Minnesota
Albertville, Minnesota
Wyoming, Minnesota
Mahtomedi, Minnesota
Shorewood, Minnesota
Belle Plaine, Minnesota
Corcoran, Minnesota
Crookston, Minnesota
Isanti, Minnesota
St. Joseph, Minnesota
Spring Lake Park, Minnesota
Kasson, Minnesota
Delano, Minnesota
Medina, Minnesota
Stewartville, Minnesota
Jordan, Minnesota
Byron, Minnesota
Litchfield, Minnesota
Zimmerman, Minnesota
Carver, Minnesota
Glencoe, Minnesota
Chisago City, Minnesota
International Falls, Minnesota
Credit River, Minnesota
St. Paul Park, Minnesota
La Crescent, Minnesota
Princeton, Minnesota
Lake City, Minnesota
Montevid

Brewster, Minnesota
Sacred Heart, Minnesota
Brandon, Minnesota
Rothsay, Minnesota
Jenkins, Minnesota
Carlos, Minnesota
Kiester, Minnesota
Ellsworth, Minnesota
Pennock, Minnesota
Upsala, Minnesota
Lafayette, Minnesota
Ulen, Minnesota
Ashby, Minnesota
Stewart, Minnesota
Bethel, Minnesota
Clearbrook, Minnesota
Altura, Minnesota
Randolph, Minnesota
New Germany, Minnesota
Sturgeon Lake, Minnesota
Danube, Minnesota
Fifty Lakes, Minnesota
Wrenshall, Minnesota
Miltona, Minnesota
Wykoff, Minnesota
Vermillion, Minnesota
Lynd, Minnesota
Badger, Minnesota
Kellogg, Minnesota
Tower, Minnesota
Akeley, Minnesota
Milan, Minnesota
Fisher, Minnesota
New Auburn, Minnesota
Fountain, Minnesota
Oklee, Minnesota
Chokio, Minnesota
Bigfork, Minnesota
Waubun, Minnesota
Morton, Minnesota
Remer, Minnesota
Willow River, Minnesota
Rose Creek, Minnesota
Ogilvie, Minnesota
Erskine, Minnesota
Nevis, Minnesota
Herman, Minnesota
Hanska, Minnesota
McGregor, Minnesota
Woodland, Minnesota
Alvarado, Minnesota
Clinton, Minnes

Coldwater, Mississippi
Collins, Mississippi
Columbia, Mississippi
Columbus, Mississippi
Como, Mississippi
Corinth, Mississippi
Courtland, Mississippi
Crawford, Mississippi
Crenshaw, Mississippi
Crosby, Mississippi
Crowder, Mississippi
Cruger, Mississippi
Crystal Springs, Mississippi
Decatur, Mississippi
De Kalb, Mississippi
Derma, Mississippi
D'Iberville, Mississippi
D'Lo, Mississippi
Diamondhead, Mississippi
Doddsville, Mississippi
Drew, Mississippi
Duck Hill, Mississippi
Dumas, Mississippi
Duncan, Mississippi
Durant, Mississippi
Ecru, Mississippi
Eden, Mississippi
Edwards, Mississippi
Ellisville, Mississippi
Enterprise, Clarke County, Mississippi
Ethel, Mississippi
Eupora, Mississippi
Falcon, Mississippi
Falkner, Mississippi
Farmington, Mississippi
Fayette, Mississippi
Flora, Mississippi
Florence, Mississippi
Flowood, Mississippi
Forest, Mississippi
French Camp, Mississippi
Friars Point, Mississippi
Fulton, Mississippi
Gattman, Mississippi
Gautier, Mississippi
Georgetown, Mississippi

Canalou, Missouri
Canton, Missouri
Cape Girardeau, Missouri
Cardwell, Missouri
Carl Junction, Missouri
Carrollton, Missouri
Carterville, Missouri
Carthage, Missouri
Caruthersville, Missouri
Carytown, Missouri
Cassville, Missouri
Catron, Missouri
Cave, Missouri
Cedar Hill Lakes, Missouri
Center, Missouri
Centertown, Missouri
Centerview, Missouri
Centerville, Missouri
Centralia, Missouri
Chaffee, Missouri
Chain of Rocks, Missouri
Chain-O-Lakes, Missouri
Chamois, Missouri
Champ, Missouri
Charlack, Missouri
Charleston, Missouri
Chesterfield, Missouri
Chilhowee, Missouri
Chillicothe, Missouri
Chula, Missouri
Clarence, Missouri
Clark, Missouri
Clarksburg, Missouri
Clarksdale, Missouri
Clarkson Valley, Missouri
Clarksville, Missouri
Clarkton, Missouri
Claycomo, Missouri
Clayton, Missouri
Clearmont, Missouri
Cleveland, Missouri
Clever, Missouri
Cliff Village, Missouri
Clifton Hill, Missouri
Climax Springs, Missouri
Clinton, Missouri
Clyde, Missouri
Cobalt, Missouri
Coffey, Missouri
Cole Camp, 

McBaine, Missouri
McCord Bend, Missouri
McFall, Missouri
McKittrick, Missouri
Meadville, Missouri
Memphis, Missouri
Mendon, Missouri
Mercer, Missouri
Merriam Woods, Missouri
Merwin, Missouri
Meta, Missouri
Mexico, Missouri
Miami, Missouri
Middletown, Missouri
Milan, Missouri
Milford, Missouri
Mill Spring, Missouri
Millard, Missouri
Miller, Missouri
Milo, Missouri
Mindenmines, Missouri
Miner, Missouri
Mineral Point, Missouri
Miramiguoa Park, Missouri
Missouri City, Missouri
Moberly, Missouri
Mokane, Missouri
Moline Acres, Missouri
Monett, Missouri
Monroe City, Missouri
Montgomery City, Missouri
Monticello, Missouri
Montrose, Missouri
Mooresville, Missouri
Morehouse, Missouri
Morley, Missouri
Morrison, Missouri
Morrisville, Missouri
Mosby, Missouri
Moscow Mills, Missouri
Mound City, Missouri
Moundville, Missouri
Mount Leonard, Missouri
Mount Moriah, Missouri
Mount Vernon, Missouri
Mountain Grove, Missouri
Mountain View, Missouri
Napoleon, Missouri
Naylor, Missouri
Neck City, Missouri
Nee

Broadview, Montana
Browning, Montana
Butte, Montana
Cascade, Montana
Chester, Montana
Chinook, Montana
Choteau, Montana
Circle, Montana
Clyde Park, Montana
Colstrip, Montana
Columbia Falls, Montana
Columbus, Montana
Conrad, Montana
Culbertson, Montana
Cut Bank, Montana
Darby, Montana
Deer Lodge, Montana
Denton, Montana
Dillon, Montana
Dodson, Montana
Drummond, Montana
Dutton, Montana
East Helena, Montana
Ekalaka, Montana
Ennis, Montana
Eureka, Montana
Fairfield, Montana
Fairview, Montana
Flaxville, Montana
Forsyth, Montana
Fort Benton, Montana
Fort Peck, Montana
Froid, Montana
Fromberg, Montana
Geraldine, Montana
Glasgow, Montana
Glendive, Montana
Grass Range, Montana
Great Falls, Montana
Hamilton, Montana
Hardin, Montana
Harlem, Montana
Harlowton, Montana
Havre, Montana
Helena, Montana
Hingham, Montana
Hobson, Montana
Hot Springs, Montana
Hysham, Montana
Ismay, Montana
Joliet, Montana
Jordan, Montana
Judith Gap, Montana
Kalispell, Montana
Kevin, Montana
Laurel, Montana
Lavina, Montana

Trenton, New Jersey
Clifton, New Jersey
Cherry Hill, New Jersey
Brick Township, New Jersey
Camden, New Jersey
Bayonne, New Jersey
Passaic, New Jersey
East Orange, New Jersey
Union City, New Jersey
Franklin Township, Somerset County, New Jersey
Middletown Township, New Jersey
Old Bridge Township, New Jersey
Gloucester Township, New Jersey
North Bergen, New Jersey
Irvington, New Jersey
Piscataway, New Jersey
Vineland, New Jersey
Hoboken, New Jersey
Union Township, Union County, New Jersey
Jackson Township, New Jersey
Parsippany–Troy Hills, New Jersey
Perth Amboy, New Jersey
New Brunswick, New Jersey
Wayne, New Jersey
Plainfield, New Jersey
Howell Township, New Jersey
Bloomfield, New Jersey
West New York, New Jersey
East Brunswick, New Jersey
West Orange, New Jersey
Washington Township, Gloucester County, New Jersey
Monroe Township, Middlesex County, New Jersey
Egg Harbor Township, New Jersey
South Brunswick, New Jersey
Evesham Township, New Jersey
Hackensack, New Jersey
Bridgewater Towns

Allendale, New Jersey
Tabernacle Township, New Jersey
North Caldwell, New Jersey
Rockaway, New Jersey
Union Township, Hunterdon County, New Jersey
Washington Township, Warren County, New Jersey
Shamong Township, New Jersey
Watchung, New Jersey
Carlstadt, New Jersey
Prospect Park, New Jersey
New Hanover Township, New Jersey
Roseland, New Jersey
Dennis Township, New Jersey
Fair Haven, New Jersey
Maurice River Township, New Jersey
Paulsboro, New Jersey
Lebanon Township, New Jersey
Eastampton Township, New Jersey
Morris Plains, New Jersey
Oceanport, New Jersey
Little Silver, New Jersey
Woodcliff Lake, New Jersey
Hainesport Township, New Jersey
Mendham Township, New Jersey
Logan Township, New Jersey
Andover Township, New Jersey
Manasquan, New Jersey
Mount Arlington, New Jersey
Belmar, New Jersey
Hightstown, New Jersey
Old Tappan, New Jersey
Tewksbury Township, New Jersey
Berlin Township, New Jersey
Mullica Township, New Jersey
Rochelle Park, New Jersey
Jamesburg, New Jersey
Union Beach, New

San Jon, New Mexico
San Ysidro, New Mexico
Santa Clara, New Mexico
Santa Fe, New Mexico
Santa Rosa, New Mexico
Silver City, New Mexico
Socorro, New Mexico
Springer, New Mexico
Sunland Park, New Mexico
Taos, New Mexico
Taos Ski Valley, New Mexico
Tatum, New Mexico
Texico, New Mexico
Tijeras, New Mexico
Truth or Consequences, New Mexico
Tucumcari, New Mexico
Tularosa, New Mexico
Vaughn, New Mexico
Virden, New Mexico
Wagon Mound, New Mexico
Willard, New Mexico
Williamsburg, New Mexico
Population
Square mile
Adams (village), New York
Addison (village), New York
Afton (village), New York
Airmont, New York
Akron, New York
Albany, New York
Albion (village), New York
Alden (village), New York
Alexander (village), New York
Alexandria Bay, New York
Alfred (village), New York
Allegany (village), New York
Almond (village), New York
Altamont, New York
Ames, New York
Amityville, New York
Amsterdam (city), New York
Andover (village), New York
Angelica (village), New York
Angola, New York
Antwerp (vil

McGraw, New York
Mechanicville, New York
Medina, New York
Menands, New York
Meridian, New York
Mexico (village), New York
Middleburgh (village), New York
Middleport, New York
Middletown, Orange County, New York
Middleville, New York
Milford (village), New York
Mill Neck, New York
Millbrook, New York
Millerton, New York
Millport, New York
Mineola, New York
Minoa, New York
Mohawk, Herkimer County, New York
Monroe (village), New York
Montebello, New York
Montgomery (village), New York
Monticello, New York
Montour Falls, New York
Moravia (village), New York
Morris (village), New York
Morrisville, New York
Mount Kisco, New York
Mount Morris (village), New York
Mount Vernon, New York
Munnsville, New York
Munsey Park, New York
Muttontown, New York
Naples (village), New York
Nassau (village), New York
Nelliston, New York
Nelsonville, New York
New Berlin (village), New York
New Hartford (village), New York
New Hempstead, New York
New Hyde Park, New York
New Paltz (village), New York
New Rochell

Smithtown (CDP), New York
Westport, New York
Woodhull, New York
Charlotte, North Carolina
Raleigh, North Carolina
Greensboro, North Carolina
Durham, North Carolina
Winston-Salem, North Carolina
Fayetteville, North Carolina
Cary, North Carolina
Wilmington, North Carolina
High Point, North Carolina
Concord, North Carolina
Asheville, North Carolina
Greenville, North Carolina
Gastonia, North Carolina
Jacksonville, North Carolina
Apex, North Carolina
Huntersville, North Carolina
Chapel Hill, North Carolina
Burlington, North Carolina
Kannapolis, North Carolina
Rocky Mount, North Carolina
Mooresville, North Carolina
Wake Forest, North Carolina
Wilson, North Carolina
Hickory, North Carolina
Holly Springs, North Carolina
Indian Trail, North Carolina
Fuquay-Varina, North Carolina
Salisbury, North Carolina
Monroe, North Carolina
Goldsboro, North Carolina
Garner, North Carolina
Cornelius, North Carolina
New Bern, North Carolina
Morrisville, North Carolina
Sanford, North Carolina
Matthews, North Ca

Clifford, North Dakota
Egeland, North Dakota
Fortuna, North Dakota
Alsen, North Dakota
Monango, North Dakota
Nekoma, North Dakota
Springbrook, North Dakota
Hampden, North Dakota
Brinsmade, North Dakota
Fairdale, North Dakota
Luverne, North Dakota
Leith, North Dakota
Kramer, North Dakota
Amidon, North Dakota
Leal, North Dakota
Gardena, North Dakota
Antler, North Dakota
Cathay, North Dakota
Elliott, North Dakota
Gascoyne, North Dakota
Knox, North Dakota
Mylo, North Dakota
Sibley, North Dakota
Venturia, North Dakota
Ambrose, North Dakota
Braddock, North Dakota
Ludden, North Dakota
Lawton, North Dakota
Balfour, North Dakota
Bucyrus, North Dakota
Hansboro, North Dakota
Haynes, North Dakota
Sarles, North Dakota
York, North Dakota
Conway, North Dakota
Calvin, North Dakota
Ayr, North Dakota
Bergen, North Dakota
Hamberg, North Dakota
Pillsbury, North Dakota
Churchs Ferry, North Dakota
Overly, North Dakota
Grano, North Dakota
Loma, North Dakota
Wales, North Dakota
Loraine, North Dakota
Hannah, N

Fayetteville, Ohio
Felicity, Ohio
Fletcher, Ohio
Florida, Ohio
Flushing, Ohio
Forest, Ohio
Fort Jennings, Ohio
Fort Loramie, Ohio
Fort Recovery, Ohio
Frankfort, Ohio
Frazeysburg, Ohio
Fredericksburg, Ohio
Fredericktown, Ohio
Freeport, Ohio
Fulton, Ohio
Fultonham, Ohio
Galena, Ohio
Gallipolis, Ohio
Gambier, Ohio
Gann, Ohio
Garrettsville, Ohio
Gates Mills, Ohio
Geneva-on-the-Lake, Ohio
Genoa, Ohio
Georgetown, Ohio
Gettysburg, Ohio
Gibsonburg, Ohio
Gilboa, Ohio
Glandorf, Ohio
Glendale, Ohio
Glenford, Ohio
Glenmont, Ohio
Glenwillow, Ohio
Gloria Glens Park, Ohio
Glouster, Ohio
Gnadenhutten, Ohio
Golf Manor, Ohio
Gordon, Ohio
Grafton, Ohio
Grand Rapids, Ohio
Grand River, Ohio
Granville, Ohio
Gratiot, Ohio
Gratis, Ohio
Graysville, Ohio
Green Camp, Ohio
Green Springs, Ohio
Greenfield, Ohio
Greenhills, Ohio
Greenwich, Ohio
Grover Hill, Ohio
Hamden, Ohio
Hamersville, Ohio
Hamler, Ohio
Hanging Rock, Ohio
Hanover, Ohio
Hanoverton, Ohio
Harbor View, Ohio
Harpster, Ohio
Harrisburg, Ohio
Harrisville,

Oklahoma City
Tulsa, Oklahoma
Norman, Oklahoma
Broken Arrow, Oklahoma
Edmond, Oklahoma
Lawton, Oklahoma
Moore, Oklahoma
Midwest City, Oklahoma
Enid, Oklahoma
Stillwater, Oklahoma
Owasso, Oklahoma
Bartlesville, Oklahoma
Muskogee, Oklahoma
Shawnee, Oklahoma
Bixby, Oklahoma
Jenks, Oklahoma
Ardmore, Oklahoma
Ponca City, Oklahoma
Yukon, Oklahoma
Duncan, Oklahoma
Sapulpa, Oklahoma
Del City, Oklahoma
Bethany, Oklahoma
Mustang, Oklahoma
Sand Springs, Oklahoma
Claremore, Oklahoma
Altus, Oklahoma
Durant, Oklahoma
McAlester, Oklahoma
El Reno, Oklahoma
Ada, Oklahoma
Tahlequah, Oklahoma
Chickasha, Oklahoma
Glenpool, Oklahoma
Miami, Oklahoma
Guymon, Oklahoma
Choctaw, Oklahoma
Woodward, Oklahoma
Weatherford, Oklahoma
Elk City, Oklahoma
Okmulgee, Oklahoma
Newcastle, Oklahoma
Guthrie, Oklahoma
Warr Acres, Oklahoma
Coweta, Oklahoma
The Village, Oklahoma
Pryor Creek, Oklahoma
Blanchard, Oklahoma
Poteau, Oklahoma
Clinton, Oklahoma
Sallisaw, Oklahoma
Skiatook, Oklahoma
Cushing, Oklahoma
Collinsville, Oklah

Swatara Township, Dauphin County, Pennsylvania
Warrington Township, Bucks County, Pennsylvania
Marple Township, Delaware County, Pennsylvania
New Castle, Pennsylvania
West Goshen Township, Chester County, Pennsylvania
Unity Township, Westmoreland County, Pennsylvania
Pottstown, Pennsylvania
Peters Township, Washington County, Pennsylvania
Upper Providence Township, Montgomery County, Pennsylvania
Upper Macungie Township, Lehigh County, Pennsylvania
Dover Township, York County, Pennsylvania
East Pennsboro Township, Cumberland County, Pennsylvania
Palmer Township, Northampton County, Pennsylvania
Johnstown, Pennsylvania
Coolbaugh Township, Monroe County, Pennsylvania
Chambersburg, Pennsylvania
Buckingham Township, Bucks County, Pennsylvania
West Mifflin, Pennsylvania
Murrysville, Pennsylvania
Manor Township, Lancaster County, Pennsylvania
Penn Township, Westmoreland County, Pennsylvania
Muhlenberg Township, Berks County, Pennsylvania
Baldwin, Pennsylvania
McKeesport, Pennsylvania
South W

Ephrata Township, Lancaster County, Pennsylvania
Plains Township, Luzerne County, Pennsylvania
Northampton, Pennsylvania
Milford Township, Bucks County, Pennsylvania
East Stroudsburg, Pennsylvania
Sunbury, Pennsylvania
Lock Haven, Pennsylvania
Penn Forest Township, Carbon County, Pennsylvania
Bristol, Pennsylvania
Brentwood, Pennsylvania
Hazle Township, Luzerne County, Pennsylvania
South Lebanon Township, Lebanon County, Pennsylvania
West Hanover Township, Dauphin County, Pennsylvania
Jeannette, Pennsylvania
Warren, Pennsylvania
College Township, Centre County, Pennsylvania
South Strabane Township, Washington County, Pennsylvania
Neshannock Township, Lawrence County, Pennsylvania
Lititz, Pennsylvania
Butler Township, Luzerne County, Pennsylvania
Aliquippa, Pennsylvania
Darby Township, Delaware County, Pennsylvania
Maidencreek Township, Berks County, Pennsylvania
Moore Township, Northampton County, Pennsylvania
Perkiomen Township, Montgomery County, Pennsylvania
South Abington Township,

Dickson City, Pennsylvania
Carroll Township, York County, Pennsylvania
Cambria Township, Cambria County, Pennsylvania
Hellam Township, York County, Pennsylvania
New Brighton, Pennsylvania
Luzerne Township, Fayette County, Pennsylvania
Steelton, Pennsylvania
Crafton, Pennsylvania
Sewickley Township, Westmoreland County, Pennsylvania
St. Thomas Township, Pennsylvania
Plymouth, Pennsylvania
Williams Township, Northampton County, Pennsylvania
Punxsutawney, Pennsylvania
Greenville, Pennsylvania
Monroe Township, Cumberland County, Pennsylvania
Norwood, Pennsylvania
Adams Township, Cambria County, Pennsylvania
Ross Township, Monroe County, Pennsylvania
Hellertown, Pennsylvania
Mount Carmel, Pennsylvania
East Hanover Township, Dauphin County, Pennsylvania
Hollidaysburg, Pennsylvania
Reading Township, Adams County, Pennsylvania
New London Township, Chester County, Pennsylvania
Lewisburg, Pennsylvania
Union Township, Washington County, Pennsylvania
Monaca, Pennsylvania
Moosic, Pennsylvania
South

Sellersville, Pennsylvania
Franklin Township, Carbon County, Pennsylvania
Manor Township, Armstrong County, Pennsylvania
Sugarloaf Township, Luzerne County, Pennsylvania
Birmingham Township, Chester County, Pennsylvania
Strasburg Township, Lancaster County, Pennsylvania
Mahoning Township, Montour County, Pennsylvania
West Reading, Pennsylvania
Forty Fort, Pennsylvania
Menallen Township, Fayette County, Pennsylvania
Salem Township, Wayne County, Pennsylvania
Cornwall, Pennsylvania
Barrett Township, Pennsylvania
Greenfield Township, Blair County, Pennsylvania
Upper Paxton Township, Dauphin County, Pennsylvania
Little Britain Township, Lancaster County, Pennsylvania
Aldan, Pennsylvania
Connoquenessing Township, Butler County, Pennsylvania
Pine Grove Township, Schuylkill County, Pennsylvania
Ruscombmanor Township, Berks County, Pennsylvania
Heidelberg Township, Lebanon County, Pennsylvania
Bethel Township, Berks County, Pennsylvania
Waynesburg, Pennsylvania
Mahanoy City, Pennsylvania
Baden

Fulton Township, Lancaster County, Pennsylvania
Fawn Township, York County, Pennsylvania
Edgewood, Allegheny County, Pennsylvania
Macungie, Pennsylvania
Myerstown, Pennsylvania
Lower Mount Bethel Township, Northampton County, Pennsylvania
Thornbury Township, Chester County, Pennsylvania
Girard, Pennsylvania
Heidelberg Township, York County, Pennsylvania
Orwigsburg, Pennsylvania
Wormleysburg, Pennsylvania
Wrightstown Township, Bucks County, Pennsylvania
Wyoming, Pennsylvania
Lower Chanceford Township, York County, Pennsylvania
Raccoon Township, Beaver County, Pennsylvania
Nottingham Township, Washington County, Pennsylvania
Mohnton, Pennsylvania
McSherrystown, Pennsylvania
Malvern, Pennsylvania
Mahoning Township, Lawrence County, Pennsylvania
Bradford Township, Clearfield County, Pennsylvania
Wolf Township, Lycoming County, Pennsylvania
Lake City, Pennsylvania
Briar Creek Township, Pennsylvania
Springfield Township, Fayette County, Pennsylvania
Youngwood, Pennsylvania
Washington Townshi

Eddystone, Pennsylvania
Gregg Township, Centre County, Pennsylvania
Coopersburg, Pennsylvania
Marcus Hook, Pennsylvania
Woodward Township, Clinton County, Pennsylvania
Donegal Township, Westmoreland County, Pennsylvania
Red Hill, Pennsylvania
Greene Township, Beaver County, Pennsylvania
Highspire, Pennsylvania
Clifford Township, Susquehanna County, Pennsylvania
Berwick Township, Pennsylvania
Cornplanter Township, Venango County, Pennsylvania
Alburtis, Pennsylvania
Brothersvalley Township, Somerset County, Pennsylvania
Exeter Township, Luzerne County, Pennsylvania
Fawn Township, Allegheny County, Pennsylvania
Hamiltonban Township, Adams County, Pennsylvania
Huntington Township, Adams County, Pennsylvania
Connellsville Township, Fayette County, Pennsylvania
Hopewell Township, Cumberland County, Pennsylvania
Watsontown, Pennsylvania
Loyalhanna Township, Westmoreland County, Pennsylvania
Dunkard Township, Greene County, Pennsylvania
Plumcreek Township, Armstrong County, Pennsylvania
Rye To

Rayburn Township, Armstrong County, Pennsylvania
Braddock Hills, Pennsylvania
Washington Township, Clarion County, Pennsylvania
Cherry Ridge Township, Wayne County, Pennsylvania
Donegal Township, Butler County, Pennsylvania
Forest City, Pennsylvania
Tullytown, Pennsylvania
Metal Township, Pennsylvania
Jefferson Township, Mercer County, Pennsylvania
Port Carbon, Pennsylvania
Zerbe Township, Northumberland County, Pennsylvania
Brokenstraw Township, Warren County, Pennsylvania
East Providence Township, Bedford County, Pennsylvania
Limestone Township, Clarion County, Pennsylvania
Oil Creek Township, Crawford County, Pennsylvania
Brush Valley Township, Indiana County, Pennsylvania
Trainer, Pennsylvania
Londonderry Township, Bedford County, Pennsylvania
West Franklin Township, Armstrong County, Pennsylvania
Upper Fairfield Township, Lycoming County, Pennsylvania
Jacobus, Pennsylvania
Elkland, Pennsylvania
East Nantmeal Township, Chester County, Pennsylvania
Lehigh Township, Wayne County, Pen

New Beaver, Pennsylvania
East Mead Township, Crawford County, Pennsylvania
Perry Township, Greene County, Pennsylvania
Windsor, Pennsylvania
Elk Township, Clarion County, Pennsylvania
Lewis Township, Union County, Pennsylvania
Clarks Green, Pennsylvania
Sullivan Township, Tioga County, Pennsylvania
North Union Township, Schuylkill County, Pennsylvania
West Bethlehem Township, Washington County, Pennsylvania
Oakdale, Pennsylvania
Richmond Township, Crawford County, Pennsylvania
Conyngham Township, Luzerne County, Pennsylvania
Conneaut Township, Crawford County, Pennsylvania
Belfast Township, Fulton County, Pennsylvania
Horton Township, Elk County, Pennsylvania
Langhorne Manor, Pennsylvania
Rockland Township, Venango County, Pennsylvania
Blawnox, Pennsylvania
Greenwood Township, Crawford County, Pennsylvania
Wilmington Township, Mercer County, Pennsylvania
Perry Township, Mercer County, Pennsylvania
Kline Township, Schuylkill County, Pennsylvania
Sterling Township, Wayne County, Pennsylv

Sykesville, Pennsylvania
Knox, Pennsylvania
Tatamy, Pennsylvania
Durham Township, Bucks County, Pennsylvania
Tuscarora Township, Bradford County, Pennsylvania
Derry Township, Montour County, Pennsylvania
North Towanda Township, Bradford County, Pennsylvania
Dennison Township, Luzerne County, Pennsylvania
Shinglehouse, Pennsylvania
Carbondale Township, Lackawanna County, Pennsylvania
Osceola Mills, Pennsylvania
Rush Township, Northumberland County, Pennsylvania
South Creek Township, Bradford County, Pennsylvania
Springfield Township, Bradford County, Pennsylvania
Cochranton, Pennsylvania
Schuylkill Township, Schuylkill County, Pennsylvania
White Haven, Pennsylvania
Limestone Township, Montour County, Pennsylvania
Ashland Township, Pennsylvania
Lower Tyrone Township, Fayette County, Pennsylvania
Milesburg, Pennsylvania
Williams Township, Dauphin County, Pennsylvania
Slocum Township, Luzerne County, Pennsylvania
Juniata Township, Blair County, Pennsylvania
Cass Township, Huntingdon County

West Middlesex, Pennsylvania
Spruce Hill Township, Juniata County, Pennsylvania
East Norwegian Township, Schuylkill County, Pennsylvania
Hubley Township, Schuylkill County, Pennsylvania
Union Township, Jefferson County, Pennsylvania
New Milford, Pennsylvania
Clinton Township, Venango County, Pennsylvania
Oil Creek Township, Venango County, Pennsylvania
Carrolltown, Pennsylvania
Beale Township, Pennsylvania
Halifax, Pennsylvania
Parker, Pennsylvania
Jackson Township, Susquehanna County, Pennsylvania
North Irwin, Pennsylvania
Spring Creek Township, Warren County, Pennsylvania
Shickshinny, Pennsylvania
Wolf Creek Township, Mercer County, Pennsylvania
Windham Township, Wyoming County, Pennsylvania
Lathrop Township, Susquehanna County, Pennsylvania
York Springs, Pennsylvania
Freedom Township, Adams County, Pennsylvania
Wells Township, Bradford County, Pennsylvania
Worth Township, Centre County, Pennsylvania
White Township, Cambria County, Pennsylvania
Eldred, Pennsylvania
Claysville, Pennsy

Connoquenessing, Pennsylvania
Scott Township, Wayne County, Pennsylvania
Wall, Pennsylvania
Elkland Township, Sullivan County, Pennsylvania
Norwich Township, McKean County, Pennsylvania
Davidson Township, Sullivan County, Pennsylvania
Meshoppen, Pennsylvania
West Township, Huntingdon County, Pennsylvania
Valencia, Pennsylvania
Freeburg, Pennsylvania
Austin, Pennsylvania
East Rochester, Pennsylvania
Bastress Township, Lycoming County, Pennsylvania
Potter Township, Beaver County, Pennsylvania
New Alexandria, Pennsylvania
Ararat Township, Susquehanna County, Pennsylvania
Gaines Township, Tioga County, Pennsylvania
Oakland Township, Susquehanna County, Pennsylvania
Juniata Township, Huntingdon County, Pennsylvania
Monroe, Pennsylvania
Watson Township, Lycoming County, Pennsylvania
West Cameron Township, Northumberland County, Pennsylvania
Hickory Township, Forest County, Pennsylvania
Juniata Terrace, Pennsylvania
Dayton, Pennsylvania
Strattanville, Pennsylvania
Glen Osborne, Pennsylvania
L

Shrewsbury Township, Sullivan County, Pennsylvania
Youngstown, Pennsylvania
Daisytown, Pennsylvania
Kistler, Pennsylvania
Herndon, Pennsylvania
Elco, Pennsylvania
Townville, Pennsylvania
Franklin, Cambria County, Pennsylvania
Laporte, Pennsylvania
Keating Township, Potter County, Pennsylvania
East Side, Pennsylvania
Wallaceton, Pennsylvania
Eau Claire, Pennsylvania
Triumph Township, Warren County, Pennsylvania
Penn Lake Park, Pennsylvania
Creekside, Pennsylvania
Freeport Township, Greene County, Pennsylvania
Applewold, Pennsylvania
Plumville, Pennsylvania
Porter Township, Jefferson County, Pennsylvania
Pillow, Pennsylvania
Enon Valley, Pennsylvania
Spartansburg, Pennsylvania
Manns Choice, Pennsylvania
Pine Township, Lycoming County, Pennsylvania
Thompson, Pennsylvania
Hillsgrove Township, Sullivan County, Pennsylvania
Le Raysville, Pennsylvania
Unionville, Centre County, Pennsylvania
Hunker, Pennsylvania
Pavia Township, Bedford County, Pennsylvania
Hartleton, Pennsylvania
Markleysburg,

Bishopville, South Carolina
Blacksburg, South Carolina
Blackville, South Carolina
Blenheim, South Carolina
Bluffton, South Carolina
Blythewood, South Carolina
Bonneau, South Carolina
Bowman, South Carolina
Branchville, South Carolina
Briarcliffe Acres, South Carolina
Brunson, South Carolina
Burnettown, South Carolina
Calhoun Falls, South Carolina
Camden, South Carolina
Cameron, South Carolina
Campobello, South Carolina
Carlisle, South Carolina
Cayce, South Carolina
Central, South Carolina
Central Pacolet, South Carolina
Chapin, South Carolina
Charleston, South Carolina
Cheraw, South Carolina
Chesnee, South Carolina
Chester, South Carolina
Chesterfield, South Carolina
Clemson, South Carolina
Clinton, South Carolina
Clio, South Carolina
Clover, South Carolina
Columbia, South Carolina
Conway, South Carolina
Cope, South Carolina
Cordova, South Carolina
Cottageville, South Carolina
Coward, South Carolina
Cowpens, South Carolina
Cross Hill, South Carolina
Darlington, South Carolina
Denmark, 

Marion, South Dakota
Howard, South Dakota
Faulkton, South Dakota
Viborg, South Dakota
Eureka, South Dakota
Scotland, South Dakota
Alcester, South Dakota
Plankinton, South Dakota
Elkton, South Dakota
Edgemont, South Dakota
Wessington Springs, South Dakota
Estelline, South Dakota
Philip, South Dakota
Colton, South Dakota
Castlewood, South Dakota
Wall, South Dakota
Armour, South Dakota
Lake Andes, South Dakota
Woonsocket, South Dakota
Onida, South Dakota
Alexandria, South Dakota
Colman, South Dakota
Canistota, South Dakota
Highmore, South Dakota
Menno, South Dakota
New Underwood, South Dakota
Selby, South Dakota
Lake Preston, South Dakota
Newell, South Dakota
Humboldt, South Dakota
Lake Norden, South Dakota
Avon, South Dakota
Burke, South Dakota
Kimball, South Dakota
Tripp, South Dakota
McLaughlin, South Dakota
Corsica, South Dakota
Kadoka, South Dakota
White, South Dakota
White River, South Dakota
Bridgewater, South Dakota
Timber Lake, South Dakota
Dupree, South Dakota
Emery, South Dakot

Hartsville, Tennessee
Henderson, Tennessee
Hendersonville, Tennessee
Henning, Tennessee
Henry, Tennessee
Hickory Valley, Tennessee
Hohenwald, Tennessee
Hollow Rock, Tennessee
Hornbeak, Tennessee
Hornsby, Tennessee
Humboldt, Tennessee
Huntingdon, Tennessee
Huntland, Tennessee
Huntsville, Tennessee
Jacksboro, Tennessee
Jackson, Tennessee
Jamestown, Tennessee
Jasper, Tennessee
Jefferson City, Tennessee
Jellico, Tennessee
Johnson City, Tennessee
Jonesborough, Tennessee
Kenton, Tennessee
Kimball, Tennessee
Kingsport, Tennessee
Kingston, Tennessee
Kingston Springs, Tennessee
Knoxville, Tennessee
Lafayette, Tennessee
LaFollette, Tennessee
La Grange, Tennessee
Lakeland, Tennessee
Lakesite, Tennessee
La Vergne, Tennessee
Lawrenceburg, Tennessee
Lebanon, Tennessee
Lenoir City, Tennessee
Lewisburg, Tennessee
Lexington, Tennessee
Liberty, Tennessee
Linden, Tennessee
Livingston, Tennessee
Lobelville, Tennessee
Lookout Mountain, Tennessee
Loretto, Tennessee
Loudon, Tennessee
Louisville, Tennessee
Lu

Pecos, Texas
Fair Oaks Ranch, Texas
Burkburnett, Texas
Pleasanton, Texas
Fairview, Texas
Bonham, Texas
Heath, Texas
Rockport, Texas
Clute, Texas
Bellmead, Texas
Freeport, Texas
Sweetwater, Texas
Galena Park, Texas
Robstown, Texas
Raymondville, Texas
San Elizario, Texas
Ingleside, Texas
Roanoke, Texas
Vernon, Texas
Sanger, Texas
Lago Vista, Texas
Vidor, Texas
Helotes, Texas
Woodway, Texas
Bridge City, Texas
Dayton, Texas
Kennedale, Texas
Jacinto City, Texas
Commerce, Texas
Whitehouse, Texas
Liberty Hill, Texas
Mont Belvieu, Texas
Pearsall, Texas
Bee Cave, Texas
Northlake, Texas
Aransas Pass, Texas
Graham, Texas
Wharton, Texas
Highland Park, Texas
Brownfield, Texas
Joshua, Texas
Hondo, Texas
Liberty, Texas
Hillsboro, Texas
Cleveland, Texas
Lucas, Texas
Providence Village, Texas
Lamesa, Texas
Prairie View, Texas
Navasota, Texas
Richland Hills, Texas
Dalhart, Texas
Sunnyvale, Texas
Kaufman, Texas
Los Fresnos, Texas
Fort Stockton, Texas
Perryton, Texas
Cuero, Texas
Kirby, Texas
Floresville,

Menard, Texas
Emory, Texas
Thorndale, Texas
Wallis, Texas
Booker, Texas
Brackettville, Texas
Nevada, Texas
Rosebud, Texas
Plains, Texas
Rotan, Texas
Old River-Winfree, Texas
Natalia, Texas
Big Sandy, Texas
Valley Mills, Texas
Sundown, Texas
Lexington, Texas
China, Texas
Woodsboro, Texas
Brownsboro, Texas
Clear Lake Shores, Texas
Kemp, Texas
Elkhart, Texas
Point Venture, Texas
Gholson, Texas
Roscoe, Texas
Rice, Texas
Tioga, Texas
Kempner, Texas
La Vernia, Texas
Martindale, Texas
Lakeside City, Texas
Munday, Texas
La Grulla, Texas
Blue Ridge, Texas
Oyster Creek, Texas
Claude, Texas
Tye, Texas
Florence, Texas
Newark, Texas
Von Ormy, Texas
Cut and Shoot, Texas
Granger, Texas
Orange Grove, Texas
LaCoste, Texas
Rio Vista, Texas
Ransom Canyon, Texas
Pine Island, Texas
Benavides, Texas
Ore City, Texas
Sterling City, Texas
Eustace, Texas
China Grove, Texas
Oak Ridge, Kaufman County, Texas
Rogers, Texas
Holland, Texas
Frankston, Texas
Gruver, Texas
Tiki Island, Texas
Lindsay, Cooke County, Texas

Sun Valley, Texas
Seven Oaks, Texas
Pyote, Texas
Valentine, Texas
Neylandville, Texas
Putnam, Texas
Dorchester, Texas
Lakeview, Texas
Toyah, Texas
Dayton Lakes, Texas
Spofford, Texas
Draper, Texas
Quintana, Texas
Impact, Texas
Los Ybanez, Texas
Mustang, Texas
Alpine, Utah
Alta, Utah
Altamont, Utah
Alton, Utah
Amalga, Utah
American Fork, Utah
Annabella, Utah
Antimony, Utah
Apple Valley, Utah
Aurora, Utah
Ballard, Utah
Bear River City, Utah
Beaver, Utah
Bicknell, Utah
Big Water, Utah
Blanding, Utah
Bluff, Utah
Bluffdale, Utah
Boulder, Utah
Bountiful, Utah
Brian Head, Utah
Brigham City, Utah
Brighton, Utah
Bryce Canyon City, Utah
Cannonville, Utah
Castle Dale, Utah
Castle Valley, Utah
Cedar City, Utah
Cedar Fort, Utah
Cedar Hills, Utah
Centerfield, Utah
Centerville, Utah
Central Valley, Utah
Charleston, Utah
Circleville, Utah
Clarkston, Utah
Clawson, Utah
Clearfield, Utah
Cleveland, Utah
Clinton, Utah
Coalville, Utah
Copperton, Utah
Corinne, Utah
Cornish, Utah
Cottonwood Heights, Utah
Dan

Washington, Vermont
Waterbury, Vermont
Waterford, Vermont
Waterville, Vermont
Weathersfield, Vermont
Wells, Vermont
West Fairlee, Vermont
West Haven, Vermont
West Rutland, Vermont
West Windsor, Vermont
Westfield, Vermont
Westford, Vermont
Westminster, Vermont
Westmore, Vermont
Weston, Vermont
Weybridge, Vermont
Wheelock, Vermont
Whiting, Vermont
Whitingham, Vermont
Williamstown, Vermont
Williston, Vermont
Wilmington, Vermont
Windham, Vermont
Windsor, Vermont
Winhall, Vermont
Wolcott, Vermont
Woodbury, Vermont
Woodford, Vermont
Woodstock, Vermont
Worcester, Vermont
Middlebury (village), Vermont
Montpelier, Vermont
Brattleboro (village), Vermont
Windsor (village), Vermont
Bellows Falls (village), Vermont
Woodstock (village), Vermont
Rutland (city), Vermont
Castleton (village), Vermont
Bennington (village), Vermont
St. Johnsbury (village), Vermont
Northfield (village), Vermont
Wilmington (village), Vermont
St. Albans (city), Vermont
Newport (city), Vermont
Fair Haven (village), Vermont
Ca

Long Beach, Washington
Longview, Washington
Lynden, Washington
Lynnwood, Washington
Mabton, Washington
Maple Valley, Washington
Marysville, Washington
Mattawa, Washington
McCleary, Washington
Medical Lake, Washington
Medina, Washington
Mercer Island, Washington
Mesa, Washington
Mill Creek, Washington
Millwood, Washington
Milton, Washington
Monroe, Washington
Montesano, Washington
Morton, Washington
Moses Lake, Washington
Mossyrock, Washington
Mount Vernon, Washington
Mountlake Terrace, Washington
Moxee, Washington
Mukilteo, Washington
Napavine, Washington
Newcastle, Washington
Newport, Washington
Nooksack, Washington
Normandy Park, Washington
North Bend, Washington
North Bonneville, Washington
Oak Harbor, Washington
Oakville, Washington
Ocean Shores, Washington
Okanogan, Washington
Olympia, Washington
Omak, Washington
Oroville, Washington
Orting, Washington
Othello, Washington
Pacific, Washington
Palouse, Washington
Pasco, Washington
Pateros, Washington
Pomeroy, Washington
Port Angeles

Fairview, West Virginia
Lost Creek, West Virginia
Windsor Heights, West Virginia
Pine Grove, West Virginia
Whitesville, West Virginia
Lester, West Virginia
Gilbert, West Virginia
Meadow Bridge, West Virginia
Mitchell Heights, West Virginia
Tunnelton, West Virginia
Flemington, West Virginia
Kermit, West Virginia
Hedgesville, West Virginia
Bramwell, West Virginia
Newburg, West Virginia
Iaeger, West Virginia
Valley Grove, West Virginia
Harpers Ferry, West Virginia
Wardensville, West Virginia
Albright, West Virginia
Flatwoods, West Virginia
Hundred, West Virginia
Durbin, West Virginia
Northfork, West Virginia
Ellenboro, West Virginia
Hillsboro, West Virginia
Henderson, West Virginia
Davy, West Virginia
Hendricks, West Virginia
Handley, West Virginia
Bradshaw, West Virginia
Quinwood, West Virginia
Hambleton, West Virginia
Elk Garden, West Virginia
Bayard, West Virginia
Womelsdorf (Coalton), West Virginia
Keystone, West Virginia
Worthington, West Virginia
Sand Fork, West Virginia
Anawalt, We

In [138]:
revids = []
preds = []

for i in range(0, len(score_list)):
    revid = str(titles_revids_df['revid'][i])
    if list(score_list[i])[0]=='enwiki':
        pred = score_list[i]['enwiki']['scores'][revid]['articlequality']['score']['prediction']
    else:
        pred = None # if unable to get score for this article
    revids.append(revid)
    preds.append(pred)

In [139]:
# save revid and predictions in df
revids_preds_df = pd.DataFrame({'revid':revids,'prediction':preds})

# View df
revids_preds_df.head()

revid prediction
0  1171163550          C
1  1177621427          C
2  1168359898          C
3  1165909508         GA
4  1179139816          C

Now, we will create two new dataframes from this data. The first dataframe, *revids_preds_scores_df*, is filtered to only include articles for which we were able to receive an ORES score. The second dataframe, *revids_preds_noscores_df*, is filtered to only include articles for which we were not able to receive an ORES score.

In [142]:
# Df for articles with ORES Score
revids_preds_scores_df = revids_preds_df.dropna().reset_index(drop=True)
len(revids_preds_scores_df)

16231

In [153]:
revids_preds_scores_df.head()

revid prediction
0  1171163550          C
1  1177621427          C
2  1168359898          C
3  1165909508         GA
4  1179139816          C

In [150]:
# Df for articles without ORES Score
revids_preds_noscores_df = revids_preds_df[revids_preds_df['prediction'].isnull()].reset_index(drop=True)
len(revids_preds_noscores_df)

5294

In [152]:
revids_preds_noscores_df.head()

revid prediction
0  1166229686       None
1  1174673505       None
2  1174673519       None
3  1172669651       None
4  1178675089       None

As shown above, I was not able to receive an ORES score for almost 5,300 articles. This is because, some of the articles could not receive an ORES score due to the following error: *Max retries exceeded with URL in requests in Python*. I obtain a list of these articles, and re-run them through the same code I wrote earlier to utilize the ORES API.

In [234]:
# Save dataframe to csv file on local device
revids_preds_noscores_df.to_csv('revids_preds_noscores_df.csv', index=False)

In [225]:
score_list_2 = []
for i in range(0, len(revids_preds_noscores_df)):
    id = int(revids_preds_noscores_df['revid'][i]) # convert to int
    score = request_ores_score_per_article(article_revid=id,
                                       email_address="tejalk@uw.edu",
                                       access_token=ACCESS_TOKEN)
    print(id) # make sure API is running through revids
    score_list_2.append(score)

1166229686
1174673505
1174673519
1172669651
1178675089
1174673937
1167102310
1169358992
1174674581
1175683666
1175485812
1174676598
1132494463
1170938718
1172987370
1178789607
1177414099
1170996326
1169350309
1166067028
1177286983
1161182691
1166067098
1166067147
1175561044
1140222341
1166067224
1179192848
1166508337
1167233752
1178070516
1171251527
1166067515
1176918417
1178153297
1178882062
1169442815
1179277288
1177783028
1178284864
1174683020
1176063097
1178729348
1179365985
1179452951
1169330645
1166673816
1178974129
1179710244
1166069613
1166069631
1178800086
1172717547
1177741358
1169352708
1175567255
1166180134
1170251512
1174443299
1171021618
1179715406
1166180371
1166180407
1168800169
1166180455
1166180476
1178473616
1176117284
1166180700
1178516564
1174707560
1166180805
1178863447
1166181113
1169799205
1166181192
1166181223
1174795329
1179577229
1166181369
1179392250
1166181474
1175693899
1172852301
1166181562
1161181616
1176263428
1179048083
1170887830
1166205523
1168146546

1177398947
1141957344
1166850738
1166850852
1174677630
1166850894
1174677687
1166849798
1179498324
1167462140
1132507834
1170083147
1166851270
1174677797
1166851643
1176701461
1170754690
1166852897
1174678012
1166852947
1174678040
1138393902
1168638628
1161152443
1166854329
1166854325
1174678318
1174797548
1172003079
1174678429
1172296560
1174678467
1166855451
1174678564
1174678496
1138001086
1169586518
1173242918
1165553360
1168220111
1178262553
1166991577
1177926179
1155701334
1132565132
1176874237
1132565112
1166991722
1174678899
1174678924
1132565198
1174679109
1174679125
1166992286
1166992533
1174679273
1166992661
1177514282
1174679348
1166993036
1166993085
1174679390
1174679580
1174679597
1166993748
1169895196
1166993545
1166993800
1174679688
1174679710
1166994142
1174679762
1174680422
1174680450
1174680470
1174680367
1165320175
1174680526
1166994944
1174680561
1174680675
1132566344
1166995395
1174680698
1171038167
1166995443
1174680782
1166995867
1174680894
1166996151
1174681113

1167411587
1133247419
1167411043
1167411675
1167411184
1167411233
1175692300
856537181
1133247981
1167411890
1153671918
1167411974
1167412043
1167412047
1167412084
1173469200
1167412162
1167412217
1173882814
1167412225
1167412338
1172474740
1171235816
1168705619
1169114624
1167424260
1178152503
1167424510
1167424641
1167424689
1167425924
1167425946
1167425996
1167426005
1142678440
1133249387
1168842341
1176982981
1168257449
1174458417
1167426450
1179049008
1167426477
1168637528
1168637517
1167426521
1167453855
1167453858
1167453912
1158532850
1167454067
1167454257
201818773
1167454415
1142874269
1167454584
1167454771
1167454775
201825363
34414516
1167455011
1167455332
1167455352
1162041289
1177340573
1167455391
1167455499
1167455560
1168312810
1167455818
1142640991
1167455821
1167455904
1174981299
201864255
1167456088
951131305
1167456861
1170591370
1138394523
1167457413
1175281253
1167457518
1167457730
1167457727
1167458229
1167458282
1167458246
1167458542
1174844047
1167458720
116745

1165899548
1172242820
1165748235
1176983940
1170033989
1165748531
1176545885
1179748918
1165894133
1179373148
1165897860
1165646449
1165956065
1169370586
1170355708
1178289279
1165750789
1169523126
1173493544
1165893122
1167971914
1165898049
1165894047
1175884108
1178257357
1179061386
1165901931
1173226179
1165536916
1178558660
1165647518
1179162574
1156791128
1177880194
1165898822
1165890141
1173232139
1170365867
1175893503
1167464815
1171294735
1165748712
1165894650
1173253941
1165646961
1165506281
1178459077
1178233684
1170887827
1165536941
1161131345
1166998402
1175712314
1165748136
1165897460
1165906347
1176045812
1176062797
1165892659
1165752692
1177437660
1165751064
1175359047
1165897536
1165645706
1169929462
1175251509
1179661089
1173271940
1165896554
1177617831
1165749469
1178923795
1165507517
1168624372
1172350513
1165892078
1170513536
1175700936
1165900792
1170235067
1175712535
1144036352
1171754615
1165895592
1176978186
1162259151
1165651026
1165896790
1162741756
1174709464

1168636912
1167173891
1166066506
1166066746
1175768805
1166066297
1150129923
1166066981
1166877462
1178799857
1170521349
1166067115
1165647456
1166067445
1166992234
1157605417
1179356372
1166067739
1166067844
1165650888
1176361787
1166068051
1166068099
1169905013
1166068318
1165746999
1171249078
1165747140
1166068806
1179548228
1167951191
1167019864
1165747791
1166069196
1166069475
1167021562
1130432586
1155969925
1166069521
1174868009
1178595232
1167783753
1178595421
1179317199
1166180242
1176861506
1166180702
1177430837
1165749558
1179418694
1172547691
1166180960
1166180945
1165750216
1165750254
1165750404
1161479292
1173749164
1168110955
1168111038
1165750966
1175721491
1179668204
321451964
1166182116
1175145640
1177468238
1167291748
1166205360
1166205450
1175429757
1157006218
1179263613
1175143027
1167418158
1166048386
1165890235
1165891260
1166206322
1166206339
1165891449
1165891572
1166206485
1165891602
1166206587
1166206604
1176138949
1166207311
1165892861
1178023135
1167179287


1175954551
1174273659
1158103823
1175380100
1172051125
1166636568
1177458623
1157350518
1173398071
1173397916
1171091114
1167293988
1157351528
1172051191
1157361234
1172125470
1175074620
1162528578
1175374030
1173807765
1157438603
1173809380
1167392327
1175379038
1173705958
1157354973
1175375135
1179429493
1172882651
1175955456
1172105822
1172101657
1174557558
1175230875
1175381398
1170367596
1175382483
1178632655
1153589424
1178768111
1175956750
1174294312
1175874133
1171747803
1173676681
1157355384
1160605334
1167679991
1169337971
1175372444
1167498865
1174874054
1174318672
1158806090
1179453817
1159119717
1167128167
1175381291
1167178619
1178880959
1157440286
1157445510
1173517818
1173540546
1170742193
1167128508
1169323941
1157437315
1159983460
1167507282
1173293677
1167426013
1167316479
1175379427
1167127516
1167178917
1173397803
1173813546
1172050264
1175374188
1169748425
1167739274
1157446321
1174221765
1174295605
1176646419
1173811730
1175957233
1166612187
1175382237
1168785991

1176777842
1171418255
1179352520
1159984615
1175372541
1161079385
1175371021
1167292361
1157361796
1172530062
1173792427
1175371719
1175380608
1175502843
1157444576
1160603861
1169091499
1158103275
1157355437
1159988299
1099141448
1158101369
1175384195
1172104273
1157359936
1171055052
1157360181
1176176215
1176756204
1157360100
1175873392
1171938638
1157445178
1160604778
1166993225
1177815637
1159545823
1157438967
1167836802
1175380255
1169062096
1176320013
1175381297
1167126914
1172681704
1167017367
1157741405
1145603355
1157361815
1175503710
1167130736
1176887168
1175378412
1177363938
1178758776
1169043148
1177814409
1175381950
1177950616
1167316207
1132679016
1158100876
1175369949
1173806981
1175956995
1158103126
1175955192
1152769006
1146486415
1143116762
1174717625
1174300651
1157349750
1174220865
1169133815
1173809808
1175247948
1171058914
1171904954
1174298371
1166756548
1172688557
1158113854
1172125066
1175955920
1172047132
1161760397
1175373384
1174110778
1173994194
1175382742

1165749196
1172198759
1179559876
1174007173
1172242969
1172243004
1172243054
1175262212
1172243297
1179188075
1166181291
1166181335
1165750836
1176444911
1159458768
1166181773
1173679744
1141260513
1173679980
1166181968
1166181982
1165751231
1173680205
1166182101
1166182321
1173680853
1175796239
1173682291
1179597052
1173682412
1173682471
1165752940
1165752955
1173682565
1173682682
1174658343
1173683075
1175669747
1173683466
1173683843
1173683929
1177926425
1173684002
1165891378
1173684067
1173684105
1173684139
1172044185
1173684181
1159461933
1175708970
1171664560
1173688603
1173704533
1165892002
1179734018
1174507091
1173688206
1173704577
1177941057
1173704807
1166208709
1177321528
1165894730
1175861661
1173705227
1167621361
1165895189
1173705418
1173705157
1173705465
1177411131
1153472951
1174657096


I create a new dataframe, *revids_preds_df_2*, where I save the revision IDs and predictions of this subset of articles.

In [229]:
revids2 = []
preds2 = []

for i in range(0, len(score_list_2)):
    revid = str(revids_preds_noscores_df['revid'][i])
    if list(score_list_2[i])[0]=='enwiki':
        pred = score_list_2[i]['enwiki']['scores'][revid]['articlequality']['score']['prediction']
    else:
        pred = None # if unable to get score for this article
    revids2.append(revid)
    preds2.append(pred)

In [230]:
# save revid and predictions in df
revids_preds_df_2 = pd.DataFrame({'revid':revids2,'prediction':preds2})

# View df
revids_preds_df_2.head()

revid prediction
0  1166229686      Start
1  1174673505          C
2  1174673519          C
3  1172669651          C
4  1178675089          C

In order to add these revision IDs and predictions to my dataframe containing articles with ORES scores, I concatenate the following dataframes: *revids_preds_scores_df* and *revids_preds_df_2*. I also drop null values to ensure that this dataframe only contains articles for which I was able to obtain ORES scores. The resulting dataframe is named *revids_preds_scores_df_all*.

In [269]:
revids_preds_scores_df_all = pd.concat([revids_preds_scores_df,revids_preds_df_2]).dropna().reset_index(drop=True)

len(revids_preds_scores_df_all)

21196

I also create a new dataframe for articles without ORES scores. This dataframe is called *revids_preds_noscores_df2*.

In [279]:
# Df for articles without ORES Score
revids_preds_noscores_df2 = pd.concat([revids_preds_scores_df,revids_preds_df_2])[pd.concat([revids_preds_scores_df,revids_preds_df_2])['prediction'].isnull()].reset_index(drop=True)

# Convert column type to merge
revids_preds_noscores_df2['revid'] = revids_preds_noscores_df2['revid'].astype(int)

# Merge with table to show corresponding article titles
revids_preds_noscores_df2 = revids_preds_noscores_df2.merge(titles_revids_df)

len(revids_preds_noscores_df2)

329

In [283]:
revids_preds_noscores_df2['title'].unique()

array(['Malvern, Pennsylvania',
       'Gray Township, Greene County, Pennsylvania',
       'Landisburg, Pennsylvania', 'Ursina, Pennsylvania',
       'Elgin, Pennsylvania',
       'Centerville, Crawford County, Pennsylvania',
       'Glenfield, Pennsylvania', 'Shippingport, Pennsylvania',
       'Cherry Grove Township, Warren County, Pennsylvania',
       'Karns City, Pennsylvania', 'Petrolia, Pennsylvania',
       'Duncan Township, Tioga County, Pennsylvania',
       'Stillwater, Pennsylvania',
       'North Branch Township, Wyoming County, Pennsylvania',
       'Barkeyville, Pennsylvania', 'Callensburg, Pennsylvania',
       'Newton Hamilton, Pennsylvania', 'Addison, Pennsylvania',
       'Marklesburg, Pennsylvania',
       'Benezette Township, Elk County, Pennsylvania',
       'Colebrook Township, Clinton County, Pennsylvania',
       'Clara Township, Potter County, Pennsylvania',
       'Fairview, Butler County, Pennsylvania', 'Chapman, Pennsylvania',
       'Mount Gretna, Pennsyl

At this point, there are still 329 articles (listed above) without an ORES score. I run this subset of articles through the API a final time to see if I am able to obtain an ORES score. Once again, I go through the same process for using the ORES API.

I also use the same process as above for creating a final dataframe only contains articles for which I was able to obtain ORES scores

In [265]:
score_list_3 = []
for i in range(0, len(revids_preds_noscores_df2)):
    id = int(revids_preds_noscores_df2['revid'][i]) # convert to int
    score = request_ores_score_per_article(article_revid=id,
                                       email_address="tejalk@uw.edu",
                                       access_token=ACCESS_TOKEN)
    print(id) # make sure API is running through revids
    score_list_3.append(score)

1179414836
1167127407
1157437993
1152766950
1169067223
1172103722
1168983420
1176901114
1173803047
1177625122
1177918832
1173730832
1158105974
1175954579
1169089320
1157351827
1175076006
1157348789
1157440069
1172124966
1166756223
1166696053
1177865520
1171085761
1169015035
1157452459
1173293849
1169325989
1159221803
1177807207
805119630
1167679471
1174370970
1169338006
1176483354
1157444403
1157356666
1157359163
1074075120
1167296764
1170376213
1178183223
1175371838
1167129017
1176379419
1177806632
1160842750
1158250300
1169924892
1173397827
1169508880
1157438107
1174371543
1171355501
1167020594
1157437987
1157348799
1176777848
1172105445
1158114285
1158102634
1176440016
1157354494
1156981946
1159190103
1177806705
1157352036
1169338141
1169056796
1157448175
1175380244
1152768158
1159221532
1157455357
1141451948
1157443987
1176316625
1158102425
1145498614
1173809925
1174460788
1157356461
1170119577
1176419728
1152768236
1157355024
1170965230
1169073087
1173170320
1166986070
1140359812


In [266]:
revids3 = []
preds3 = []

for i in range(0, len(score_list_3)):
    revid = str(revids_preds_noscores_df2['revid'][i])
    if list(score_list_3[i])[0]=='enwiki':
        pred = score_list_3[i]['enwiki']['scores'][revid]['articlequality']['score']['prediction']
    else:
        pred = None # if unable to get score for this article
    revids3.append(revid)
    preds3.append(pred)

In [267]:
# save revid and predictions in df for this subset of data
revids_preds_df_3 = pd.DataFrame({'revid':revids3,'prediction':preds3})

In [268]:
# Write to CSV FILE just in case for now
revids_preds_df_3.to_csv('revids_preds_df_3.csv', index=False)

In [273]:
# Dataframe for articles with ORES Score
revids_preds_scores_final = pd.concat([revids_preds_scores_df_all, revids_preds_df_3]).dropna().reset_index(drop=True)
len(revids_preds_scores_final)

21525

In [284]:
# Articles without ORES Score
len(pd.concat([revids_preds_scores_df_all,revids_preds_df_3])[pd.concat([revids_preds_scores_df_all,revids_preds_df_3])['prediction'].isnull()].reset_index(drop=True))

0

As shown above, my final dataframe, *revids_preds_scores_final* now contains ORES scores for all 21,525 articles. At this point, there is no article for which I was unable to obtain an ORES score.

## Combining the Datasets

The next step in this analysis involves combining the datasets obtained above. First, I merge the dataset with the page titles and revision IDs (*titles_revids_df*) and the dataset with the revision IDs and predictions (*revids_preds_scores_final*).

In [285]:
# Convert column type to merge
revids_preds_scores_final['revid'] = revids_preds_scores_final['revid'].astype(int)

# Merge dataframes
pages_revids_predictions = titles_revids_df.merge(revids_preds_scores_final)

pages_revids_predictions.head()

title       revid prediction
0   Abbeville, Alabama  1171163550          C
1  Adamsville, Alabama  1177621427          C
2     Addison, Alabama  1168359898          C
3       Akron, Alabama  1165909508         GA
4   Alabaster, Alabama  1179139816          C

Next, we add a *state* column to the dataframe. These values are obtained by performing a join with the current dataframe (*pages_revids_predictions*) and the *us_cities_by_state_df* dataframe. Prior to performing this merge, we further clean the *us_cities_by_state_df* dataframe to ensure naming convention consistency with the other tables.

In [286]:
# Clean data to ensure consistency with other tables
# Replace underscores between words with spaces (e.g. 'New_York' to 'New York')
us_cities_by_state_df['state'] = us_cities_by_state_df['state'].str.replace("_", " ")

In [287]:
# Replace "Georgia (U.S. state)" with "Georgia"
us_cities_by_state_df['state'] = us_cities_by_state_df['state'].str.replace("Georgia (U.S. state)", "Georgia",regex=False)
us_cities_by_state_df['state'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [382]:
# Merge dataframes to obtain state columns
pages_revids_predictions_merged = pages_revids_predictions.merge(us_cities_by_state_df, how='left', left_on='title', right_on='page_title').drop(columns=['url','page_title'])

pages_revids_predictions_merged.head()

title       revid prediction    state
0   Abbeville, Alabama  1171163550          C  Alabama
1  Adamsville, Alabama  1177621427          C  Alabama
2     Addison, Alabama  1168359898          C  Alabama
3       Akron, Alabama  1165909508         GA  Alabama
4   Alabaster, Alabama  1179139816          C  Alabama

After this, we merge this dataframe with the dataframe containing information about state populations (*pop_estimates_df*).

In [383]:
# Merge dataframes
pages_revids_predictions_merged = pages_revids_predictions_merged.merge(pop_estimates_df, how='left', left_on='state', right_on='NAME').drop(columns=['NAME'])

pages_revids_predictions_merged.head()

title       revid prediction    state  POPESTIMATE2022
0   Abbeville, Alabama  1171163550          C  Alabama          5074296
1  Adamsville, Alabama  1177621427          C  Alabama          5074296
2     Addison, Alabama  1168359898          C  Alabama          5074296
3       Akron, Alabama  1165909508         GA  Alabama          5074296
4   Alabaster, Alabama  1179139816          C  Alabama          5074296

Next, we merge this dataframe with the dataframe containing information about states and regions created above (*states_regions_df*).

In [384]:
# Merge dataframes 
pages_revids_predictions_merged = pages_revids_predictions_merged.merge(states_regions_df, how='left', left_on='state', right_on='STATE').drop(columns=['STATE'])

pages_revids_predictions_merged.head()

title       revid prediction    state  POPESTIMATE2022  \
0   Abbeville, Alabama  1171163550          C  Alabama          5074296   
1  Adamsville, Alabama  1177621427          C  Alabama          5074296   
2     Addison, Alabama  1168359898          C  Alabama          5074296   
3       Akron, Alabama  1165909508         GA  Alabama          5074296   
4   Alabaster, Alabama  1179139816          C  Alabama          5074296   

  REGION            DIVISION  
0  South  East South Central  
1  South  East South Central  
2  South  East South Central  
3  South  East South Central  
4  South  East South Central

I rename and reorder the columns to clean the overall dataframe.

In [385]:
# Rename columns
pages_revids_predictions_merged.rename(columns={"title": "article_title", "revid": "revision_id", "prediction":"article_quality", "POPESTIMATE2022": "population", "DIVISION": "regional_division"}, inplace=True)

# Drop extra columns
pages_revids_predictions_merged = pages_revids_predictions_merged.drop(columns=['REGION'])

# Reoder columns
pages_revids_predictions_merged = pages_revids_predictions_merged[['state', 'regional_division', 'population', 'article_title', 'revision_id', 'article_quality']]

pages_revids_predictions_merged.head()

state   regional_division  population        article_title  revision_id  \
0  Alabama  East South Central     5074296   Abbeville, Alabama   1171163550   
1  Alabama  East South Central     5074296  Adamsville, Alabama   1177621427   
2  Alabama  East South Central     5074296     Addison, Alabama   1168359898   
3  Alabama  East South Central     5074296       Akron, Alabama   1165909508   
4  Alabama  East South Central     5074296   Alabaster, Alabama   1179139816   

  article_quality  
0               C  
1               C  
2               C  
3              GA  
4               C

The final dataframe is named *pages_revids_predictions_merged* and is shown above. I save this in a csv file called *wp_scored_city_articles_by_state.csv*. Please note that in the above table, the column *population* refers to the population of the state.

In [386]:
# Write to CSV file
pages_revids_predictions_merged.to_csv('wp_scored_city_articles_by_state.csv', index=False)

### Areas with No Matches

When merging the data, we come across entries which can not be trivially merged. The list below outlines areas for which there are no matches. Specifically, this list indicates areas that are present in the US Census Bureau population dataset, which are not present in the 'U.S. Cities by State' Wikipedia article dataset. As seen below, most of these areas are non-states. However, two states appear: Connecticut and Nebraska. As mentioned above, these two states are not present in the original Wikipedia dataset. For this reason, we do not include them in our analysis.

In [317]:
list(set(pop_estimates_df['NAME'].unique()) - set(pages_revids_predictions_merged['state'].unique()))

['South Atlantic',
 'East South Central',
 'East North Central',
 'Northeast Region',
 'New England',
 'Middle Atlantic',
 'Pacific',
 'Mountain',
 'West Region',
 'Midwest Region',
 'West North Central',
 'Puerto Rico',
 'United States',
 'District of Columbia',
 'Nebraska',
 'Connecticut',
 'West South Central',
 'South Region']

## Analysis

This portion of the analysis focuses on calculating total-articles-per-population (a ratio representing the number of articles per person)  and high-quality-articles-per-population (a ratio representing the number of high quality articles per person) on a state-by-state and divisional basis. All of these values are “per capita” ratios.

For the purposes of this analysis, I consider "high quality" articles to be articles that ORES predicts as being in either the "FA" (featured article) or "GA" (good article) classes.

In order to calculate the total-articles-per-population by state, I first create a table that sums the number of articles per state. I join this dataframe with the *pop_estimates_df* dataframe to bring in the estimated population for each state. Next, I create a new column, *articles_per_person*, which is calculated by dividing the number of articles by the estimated population for each state. My final dataframe is named *articles_per_pop_state*.

In [344]:
# Number of articles per state
articles_per_pop_state = pages_revids_predictions_merged.groupby('state').size().reset_index(name='row_count')

# Merge dataframes to bring in populations
articles_per_pop_state = articles_per_pop_state.merge(pop_estimates_df, how='left', left_on='state', right_on='NAME').drop(columns=['NAME'])

# Calculate articles per person
articles_per_pop_state['articles_per_person'] = (articles_per_pop_state['row_count']/articles_per_pop_state['POPESTIMATE2022'])

# Rename columns
articles_per_pop_state = articles_per_pop_state.rename(columns={"row_count": "number_of_articles", "POPESTIMATE2022": "population"})

articles_per_pop_state.head()

state  number_of_articles  population  articles_per_person
0     Alabama                 461     5074296             0.000091
1      Alaska                 149      733583             0.000203
2     Arizona                  91     7359197             0.000012
3    Arkansas                 500     3045637             0.000164
4  California                 482    39029342             0.000012

Next, I want to calculate the number of high-quality-articles-per-population on a divisional basis. I follow the same general process as above, however this time, I focus on divisions rather than states.

In [367]:
# Number of articles per division
articles_per_pop_div = pages_revids_predictions_merged.groupby('regional_division').size().reset_index(name='row_count')

# Merge dataframes to bring in populations
articles_per_pop_div = articles_per_pop_div.merge(pop_estimates_df, how='left', left_on='regional_division', right_on='NAME').drop(columns=['NAME'])

# Calculate articles per person
articles_per_pop_div['articles_per_person'] = (articles_per_pop_div['row_count']/articles_per_pop_div['POPESTIMATE2022'])

# Rename columns
articles_per_pop_div = articles_per_pop_div.rename(columns={"row_count": "number_of_articles", "POPESTIMATE2022": "population"})

# Sort by total articles per capita (descending)
articles_per_pop_div.sort_values(by=['articles_per_person'], inplace=True, ascending=False)

articles_per_pop_div = articles_per_pop_div.reset_index(drop=True)

articles_per_pop_div.head()

regional_division  number_of_articles  population  articles_per_person
0  West North Central                3593    21689816             0.000166
1  East North Central                4769    47097779             0.000101
2         New England                1437    15129548             0.000095
3     Middle Atlantic                3784    41910858             0.000090
4  East South Central                1544    19578002             0.000079

I am now interested in observing the number of high quality articles per state. I begin by filtering my *pages_revids_predictions_merged* to only include articles that have an *article_quality* of "FA" or "GA".

In [364]:
high_quality_articles = pages_revids_predictions_merged[pages_revids_predictions_merged['article_quality'].isin(["FA","GA"])]

high_quality_articles = high_quality_articles.reset_index(drop=True)

high_quality_articles.head()

state   regional_division  statepopulation            article_title  \
0  Alabama  East South Central          5074296           Akron, Alabama   
1  Alabama  East South Central          5074296  Alexander City, Alabama   
2  Alabama  East South Central          5074296      Aliceville, Alabama   
3  Alabama  East South Central          5074296         Ardmore, Alabama   
4  Alabama  East South Central          5074296      Bear Creek, Alabama   

   revision_id article_quality  
0   1165909508              GA  
1   1179140073              GA  
2   1167792390              GA  
3   1176903479              GA  
4   1166015184              GA

Then, I calculate the number of high-quality articles by state. I follow a similar process as above, where I calculated the total number of articles per state. However, this time, I begin by using my filtered dataframe.

In [365]:
# Number of high quality articles per state
qual_articles_per_pop_state = high_quality_articles.groupby('state').size().reset_index(name='row_count')

# Merge dataframes to bring in populations
qual_articles_per_pop_state = qual_articles_per_pop_state.merge(pop_estimates_df, how='left', left_on='state', right_on='NAME').drop(columns=['NAME'])

# Calculate articles per person
qual_articles_per_pop_state['articles_per_person'] = (qual_articles_per_pop_state['row_count']/qual_articles_per_pop_state['POPESTIMATE2022'])

# Rename columns
qual_articles_per_pop_state = qual_articles_per_pop_state.rename(columns={"row_count": "number_of_articles", "POPESTIMATE2022": "population"})

qual_articles_per_pop_state.head()

state  number_of_articles  population  articles_per_person
0     Alabama                  53     5074296             0.000010
1      Alaska                  31      733583             0.000042
2     Arizona                  24     7359197             0.000003
3    Arkansas                  72     3045637             0.000024
4  California                 172    39029342             0.000004

I follow a similar process to calculate the total number of high-quality articles per regional division.

In [368]:
# Number of high quality articles per division
qual_articles_per_pop_div = high_quality_articles.groupby('regional_division').size().reset_index(name='row_count')

# Merge dataframes to bring in populations
qual_articles_per_pop_div = qual_articles_per_pop_div.merge(pop_estimates_df, how='left', left_on='regional_division', right_on='NAME').drop(columns=['NAME'])

# Calculate articles per person
qual_articles_per_pop_div['articles_per_person'] = (qual_articles_per_pop_div['row_count']/qual_articles_per_pop_div['POPESTIMATE2022'])

# Rename columns
qual_articles_per_pop_div = qual_articles_per_pop_div.rename(columns={"row_count": "number_of_articles", "POPESTIMATE2022": "population"})

# Sort by total articles per capita (descending)
qual_articles_per_pop_div.sort_values(by=['articles_per_person'], inplace=True, ascending=False)

qual_articles_per_pop_div = qual_articles_per_pop_div.reset_index(drop=True)

qual_articles_per_pop_div.head()

regional_division  number_of_articles  population  articles_per_person
0  West North Central                 653    21689816             0.000030
1     Middle Atlantic                1056    41910858             0.000025
2  East South Central                 331    19578002             0.000017
3  East North Central                 727    47097779             0.000015
4  West South Central                 637    41685250             0.000015

## Results

I print the results of my analysis below, formatted as six tables. For each table, I sort the values (either by ascending or descending based on the requirements), display either the top 10 results or the complete set of results (once again based on the requirements) and reset the index.

### Top 10 US states by coverage
#### The 10 US states with the highest total articles per capita (in descending order)

In [373]:
articles_per_pop_state.sort_values(by=['articles_per_person'], ascending=False).head(10).reset_index(drop=True)

state  number_of_articles  population  articles_per_person
0        Vermont                 329      647064             0.000508
1   North Dakota                 356      779261             0.000457
2          Maine                 483     1385340             0.000349
3   South Dakota                 311      909824             0.000342
4           Iowa                1058     3200517             0.000331
5         Alaska                 149      733583             0.000203
6   Pennsylvania                2556    12972008             0.000197
7       Michigan                1773    10034113             0.000177
8        Wyoming                  99      581381             0.000170
9  New Hampshire                 234     1395231             0.000168

### Bottom 10 US states by coverage
#### The 10 US states with the lowest total articles per capita (in ascending order) 

In [374]:
articles_per_pop_state.sort_values(by=['articles_per_person'], ascending=True).head(10).reset_index(drop=True)

state  number_of_articles  population  articles_per_person
0  North Carolina                  50    10698973             0.000005
1          Nevada                  19     3177772             0.000006
2      California                 482    39029342             0.000012
3         Arizona                  91     7359197             0.000012
4        Virginia                 133     8683619             0.000015
5        Oklahoma                  75     4019800             0.000019
6         Florida                 427    22244823             0.000019
7          Kansas                  63     2937150             0.000021
8        Maryland                 157     6164660             0.000025
9        New York                 664    19677151             0.000034

### Top 10 US states by high quality
#### The 10 US states with the highest high quality articles per capita (in descending order)

In [375]:
qual_articles_per_pop_state.sort_values(by=['articles_per_person'], ascending=False).head(10).reset_index(drop=True)

state  number_of_articles  population  articles_per_person
0        Vermont                  45      647064             0.000070
1        Wyoming                  39      581381             0.000067
2   South Dakota                  56      909824             0.000062
3  West Virginia                 105     1775156             0.000059
4        Montana                  55     1122867             0.000049
5  New Hampshire                  63     1395231             0.000045
6   Pennsylvania                 566    12972008             0.000044
7       Missouri                 263     6177957             0.000043
8         Alaska                  31      733583             0.000042
9     New Jersey                 379     9261699             0.000041

### Bottom 10 US states by high quality
#### The 10 US states with the lowest high quality articles per capita (in ascending order)

In [376]:
qual_articles_per_pop_state.sort_values(by=['articles_per_person'], ascending=True).head(10).reset_index(drop=True)

state  number_of_articles  population  articles_per_person
0  North Carolina                  20    10698973             0.000002
1        Virginia                  18     8683619             0.000002
2          Nevada                   8     3177772             0.000003
3         Arizona                  24     7359197             0.000003
4      California                 172    39029342             0.000004
5        New York                 111    19677151             0.000006
6         Florida                 134    22244823             0.000006
7        Maryland                  42     6164660             0.000007
8          Kansas                  22     2937150             0.000007
9        Oklahoma                  31     4019800             0.000008

### Census divisions by total coverage
#### A rank ordered list of US census divisions (in descending order) by total articles per capita

In [377]:
articles_per_pop_div

regional_division  number_of_articles  population  articles_per_person
0  West North Central                3593    21689816             0.000166
1  East North Central                4769    47097779             0.000101
2         New England                1437    15129548             0.000095
3     Middle Atlantic                3784    41910858             0.000090
4  East South Central                1544    19578002             0.000079
5  West South Central                2112    41685250             0.000051
6            Mountain                1195    25514320             0.000047
7      South Atlantic                1865    67452940             0.000028
8             Pacific                1304    53229044             0.000024

### Census divisions by high quality coverage
#### Rank ordered list of US census divisions (in descending order) by high quality articles per capita

In [378]:
qual_articles_per_pop_div

regional_division  number_of_articles  population  articles_per_person
0  West North Central                 653    21689816             0.000030
1     Middle Atlantic                1056    41910858             0.000025
2  East South Central                 331    19578002             0.000017
3  East North Central                 727    47097779             0.000015
4  West South Central                 637    41685250             0.000015
5         New England                 225    15129548             0.000015
6            Mountain                 339    25514320             0.000013
7             Pacific                 489    53229044             0.000009
8      South Atlantic                 540    67452940             0.000008